.BANK 14
.ORG $0000

.SECTION "Bank13" FORCE

.db $FF
.db $FF
.db $FF
.db $FF
.db $47
.db $C8
.db $C8
.db $47
.db $99
.db $C8
.db $99
.db $47
.db $47
.db $C8
.db $99
.db $47
.db $59
.db $68
.db $68
.db $59
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $81
.db $68
.db $B2
.db $59
.db $AA
.db $AA
.db $AA
.db $AA
.db $49
.db $AA
.db $49
.db $AA
.db $AA
.db $AA
.db $49
.db $AA
.db $49
.db $A1
.db $49
.db $A1
.db $AB
.db $AB
.db $AB
.db $AB
.db $AC
.db $AB
.db $AC
.db $AB
.db $AB
.db $AB
.db $AC
.db $AB
.db $A1
.db $AC
.db $A1
.db $AC
.db $9A
.db $AB
.db $AB
.db $AB
.db $AB
.db $AB
.db $9A
.db $AB
.db $86
.db $87
.db $AB
.db $AB
.db $AB
.db $AB
.db $86
.db $87
.db $77
.db $77
.db $AB
.db $AB
.db $77
.db $77
.db $AA
.db $AA
.db $AC
.db $AB
.db $AB
.db $AB
.db $49
.db $AA
.db $AA
.db $AA
.db $6E
.db $6F
.db $7E
.db $7F
.db $4E
.db $4F
.db $5E
.db $5F
.db $48
.db $48
.db $48
.db $48
.db $58
.db $48
.db $58
.db $48
.db $48
.db $48
.db $58
.db $48
.db $49
.db $58
.db $49
.db $58
.db $C8
.db $C8
.db $68
.db $C8
.db $8D
.db $8D
.db $8D
.db $8D
.db $8F
.db $8F
.db $8F
.db $8F
.db $8F
.db $8F
.db $9F
.db $8F
.db $8D
.db $AD
.db $AD
.db $AE
.db $AE
.db $AE
.db $AE
.db $AE
.db $AF
.db $8F
.db $AE
.db $AF
.db $6C
.db $6D
.db $AB
.db $AB
.db $6C
.db $6D
.db $AA
.db $AA
.db $6C
.db $6D
.db $AC
.db $AB
.db $45
.db $55
.db $55
.db $45
.db $46
.db $55
.db $56
.db $45
.db $45
.db $55
.db $56
.db $45
.db $46
.db $56
.db $56
.db $46
.db $67
.db $67
.db $67
.db $67
.db $B2
.db $99
.db $B2
.db $99
.db $B0
.db $68
.db $B0
.db $68
.db $68
.db $B1
.db $68
.db $B1
.db $68
.db $68
.db $68
.db $68
.db $68
.db $68
.db $B2
.db $68
.db $68
.db $C8
.db $68
.db $C8
.db $57
.db $57
.db $57
.db $57
.db $A1
.db $57
.db $A1
.db $57
.db $57
.db $57
.db $A1
.db $57
.db $6A
.db $6B
.db $6A
.db $6B
.db $6A
.db $69
.db $6A
.db $69
.db $69
.db $69
.db $69
.db $69
.db $69
.db $6B
.db $69
.db $6B
.db $9B
.db $9C
.db $AA
.db $AA
.db $AA
.db $AA
.db $9B
.db $9C
.db $9B
.db $9C
.db $9B
.db $9C
.db $78
.db $79
.db $79
.db $78
.db $47
.db $C6
.db $C6
.db $D8
.db $C7
.db $C8
.db $D8
.db $C7
.db $D6
.db $D8
.db $C8
.db $D6
.db $D8
.db $D7
.db $D7
.db $47
.db $D8
.db $D8
.db $D8
.db $D8
.db $D8
.db $D7
.db $D8
.db $C7
.db $D6
.db $D8
.db $C6
.db $D8
.db $C7
.db $C6
.db $D8
.db $D8
.db $D8
.db $D8
.db $D7
.db $D6
.db $C8
.db $C8
.db $C8
.db $C8
.db $C8
.db $C8
.db $68
.db $C8
.db $BB
.db $BC
.db $CB
.db $CC
.db $BB
.db $BC
.db $FF
.db $FF
.db $8E
.db $8E
.db $C8
.db $47
.db $8E
.db $99
.db $C8
.db $47
.db $88
.db $79
.db $89
.db $78
.db $78
.db $79
.db $89
.db $78
.db $B0
.db $68
.db $E7
.db $E9
.db $68
.db $B1
.db $E9
.db $E8
.db $E5
.db $EA
.db $B0
.db $68
.db $EA
.db $E6
.db $68
.db $B1
.db $EA
.db $EA
.db $68
.db $68
.db $68
.db $68
.db $E9
.db $E9
.db $48
.db $48
.db $49
.db $58
.db $C8
.db $C8
.db $C8
.db $C8
.db $8D
.db $8D
.db $8D
.db $8D
.db $8F
.db $8F
.db $8F
.db $8F
.db $8F
.db $8F
.db $9F
.db $8F
.db $8D
.db $AD
.db $AD
.db $AE
.db $AE
.db $AE
.db $AE
.db $AE
.db $AF
.db $8F
.db $AE
.db $AF
.db $43
.db $53
.db $53
.db $43
.db $B8
.db $B8
.db $6C
.db $6D
.db $B8
.db $B8
.db $7D
.db $7D
.db $B8
.db $75
.db $7D
.db $B4
.db $C8
.db $B8
.db $7C
.db $7D
.db $B8
.db $75
.db $B8
.db $75
.db $B8
.db $B8
.db $B8
.db $B8
.db $A7
.db $A7
.db $86
.db $87
.db $77
.db $77
.db $77
.db $77
.db $A9
.db $A9
.db $98
.db $98
.db $A7
.db $A7
.db $A9
.db $A9
.db $AA
.db $97
.db $A1
.db $97
.db $52
.db $CA
.db $62
.db $DA
.db $85
.db $74
.db $85
.db $98
.db $74
.db $85
.db $98
.db $85
.db $8C
.db $A7
.db $85
.db $74
.db $A7
.db $8C
.db $74
.db $85
.db $97
.db $AC
.db $97
.db $AC
.db $AB
.db $97
.db $AB
.db $97
.db $97
.db $A1
.db $97
.db $A1
.db $AA
.db $97
.db $AA
.db $97
.db $80
.db $80
.db $80
.db $80
.db $A7
.db $A7
.db $90
.db $80
.db $A0
.db $80
.db $65
.db $80
.db $8C
.db $A7
.db $97
.db $90
.db $A7
.db $A7
.db $80
.db $80
.db $A7
.db $8C
.db $80
.db $97
.db $97
.db $A0
.db $97
.db $65
.db $80
.db $97
.db $80
.db $97
.db $8C
.db $A7
.db $85
.db $4C
.db $A7
.db $8C
.db $4D
.db $85
.db $85
.db $5C
.db $85
.db $98
.db $5D
.db $85
.db $98
.db $85
.db $04
.db $04
.db $42
.db $42
.db $52
.db $52
.db $62
.db $62
.db $2F
.db $02
.db $3F
.db $B9
.db $05
.db $2F
.db $BA
.db $3F
.db $3F
.db $C9
.db $3F
.db $D9
.db $CA
.db $3F
.db $DA
.db $3F
.db $39
.db $32
.db $42
.db $42
.db $38
.db $39
.db $42
.db $42
.db $02
.db $04
.db $B9
.db $42
.db $04
.db $05
.db $42
.db $BA
.db $C9
.db $52
.db $D9
.db $62
.db $52
.db $CA
.db $62
.db $DA
.db $39
.db $49
.db $9D
.db $49
.db $48
.db $39
.db $48
.db $9D
.db $39
.db $32
.db $9D
.db $BF
.db $38
.db $39
.db $42
.db $9D
.db $39
.db $CF
.db $9D
.db $DF
.db $E4
.db $52
.db $F4
.db $62
.db $52
.db $39
.db $62
.db $9D
.db $03
.db $49
.db $03
.db $49
.db $48
.db $03
.db $48
.db $03
.db $B5
.db $04
.db $03
.db $BF
.db $04
.db $D5
.db $42
.db $03
.db $03
.db $CF
.db $03
.db $DF
.db $52
.db $03
.db $62
.db $03
.db $C5
.db $04
.db $B9
.db $42
.db $04
.db $EF
.db $42
.db $BA
.db $48
.db $03
.db $49
.db $03
.db $67
.db $67
.db $72
.db $72
.db $57
.db $03
.db $57
.db $03
.db $42
.db $42
.db $42
.db $42
.db $40
.db $07
.db $50
.db $17
.db $0E
.db $0F
.db $1E
.db $1F
.db $0E
.db $0F
.db $0E
.db $0F
.db $2E
.db $2E
.db $2E
.db $2E
.db $2E
.db $2E
.db $3E
.db $3E
.db $3E
.db $3E
.db $B8
.db $B8
.db $43
.db $53
.db $53
.db $43
.db $63
.db $53
.db $73
.db $43
.db $43
.db $53
.db $73
.db $43
.db $E4
.db $52
.db $F4
.db $62
.db $52
.db $52
.db $62
.db $62
.db $C9
.db $52
.db $D9
.db $62
.db $E4
.db $CA
.db $F4
.db $DA
.db $B9
.db $42
.db $B9
.db $42
.db $42
.db $BA
.db $42
.db $BA
.db $CF
.db $E4
.db $DF
.db $F4
.db $42
.db $42
.db $BF
.db $42
.db $C2
.db $C2
.db $C2
.db $C2
.db $C2
.db $C2
.db $D2
.db $D2
.db $07
.db $61
.db $17
.db $71
.db $66
.db $56
.db $76
.db $46
.db $45
.db $66
.db $55
.db $76
.db $60
.db $06
.db $70
.db $16
.db $66
.db $56
.db $66
.db $46
.db $FF
.db $A3
.db $A4
.db $A3
.db $A2
.db $FF
.db $A2
.db $A4
.db $DB
.db $EC
.db $B9
.db $42
.db $EB
.db $DC
.db $42
.db $BA
.db $94
.db $9E
.db $FF
.db $A3
.db $FF
.db $FF
.db $FF
.db $FF
.db $06
.db $41
.db $16
.db $51
.db $49
.db $39
.db $49
.db $9D
.db $48
.db $39
.db $49
.db $9D
.db $84
.db $84
.db $82
.db $82
.db $FF
.db $FF
.db $A4
.db $A4
.db $94
.db $94
.db $FF
.db $FF
.db $A2
.db $FF
.db $A2
.db $FF
.db $FF
.db $A3
.db $FF
.db $A3
.db $44
.db $44
.db $54
.db $54
.db $54
.db $54
.db $64
.db $64
.db $84
.db $84
.db $84
.db $84
.db $00
.db $00
.db $00
.db $00
.db $92
.db $94
.db $A2
.db $FF
.db $94
.db $93
.db $FF
.db $A3
.db $0C
.db $0D
.db $1C
.db $1D
.db $2C
.db $2D
.db $3C
.db $3D
.db $8A
.db $8B
.db $1C
.db $1D
.db $45
.db $66
.db $55
.db $66
.db $C3
.db $C4
.db $D3
.db $D4
.db $40
.db $41
.db $50
.db $51
.db $60
.db $61
.db $70
.db $71
.db $06
.db $07
.db $16
.db $17
.db $07
.db $06
.db $17
.db $16
.db $C5
.db $04
.db $FF
.db $FF
.db $04
.db $EF
.db $FF
.db $FF
.db $B5
.db $04
.db $03
.db $FF
.db $04
.db $D5
.db $FF
.db $03
.db $03
.db $56
.db $03
.db $46
.db $45
.db $03
.db $55
.db $03
.db $03
.db $FF
.db $03
.db $FF
.db $FF
.db $03
.db $FF
.db $03
.db $04
.db $04
.db $FF
.db $FF
.db $45
.db $03
.db $56
.db $03
.db $04
.db $04
.db $BF
.db $42
.db $00
.db $00
.db $00
.db $00
.db $EB
.db $EC
.db $42
.db $42
.db $0A
.db $0B
.db $1A
.db $1B
.db $C9
.db $22
.db $D9
.db $62
.db $25
.db $CA
.db $62
.db $DA
.db $02
.db $04
.db $B9
.db $12
.db $04
.db $04
.db $13
.db $14
.db $04
.db $05
.db $15
.db $BA
.db $B6
.db $B7
.db $33
.db $34
.db $46
.db $56
.db $56
.db $46
.db $FE
.db $FE
.db $FE
.db $FF
.db $73
.db $63
.db $63
.db $73
.db $18
.db $19
.db $28
.db $29
.db $08
.db $09
.db $28
.db $29
.db $95
.db $96
.db $A5
.db $A6
.db $4A
.db $4B
.db $5A
.db $5B
.db $68
.db $68
.db $68
.db $68
.db $6A
.db $6B
.db $7A
.db $7B
.db $44
.db $44
.db $54
.db $54
.db $54
.db $54
.db $64
.db $64
.db $00
.db $01
.db $10
.db $11
.db $20
.db $21
.db $30
.db $31
.db $BD
.db $BE
.db $CD
.db $CE
.db $DD
.db $DE
.db $ED
.db $EE
.db $C0
.db $C1
.db $D0
.db $D1
.db $E0
.db $E1
.db $F0
.db $F1
.db $2A
.db $2B
.db $3A
.db $3B
.db $E2
.db $E3
.db $F2
.db $F3
.db $6A
.db $6B
.db $6A
.db $6B
.db $26
.db $27
.db $36
.db $37
.db $23
.db $24
.db $33
.db $34
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $01
.db $01
.db $01
.db $02
.db $00
.db $00
.db $00
.db $00
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $00
.db $02
.db $03
.db $03
.db $03
.db $03
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $03
.db $03
.db $03
.db $03
.db $02
.db $01
.db $02
.db $02
.db $02
.db $02
.db $02
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $02
.db $02
.db $02
.db $03
.db $01
.db $01
.db $01
.db $01
.db $01
.db $01
.db $01
.db $01
.db $01
.db $00
.db $00
.db $03
.db $03
.db $01
.db $01
.db $03
.db $03
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $03
.db $02
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $00
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $02
.db $03
.db $03
.db $01
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $03
.db $03
.db $03
.db $03
.db $02
.db $02
.db $01
.db $03
.db $03
.db $01
.db $03
.db $02
.db $02
.db $03
.db $03
.db $02
.db $01
.db $01
.db $03
.db $03
.db $02
.db $02
.db $02
.db $02
.db $02
.db $03
.db $03
.db $02
.db $00
.db $02
.db $02
.db $03
.db $03
.db $03
.db $03
.db $02
.db $01
.db $01
.db $01
.db $01
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $00
.db $03
.db $00
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $02
.db $02
.db $02
.db $00
.db $00
.db $00
.db $03
.db $03
.db $03
.db $00
.db $00
.db $01
.db $01
.db $02
.db $02
.db $00
.db $02
.db $03
.db $03
.db $03
.db $00
.db $00
L0D8500:
    LDA $7479
    BEQ L0D853B
    CMP #1
    BNE L0D8533
    LDA $747A
    STA $7434
    LDA $738F
    STA $78E0
    LDA $7390
    STA $78E1
    LDA $7434
    CMP #43
    BNE L0D8533
    LDA $78E0
    BPL L0D8533
    AND #127
    STA $78E0
    LDA #16
    STA $7920
    BNE L0D857C
L0D8533:
    LDA #48
    STA $7920
    JMP L0D857C.w

L0D853B:
    LDA $7434
    STA $7876
    SEC
    SBC #49
    TAX
    LDA L0DB98C.w,X
    STA $7434
    LDA #7
    STA $4A
    LDA #12
    JSR L0FCA94.w
    LDA #0
    STA $6E76
    LDA $743F
    BNE L0D857C
    LDA $743E
    CMP #1
    BNE L0D857C
    LDA #1
    STA $7434
    LDA #10
    STA $78E0
    LDA #5
    STA $78E1
    LDA $6E08
    ORA #1
    STA $6E08
L0D857C:
    LDA #13
    STA $05B7
    LDA #0
    STA $05EF
    STA $78A1
    STA $78EC
    STA $78A0
    STA $DF
    STA $7980
    STA $7479
    INC $2A
    INC $2A
    LDA #2
    STA $8A
    JSR L0FF608.w
    RTS

L0D85A3:
    LDA #2
    STA $4A
    LDA #12
    JMP L0FCA94.w

L0D85AC:
    LDA #1
    STA $4A
    LDA #12
    JMP L0FCA94.w

L0D85B5:
    LDA $05EF
    JSR L0FC34C.w
.db $C1
.db $85
.db $32
.db $9A
.db $8C
.db $92
    JSR L0FC288.w
    LDA #3
    STA $3D
    JSR L0D929D.w
    JSR L0D85EF.w
    JSR L0D8C0C.w
    JSR L0D8B29.w
    LDX #0
    STX $7874
    STX $7918
    JSR L0D8B8A.w
    STA $7875
    JSR L0FC34C.w
.db $3D
.db $C7
.db $5B
.db $87
.db $BD
.db $86
.db $A7
.db $87
.db $0F
.db $87
L0D85EF:
    LDA $8E
    BNE L0D85F4
    RTS

L0D85F4:
    LDA $8D
    AND #8
    BEQ L0D8638
    LDX $69
    DEX
    STX $0300
    LDX $D0
    LDY $8E
    DEX
    DEY
    BNE L0D860A
    DEC $69
L0D860A:
    STX $D0
    STY $8E
    LDA $D0
    CMP #240
    BCC L0D8618
.db $29
.db $EF
.db $85
.db $D0
L0D8618:
    CPY #12
    BEQ L0D8627
    CPY #8
    BEQ L0D862E
    CPY #4
    BEQ L0D8631
    JMP L0D86BC.w

L0D8627:
    LDA #1
    STA $19
    JMP L0FD1B3.w

L0D862E:
    JMP L0FD1D9.w

L0D8631:
    LDA #0
    STA $19
    JMP L0FD1B3.w

L0D8638:
    LDA $8D
    AND #4
    BEQ L0D867D
    LDA $69
    CLC
    ADC #15
    STA $0300
    LDX $D0
    LDY $8E
    INX
    DEY
    STX $D0
    STY $8E
    BNE L0D865E
    INC $69
    LDA $D0
    CMP #240
    BCC L0D865E
.db $A9
.db $00
.db $85
.db $D0
L0D865E:
    CPY #12
    BEQ L0D866C
    CPY #8
    BEQ L0D8673
    CPY #4
    BEQ L0D8676
    BNE L0D86BC
L0D866C:
    LDA #0
    STA $19
    JMP L0FD1B3.w

L0D8673:
    JMP L0FD203.w

L0D8676:
    LDA #1
    STA $19
    JMP L0FD1B3.w

L0D867D:
    LDA $8D
    AND #2
    BEQ L0D869E
    LDX $D1
    LDY $8E
    DEX
    DEY
    BNE L0D868D
    DEC $6A
L0D868D:
    CPX #254
    BCC L0D8697
    LDA $D3
    AND #254
    STA $D3
L0D8697:
    STX $D1
    STY $8E
    JMP L0D86BC.w

L0D869E:
    LDA $8D
    AND #1
    BEQ L0D86BC
    LDX $D1
    LDY $8E
    INX
    DEY
    BNE L0D86AE
    INC $6A
L0D86AE:
    STY $8E
    STX $D1
    CPX #0
    BNE L0D86BC
    LDA $D3
    ORA #1
    STA $D3
L0D86BC:
    RTS

L0D86BD:
    LDA $7875
    JSR L0FC3A0.w
    STA $7920
    LDA $7900
    SEC
    SBC $6A
    CMP #9
    BCC L0D86EE
    LDA $6A
    CLC
    ADC #15
    CMP $7441
    BCS L0D86EE
    JSR L0D87F9.w
    BCS L0D870E
    LDX $7875
    DEX
    LDA L0D8BB5.w,X
    STA $8D
    JSR L0FD0BB.w
    JMP L0D86FD.w

L0D86EE:
    LDA $7900
    SEC
    SBC $6A
    CMP #15
    BCS L0D870E
    JSR L0D87F9.w
    BCS L0D870E
L0D86FD:
    LDA #16
    STA $7874
    LDA $7875
    ORA $7920
    STA $7920
    JSR L0D880E.w
L0D870E:
    RTS

L0D870F:
    LDA $7875
    JSR L0FC3A0.w
    STA $7920
    LDA $7900
    SEC
    SBC $6A
    CMP #7
    BCS L0D873A
    LDA $6A
    BEQ L0D873A
    JSR L0D87F9.w
    BCS L0D875A
    LDX $7875
    DEX
    LDA L0D8BB5.w,X
    STA $8D
    JSR L0FD0BB.w
    JMP L0D8749.w

L0D873A:
    LDA $7900
    SEC
    SBC $6A
    CMP #1
    BCC L0D875A
    JSR L0D87F9.w
    BCS L0D875A
L0D8749:
    LDA #16
    STA $7874
    LDA $7875
    ORA $7920
    STA $7920
    JSR L0D880E.w
L0D875A:
    RTS

L0D875B:
    LDA $7875
    JSR L0FC3A0.w
    STA $7920
    LDA $78F8
    SEC
    SBC $69
    CMP #5
    BCS L0D8786
    LDA $69
    BEQ L0D8786
    JSR L0D87F9.w
    BCS L0D87A6
    LDX $7875
    DEX
    LDA L0D8BB5.w,X
    STA $8D
    JSR L0FD0BB.w
    JMP L0D8795.w

L0D8786:
    LDA $78F8
    SEC
    SBC $69
    CMP #1
    BCC L0D87A6
    JSR L0D87F9.w
    BCS L0D87A6
L0D8795:
    LDA #16
    STA $7874
    LDA $7875
    ORA $7920
    STA $7920
    JSR L0D880E.w
L0D87A6:
    RTS

L0D87A7:
    LDA $7875
    JSR L0FC3A0.w
    STA $7920
    LDA $78F8
    SEC
    SBC $69
    CMP #9
    BCC L0D87D8
    LDA $69
    CLC
    ADC #14
    CMP $7440
    BCS L0D87D8
    JSR L0D87F9.w
    BCS L0D87F8
    LDX $7875
    DEX
    LDA L0D8BB5.w,X
    STA $8D
    JSR L0FD0BB.w
    JMP L0D87E7.w

L0D87D8:
    LDA $78F8
    SEC
    SBC $69
    CMP #14
    BCS L0D87F8
    JSR L0D87F9.w
    BCS L0D87F8
L0D87E7:
    LDA #16
    STA $7874
    LDA $7875
    ORA $7920
    STA $7920
    JSR L0D880E.w
L0D87F8:
    RTS

L0D87F9:
    LDA $7875
    JSR L0D8BB9.w
    JSR L0D8827.w
    BCS L0D880D
    LDA $7875
    JSR L0D8BB9.w
    JSR L0D8D76.w
L0D880D:
    RTS

L0D880E:
    LDA $7875
    JSR L0D8BB9.w
    LDA $78F8
    CLC
    ADC $00
    STA $7908
    LDA $7900
    CLC
    ADC $01
    STA $7910
    RTS

L0D8827:
    LDA $00
    CLC
    ADC $78F8
    STA $0A
    JSR L0FCEBF.w
    LDA $01
    CLC
    ADC $7900
    STA $0B
    TAY
    LDA ($70),Y
    STA $78D6
    CMP #232
    BCS L0D8876
    CMP #96
    BCC L0D884F
    CMP #102
    BCS L0D88B6
    JMP L0D88BB.w

L0D884F:
    LDY #1
L0D8851:
    LDA $78F0,Y
    BEQ L0D886E
    LDA $0A
    CMP $78F8,Y
    BEQ L0D8862
    CMP $7908,Y
    BNE L0D886E
L0D8862:
    LDA $0B
    CMP $7900,Y
    BEQ L0D88AA
    CMP $7910,Y
    BEQ L0D88AA
L0D886E:
    INY
    CPY #8
    BNE L0D8851
    JMP L0D88B9.w

L0D8876:
    LDA $78D6
    CMP #242
    BEQ L0D8889
    CMP #244
    BEQ L0D8889
    CMP #246
    BEQ L0D8889
    CMP #248
    BNE L0D888B
L0D8889:
    DEC $0A
L0D888B:
    LDA $78D6
    SEC
    SBC #232
    TAX
    LDA L0D8B11.w,X
    AND #15
    JSR L0FC34C.w
.db $34
.db $89
.db $47
.db $89
.db $9E
.db $89
.db $A1
.db $89
.db $BB
.db $8A
.db $DA
.db $8A
.db $CA
.db $8A
.db $37
.db $89
L0D88AA:
    STY $78DB
    LDA #1
    STA $05EF
    LDA #48
    STA $8A
L0D88B6:
    SEC
    BCS L0D88BA
L0D88B9:
    CLC
L0D88BA:
    RTS

L0D88BB:
    LDA $0A
    CLC
    ADC $00
    STA $0A
    LDA $0B
    CLC
    ADC $01
    STA $0B
    LDY #1
L0D88CB:
    LDA $78F0,Y
    BEQ L0D88E8
    LDA $0A
    CMP $78F8,Y
    BEQ L0D88DC
    CMP $7908,Y
    BNE L0D88E8
L0D88DC:
.db $A5
.db $0B
.db $D9
.db $00
.db $79
.db $F0
.db $C7
.db $D9
.db $10
.db $79
.db $F0
.db $C2
L0D88E8:
    INY
    CPY #8
    BNE L0D88CB
    JMP L0D88B6.w

L0D88F0:
    LDX $7434
    DEX
    TXA
    ASL
    TAX
    LDA L0DBD70.w,X
    STA $04
    LDA L0DBD71.w,X
    STA $05
    LDA #0
    STA $78E7
L0D8906:
    LDY #0
    LDA ($04),Y
    CMP #239
    BEQ L0D8932
    CMP $0A
    BNE L0D8919
    INY
    LDA ($04),Y
    CMP $0B
    BEQ L0D8924
L0D8919:
    LDY #4
    JSR L0FC38E.w
    INC $78E7
    JMP L0D8906.w

L0D8924:
    INY
    LDA ($04),Y
    STA $16
    INY
    LDA ($04),Y
    STA $78D1
    CLC
    BCC L0D8933
L0D8932:
.db $38
L0D8933:
    RTS

L0D8934:
    JMP L0D88B9.w

L0D8937:
    LDA $05B8
    BEQ L0D8947
    JMP L0D88B6.w

.db $AD
.db $B8
.db $05
.db $D0
.db $03
.db $4C
.db $B6
.db $88
L0D8947:
    LDY #0
    STY $78D9
    LDA $0B
    STA $78D3
    LDA $0A
    STA $78D4
    LDX #0
L0D8958:
    LDA L0D898B.w,X
    CMP #239
    BEQ L0D8968
    CMP $7434
    BEQ L0D896C
    INX
    INX
    BNE L0D8958
L0D8968:
    LDA #2
    BNE L0D896F
L0D896C:
    LDA L0D898C.w,X
L0D896F:
    ASL
    TAX
    LDA L0D8D2D.w,X
    STA $78D7
    LDA L0D8D2E.w,X
    STA $78D8
    JSR L0D8CCB.w
    LDA #13
    STA $78A0
    JSR L0D85AC.w
    JMP L0D88B9.w

L0D898B:
.db $0F
L0D898C:
.db $05
.db $25
.db $08
.db $1F
.db $09
.db $6E
.db $09
.db $01
.db $0A
.db $06
.db $0A
.db $09
.db $0A
.db $0A
.db $0A
.db $15
.db $0A
.db $EF
L0D899E:
    JMP L0D88B6.w

L0D89A1:
    JSR L0D88F0.w
    BCS L0D899E
    JSR L0FC288.w
    LDA #3
    STA $3D
    JSR L0D8C0C.w
    LDY #0
    STY $78D9
    LDA $0B
    STA $78D3
    LDA $0A
    STA $78D4
    LDX #0
    LDA L0D8D2D.w,X
    STA $78D7
    LDA L0D8D2E.w,X
    STA $78D8
    JSR L0D8CCB.w
    LDA $78D1
    ASL
    TAX
    LDA L0FDCAD.w,X
    STA $02
    LDA (L0FDCAD.w + 1),X
    STA $03
    LDY #0
L0D89E1:
    LDA ($02),Y
    STA $7EA5,Y
    INY
    CMP #239
    BNE L0D89E1
    LDA #9
    STA $78A0
    JSR L0D85AC.w
    JSR L0DB1FD.w
    LDA #160
    STA $7DA9
    LDA #0
    STA $7DA6
    JSR L0DAD67.w
    LDA #1
    STA $78D5
L0D8A08:
    LDA $78D5
    JSR L0DA17E.w
    LDY #11
    LDA ($04),Y
    BEQ L0D8A7C
    LDA $78D5
    LDX $05B8
    CMP $6CF6,X
    BEQ L0D8A24
    INC $78D5
    BNE L0D8A08
L0D8A24:
    LDA #160
    STA $7DA9
    LDA #1
    STA $7DA6
    JSR L0DAD67.w
    LDA $78E7
    ASL
    ASL
    STA $0549
    LDX $7434
    DEX
    TXA
    ASL
    TAX
    LDA L0DBD70.w,X
    CLC
    ADC $0549
    STA $04
    LDA L0DBD71.w,X
    ADC #0
    STA $05
    LDY #0
    LDA ($04),Y
    STA $78D4
    INY
    LDA ($04),Y
    STA $78D3
    LDA $78D4
    JSR L0FCEBF.w
    LDY $78D3
    LDA #235
    STA ($70),Y
    LDA $78D4
    STA $04
    LDA $78D3
    STA $05
    LDA #235
    JSR L0FD611.w
    JMP L0D8AB5.w

L0D8A7C:
    LDA $78D1
    STA ($04),Y
    LDX $7434
    DEX
    LDY $78E7
    LDA L0FD9B1.w,Y
    ORA $6E00,X
    STA $6E00,X
    CPX #47
    BEQ L0D8A97
    BNE L0D8AAD
L0D8A97:
.db $AD
.db $E7
.db $78
.db $C9
.db $01
.db $F0
.db $04
.db $C9
.db $02
.db $D0
.db $0B
.db $BD
.db $00
.db $6E
.db $09
.db $06
.db $9D
.db $00
.db $6E
.db $20
.db $59
.db $8C
L0D8AAD:
    LDA #30
    STA $7DA6
    JSR L0DAD67.w
L0D8AB5:
    JSR L0DADA0.w
    JMP L0D88B6.w

L0D8ABB:
    JSR L0D88F0.w
    BCS L0D8AC7
    INC $05EF
    LDA #53
    STA $8A
L0D8AC7:
    JMP L0D88B6.w

L0D8ACA:
    LDA #47
    STA $8A
    JSR L0DB1FD.w
    INC $05EF
    LDA $78D6
    JMP L0D88B6.w

L0D8ADA:
    JSR L0D88F0.w
    BCS L0D8B0B
    JSR L0FC288.w
    LDA #3
    STA $3D
    JSR L0D8C0C.w
    JSR L0DB1FD.w
    LDA #48
    STA $7DA9
    LDA #1
    STA $05D8
    LDA $78D1
    CMP #76
    BCC L0D8B05
    LDX #161
    STX $7DA9
    SEC
    SBC #76
L0D8B05:
    STA $7DA6
    JSR L0DAD67.w
L0D8B0B:
    JSR L0DADA0.w
    JMP L0D88B6.w

L0D8B11:
.db $70
.db $20
.db $60
.db $03
.db $02
.db $50
.db $50
.db $80
.db $40
.db $01
.db $01
.db $07
.db $07
.db $01
.db $01
.db $01
.db $01
.db $06
.db $02
.db $10
.db $05
.db $04
.db $02
.db $00
L0D8B29:
    LDA $7920
    AND #15
    BEQ L0D8B89
    INC $7918
    DEC $7874
    BNE L0D8B87
    LDA $7920
    AND #1
    BNE L0D8B52
    LDA $7920
    AND #2
    BNE L0D8B4C
    DEC $7900
    JMP L0D8B62.w

L0D8B4C:
    INC $7900
    JMP L0D8B62.w

L0D8B52:
    LDA $7920
    AND #2
    BNE L0D8B5F
    DEC $78F8
    JMP L0D8B62.w

L0D8B5F:
    INC $78F8
L0D8B62:
    LDA #0
    STA $7918
    LDA $7920
    AND #240
    STA $7920
    JSR L0D8EA5.w
    LDA $2A
    CMP #18
    BEQ L0D8B87
    LDA $05EF
    CMP #2
    BNE L0D8B89
    LDA $7920
    AND #240
    STA $7920
L0D8B87:
    PLA
    PLA
L0D8B89:
    RTS

L0D8B8A:
    LDA $1A
    AND #128
    BNE L0D8B96
    LDA $1A
    AND #32
    BEQ L0D8BA2
L0D8B96:
    JSR L0FF572.w
    INC $05EF
    LDA #4
    STA $8A
    BNE L0D8BAE
L0D8BA2:
    LDX #3
L0D8BA4:
    LDA $1C
    AND L0D8BB5.w,X
    BNE L0D8BB2
    DEX
    BPL L0D8BA4
L0D8BAE:
    LDA #0
    BEQ L0D8BB4
L0D8BB2:
    INX
    TXA
L0D8BB4:
    RTS

L0D8BB5:
.db $08
.db $01
.db $04
.db $02
L0D8BB9:
    ASL
    TAX
    LDA L0D8BC7.w,X
    STA $00
    INX
    LDA L0D8BC7.w,X
    STA $01
    RTS

L0D8BC7:
.db $00
.db $00
.db $FF
.db $00
.db $00
.db $01
.db $01
.db $00
.db $00
.db $FF
L0D8BD1:
    LDA $7440
    SEC
    SBC #14
    STA $0A
    LDA $7441
    SEC
    SBC #15
    STA $0B
    LDA $78F8
    SEC
    SBC #7
    BCC L0D8BF2
    CMP $0A
    BCC L0D8BF4
    LDA $0A
    JMP L0D8BF4.w

L0D8BF2:
    LDA #0
L0D8BF4:
    STA $69
    LDA $7900
    SEC
    SBC #8
    BCC L0D8C07
    CMP $0B
    BCC L0D8C09
    LDA $0B
    JMP L0D8C09.w

L0D8C07:
    LDA #0
L0D8C09:
    STA $6A
    RTS

L0D8C0C:
    LDX #0
    STX $78CF
L0D8C11:
    LDA $78F0,X
    BEQ L0D8C4E
    STA $48
    LDA $78F8,X
    STA $45
    LDA $7900,X
    STA $44
    LDA $7920,X
    STA $49
    LDA $7918,X
    STA $47
    LDA #250
    STA $43
    LDA #0
    STA $46
    LDA $7930,X
    AND #64
    BEQ L0D8C46
.db $BD
.db $20
.db $79
.db $29
.db $0F
.db $D0
.db $04
.db $A9
.db $00
.db $F0
.db $02
L0D8C46:
    LDA #0
    STA $7C34
    JSR L0FCB44.w
L0D8C4E:
    INC $78CF
    LDX $78CF
    CPX #8
    BNE L0D8C11
    RTS

L0D8C59:
    LDA #13
    STA $05B7
    LDA #0
    STA $78D5
    LDX $7434
    DEX
    CPX #50
    BCS L0D8C83
    LDA $6E00,X
    STA $78D2
L0D8C71:
    LSR $78D2
    BCC L0D8C79
    JSR L0D8C86.w
L0D8C79:
    INC $78D5
    LDA $78D5
    CMP #8
    BNE L0D8C71
L0D8C83:
    JMP L0D8D2C.w

L0D8C86:
    LDA $7434
    CMP #51
    BCC L0D8C90
.db $4C
.db $2C
.db $8D
L0D8C90:
    TAX
    DEX
    TXA
    ASL
    TAX
    LDA L0DBD70.w,X
    STA $04
    LDA L0DBD71.w,X
    STA $05
    LDA $78D5
    ASL
    ASL
    TAY
    JSR L0FC38E.w
    LDY #0
    LDA ($04),Y
    STA $78D4
    INY
    LDA ($04),Y
    STA $78D3
    INY
    LDA ($04),Y
    ASL
    TAX
    LDA L0D8D2D.w,X
    STA $78D7
    LDA L0D8D2E.w,X
    STA $78D8
    LDY #0
    STY $78D9
L0D8CCB:
    LDA #4
    STA $054B
L0D8CD0:
    LDA $78D4
    JSR L0FCEBF.w
    LDA $78D7
    STA $0A
    LDA $78D8
    STA $0B
    LDY $78D9
    LDA ($0A),Y
    CMP #239
    BEQ L0D8D2C
    INY
    STY $78D9
    LDY $78D3
    STA ($70),Y
    STA $78D6
    LDA $78D4
    STA $04
    LDA $78D3
    STA $05
    LDA $78D6
    JSR L0FD611.w
    LDA $78D4
    STA $04
    LDA $78D3
    STA $05
    LDA $78D6
    JSR L0FD67F.w
    INC $78D4
    DEC $054B
    BNE L0D8CD0
    LDA $78D4
    SEC
    SBC #4
    STA $78D4
    INC $78D3
    JMP L0D8CCB.w

L0D8D2C:
    RTS

L0D8D2D:
.db $52
L0D8D2E:
.db $8D
.db $56
.db $8D
.db $43
.db $8D
.db $5A
.db $8D
.db $58
.db $8D
.db $46
.db $8D
.db $67
.db $8D
.db $69
.db $8D
.db $49
.db $8D
.db $4C
.db $8D
.db $4F
.db $8D
.db $1C
.db $1E
.db $EF
.db $2A
.db $2C
.db $EF
.db $38
.db $38
.db $EF
.db $2A
.db $E8
.db $EF
.db $0A
.db $0C
.db $EF
.db $EC
.db $EF
.db $EB
.db $EF
.db $E7
.db $EF
.db $CF
.db $EF
.db $B9
.db $8A
.db $A6
.db $5F
.db $E0
.db $81
.db $A5
.db $5F
.db $BA
.db $8B
.db $A5
.db $5F
.db $EF
.db $5F
.db $EF
.db $BC
.db $BC
.db $BC
.db $BC
.db $C4
.db $C4
.db $C4
.db $C4
.db $C7
.db $C0
.db $09
.db $09
.db $EF
L0D8D76:
    LDY #0
    LDA $78F8
    CLC
    ADC $00
    CMP #1
    BCC L0D8D9A
    INY
    CMP $7440
    BCS L0D8DA7
    INY
    LDA $7900
    CLC
    ADC $01
    BEQ L0D8DB4
    INY
    CMP $7441
    BCS L0D8DC1
    JMP L0D8E37.w

L0D8D9A:
    LDA $7900
    STA $78E1
    LDA #255
    STA $78E0
    BNE L0D8DCC
L0D8DA7:
    LDA $7900
    STA $78E1
    LDA #2
    STA $78E0
    BNE L0D8DCC
L0D8DB4:
    LDA $78F8
    STA $78E0
    LDA #255
    STA $78E1
    BNE L0D8DCC
L0D8DC1:
    LDA $78F8
    STA $78E0
    LDA #1
    STA $78E1
L0D8DCC:
    STY $18
    LDA $7434
    STA $0A
    LDA #3
    STA $4A
    LDA #10
    JSR L0FCA94.w
    LDA $0A
    BEQ L0D8DF3
    CMP #50
    BCC L0D8DF6
    SEC
    SBC #50
    STA $7434
    JSR L0D8E38.w
    LDA #0
    STA $8A
    INC $2A
L0D8DF3:
    SEC
    BCS L0D8E37
L0D8DF6:
    CMP #43
    BNE L0D8E01
    LDX $744C
    CPX #4
    BCC L0D8DF3
L0D8E01:
    STA $78EB
    STA $00
    LDA #165
    STA $0A
    LDA #126
    STA $0B
    LDA #14
    STA $4A
    LDA #11
    JSR L0FCA94.w
    JSR L0DB1FD.w
    LDA #32
    STA $7DA6
    JSR L0DAD67.w
    LDA #112
    STA $77
    LDA #80
    STA $76
    LDA #1
    JSR L0DAE26.w
    INC $05EF
    LDA #63
    STA $8A
    SEC
L0D8E37:
    RTS

L0D8E38:
    LDX #0
L0D8E3A:
    LDA L0DBA01.w,X
    CMP #239
    BEQ L0D8EA4
    CMP $7434
    BEQ L0D8E4B
    INX
    INX
    INX
    BNE L0D8E3A
L0D8E4B:
    LDA L0DBA03.w,X
    AND $6E76
    BNE L0D8EA4
    LDA L0DBA03.w,X
    ORA $6E76
    STA $6E76
    LDA L0DBA02.w,X
    AND #127
    STA $78EB
    LDA #1
    STA $6D10
    LDA $05B8
    STA $6D11
L0D8E6F:
    LDA $7434
    STA $747A
    LDX #32
    STX $16
L0D8E79:
    JSR L0FC70D.w
    INC $36
    JSR L0D9701.w
    LDA $36
    AND #15
    BNE L0D8E8F
    LDA #22
    STA $78A0
    JSR L0D85AC.w
L0D8E8F:
    DEC $16
    BNE L0D8E79
    LDA #2
    STA $78EC
    LDA $78E0
    STA $738F
    LDA $78E1
    STA $7390
L0D8EA4:
    RTS

L0D8EA5:
    LDA $78F8
    JSR L0FCEBF.w
    LDA $7900
    TAY
    LDA ($70),Y
    CMP #232
    BCC L0D8ED4
    SEC
    SBC #232
    TAX
    LDA L0D8B11.w,X
    JSR L0FC39A.w
    JSR L0FC34C.w
.db $3D
.db $C7
.db $7F
.db $8F
.db $64
.db $8F
.db $D4
.db $8E
.db $74
.db $8F
.db $D4
.db $8F
.db $49
.db $8F
.db $87
.db $8F
.db $5E
.db $8F
L0D8ED4:
    LDX $7434
    DEX
    TXA
    ASL
    TAX
    LDA L0DB4FA.w,X
    STA $04
    LDA L0DB4FB.w,X
    STA $05
    LDX $7434
    DEX
    CPX #50
    BCS L0D8F0A
    LDA $6E32,X
    STA $78D1
    LDA #0
    STA $78D5
L0D8EF8:
    LSR $78D1
    BCC L0D8F00
    JSR L0D8F0B.w
L0D8F00:
    INC $78D5
    LDA $78D5
    CMP #8
    BNE L0D8EF8
L0D8F0A:
    RTS

L0D8F0B:
    LDA $78D5
    ASL
    CLC
    ADC $78D5
    CLC
    ADC $04
    STA $02
    LDA $05
    ADC #0
    STA $03
    LDY #0
    LDA $78F8
    CMP ($02),Y
    BNE L0D8F48
    INY
    LDA $7900
    CMP ($02),Y
    BNE L0D8F48
    INY
    LDA ($02),Y
    ASL
    TAX
    LDA L0DB61B.w,X
    STA $78E5
    LDA (L0DB61B.w + 1),X
    STA $78E6
    JSR L0D99A1.w
    LDA #2
    STA $05EF
L0D8F48:
    RTS

L0D8F49:
    JSR L0FC70D.w
    JSR L0FC70D.w
    JMP L0FC70D.w

L0D8F52:
    JSR L0D9714.w
    JSR L0FC70D.w
    JSR L0FC70D.w
    JMP L0D972B.w

L0D8F5E:
    JSR L0D8F52.w
    JMP L0D8F69.w

L0D8F64:
    LDA #1
    STA $7980
L0D8F69:
    LDA #14
    STA $78A0
    JSR L0D85AC.w
    JMP L0D8F87.w

L0D8F74:
    LDA #10
    STA $78A0
    JSR L0D85AC.w
    JMP L0D8F87.w

L0D8F7F:
    LDA #11
    STA $78A0
    JSR L0D85AC.w
L0D8F87:
    LDA $7434
    TAX
    DEX
    TXA
    ASL
    TAX
    LDA L0DBA50.w,X
    STA $04
    LDA L0DBA51.w,X
    STA $05
L0D8F99:
    LDY #0
    LDA ($04),Y
    CMP #239
    BEQ L0D8FD1
    CMP $78F8
    BNE L0D8FAE
    INY
    LDA ($04),Y
    CMP $7900
    BEQ L0D8FB6
L0D8FAE:
    LDY #5
    JSR L0FC38E.w
    JMP L0D8F99.w

L0D8FB6:
    INY
    LDA ($04),Y
    STA $7434
    INY
    LDA ($04),Y
    STA $78E0
    INY
    LDA ($04),Y
    STA $78E1
    JSR L0D8E38.w
    LDA #0
    STA $8A
    INC $2A
L0D8FD1:
    JMP L0D8ED4.w

.db $A9
.db $F9
.db $85
.db $04
.db $A9
.db $8F
.db $85
.db $05
.db $A0
.db $00
.db $B1
.db $04
.db $C9
.db $EF
.db $F0
.db $12
.db $CD
.db $34
.db $74
.db $F0
.db $04
.db $C8
.db $C8
.db $D0
.db $F1
.db $C8
.db $B1
.db $04
.db $8D
.db $EB
.db $78
.db $4C
.db $4A
.db $B2
.db $4C
.db $D4
.db $8E
.db $06
.db $09
.db $09
.db $0F
.db $EF
L0D8FFE:
    LDA $8A
    JSR L0FC34C.w
.db $09
.db $90
.db $79
.db $91
.db $18
.db $90
    LDA #4
    STA $05B5
    INC $8A
    LDA #1
    JSR L0FC9BD.w
    JMP L0D9110.w

L0D9018:
    LDA $78EC
    BNE L0D9020
    JMP L0D90A2.w

L0D9020:
    LDA #255
    STA $78A0
    LDA $78EC
    CMP #1
    BEQ L0D9057
    CMP #2
    BEQ L0D9042
    CMP #4
    BEQ L0D9097
    DEC $2A
    LDA #1
    STA $05EF
    LDA #64
    STA $8A
    JMP L0FC72D.w

L0D9042:
    JSR L0DB262.w
    LDA $78EB
    STA $0F
    LDA #4
    STA $2A
    LDA #14
    STA $4A
    LDA #8
    JMP L0FCA94.w

L0D9057:
    JSR L0DB262.w
    LDA $78EB
    STA $6D0B
    LDX $05B8
    LDA $7434
    STA $6CC0,X
    LDA $7434
    SEC
    SBC #1
    ASL
    TAY
    LDA L0FEEF4.w,Y
    STA $6C9C,X
    LDA (L0FEEF4.w + 1),Y
    STA $6CAE,X
    LDA $6D0B
    STA $05E8
    STA $05BB
    LDX $05B8
    STX $05E7
    LDA #1
    STA $05E9
    LDA $7434
    STA $6D16,X
L0D9097:
    LDA #3
    STA $2A
    LDA #0
    STA $8A
    JMP L0D910F.w

L0D90A2:
    JSR L0FFB2F.w
    LDA #0
    STA $4A
    LDA #12
    JSR L0FCA94.w
    LDA #1
    STA $4A
    LDA #10
    JSR L0FCA94.w
    JSR L0D8BD1.w
    LDA #1
    STA $9E
    JSR L0FC71F.w
    JSR L0D8C59.w
    LDA #1
    JSR L0FC9BD.w
    JSR L0D9110.w
    JSR L0FD394.w
    JSR L0DADA0.w
    JSR L0FC288.w
    LDA #3
    STA $3D
    JSR L0D8C0C.w
    LDA #0
    STA $05F4
    DEC $2A
    JSR L0D85A3.w
    LDA $7980
    BEQ L0D90FE
    LDX #32
L0D90ED:
    JSR L0FC70D.w
    DEX
    BNE L0D90ED
    LDA #0
    STA $7980
    JSR L0D8EA5.w
    JMP L0D910F.w

L0D90FE:
    JSR L0D8ED4.w
    LDA $7DA4
    BEQ L0D910F
    LDA #1
    STA $05EF
    LDA #69
    STA $8A
L0D910F:
    RTS

L0D9110:
    LDX #0
L0D9112:
    LDA L0D9158.w,X
    CMP #239
    BEQ L0D9134
    CMP $7434
    BEQ L0D9121
    INX
    BNE L0D9112
L0D9121:
    LDA $6E12
    AND #1
    BEQ L0D9134
    LDA #16
    STA $7D82
    LDA #0
    STA $7D83
    BEQ L0D9154
L0D9134:
    LDX #0
L0D9136:
    LDA L0D915D.w,X
    CMP #239
    BEQ L0D9157
    CMP $7434
    BEQ L0D9145
    INX
    BNE L0D9136
L0D9145:
    LDA #43
    STA $7D85
    LDA #11
    STA $7D86
    LDA #12
    STA $7D87
L0D9154:
    JSR L0FC70D.w
L0D9157:
    RTS

L0D9158:
.db $0F
.db $13
.db $2D
.db $22
.db $EF
L0D915D:
.db $19
.db $1B
.db $1C
.db $23
.db $2A
.db $3A
.db $40
.db $41
.db $49
.db $4C
.db $4D
.db $64
.db $70
.db $71
.db $72
.db $73
.db $74
.db $76
.db $77
.db $78
.db $79
.db $7A
.db $7B
.db $7C
.db $7D
.db $7E
.db $7F
.db $EF
L0D9179:
    LDA $05B5
    BEQ L0D9187
    LDA #2
    STA $4A
    LDA #4
    JMP L0FCA94.w

L0D9187:
    INC $8A
    RTS

L0D918A:
    LDA #1
    JSR L0FC9BD.w
    JMP L0D9110.w

L0D9192:
    LDA $058D
    BEQ L0D91CD
    CMP #4
    BNE L0D91A4
    LDY $058F
    BEQ L0D9157
    DEY
    JMP L0D91D3.w

L0D91A4:
    LDA $77
    STA $03
    LDA $0590
    ASL
    ASL
    ASL
    CLC
    ADC $77
    STA $01
    LDA $76
    SEC
    SBC #7
    STA $02
    LDA $0591
    ASL
    ASL
    ASL
    CLC
    ADC $76
    SEC
    SBC #7
    STA $00
    LDY #0
    JSR L0D91FE.w
L0D91CD:
    LDY $058F
    BEQ L0D9224
    DEY
L0D91D3:
    LDX L0D9225.w,Y
    LDA $7C35,X
    ASL
    ASL
    ASL
    CLC
    ADC $7C39,X
    SEC
    SBC #7
    STA $00
    LDA $7C39,X
    SEC
    SBC #7
    STA $02
    LDA $7C36,X
    ASL
    ASL
    ASL
    CLC
    ADC $7C3A,X
    STA $01
    LDA $7C3A,X
    STA $03
L0D91FE:
    LDX #0
L0D9200:
    LDA $0200,X
    CMP $00
    BCS L0D921B
    CMP $02
    BCC L0D921B
    LDA $0203,X
    CMP $01
    BCS L0D921B
    CMP $03
    BCC L0D921B
    LDA #244
    STA $0200,X
L0D921B:
    INX
    INX
    INX
    INX
    BNE L0D9200
    DEY
    BPL L0D91D3
L0D9224:
    RTS

L0D9225:
.db $00
.db $06
.db $0C
.db $12
.db $18
.db $30
.db $92
.db $54
.db $92
.db $68
.db $92
.db $3F
.db $00
.db $20
.db $0F
.db $20
.db $21
.db $11
.db $0F
.db $3A
.db $1A
.db $0A
.db $0F
.db $28
.db $17
.db $07
.db $0F
.db $20
.db $10
.db $00
.db $0F
.db $13
.db $36
.db $0F
.db $0F
.db $11
.db $36
.db $0F
.db $0F
.db $15
.db $36
.db $0F
.db $0F
.db $17
.db $36
.db $0F
.db $00
.db $3F
.db $10
.db $10
.db $0F
.db $20
.db $21
.db $11
.db $0F
.db $0A
.db $0B
.db $14
.db $0F
.db $11
.db $36
.db $11
.db $0F
.db $16
.db $36
.db $16
.db $00
.db $3F
.db $00
.db $20
.db $0F
.db $20
.db $10
.db $1A
.db $0F
.db $2B
.db $0A
.db $1A
.db $0F
.db $28
.db $17
.db $1A
.db $0F
.db $31
.db $1A
.db $22
.db $0F
.db $20
.db $36
.db $0F
.db $0F
.db $11
.db $36
.db $0F
.db $0F
.db $15
.db $36
.db $0F
.db $0F
.db $25
.db $36
.db $0F
.db $00
L0D928C:
    JSR L0FC288.w
    LDA #3
    STA $3D
    JSR L0D8C0C.w
    JSR L0D85EF.w
    JSR L0D93E8.w
    RTS

L0D929D:
    LDX #1
    STX $78CF
L0D92A2:
    LDA $78F0,X
    BEQ L0D92D6
    LDA $7930,X
    BPL L0D92D6
    LDA $7920,X
    AND #15
    BEQ L0D92C2
    LDY $7918,X
    INY
    CPY #16
    BCS L0D92C2
    TYA
    STA $7918,X
    JMP L0D92D6.w

L0D92C2:
    LDA #0
    STA $7918,X
    LDA $7908,X
    STA $78F8,X
    LDA $7910,X
    STA $7900,X
    JSR L0D92E1.w
L0D92D6:
    INC $78CF
    LDX $78CF
    CPX #8
    BNE L0D92A2
    RTS

L0D92E1:
    JSR L0D9349.w
    LDA $78D0
    BEQ L0D931F
    JSR L0FC3A0.w
    LDX $78CF
    STA $7920,X
    LDA $78D0
    JSR L0D8BB9.w
    LDX $78CF
    LDA $00
    CLC
    ADC $78F8,X
    STA $04
    LDA $01
    CLC
    ADC $7900,X
    STA $05
    JSR L0D9372.w
    BCS L0D931A
    JSR L0D9363.w
    BCS L0D931A
    JSR L0D93BC.w
    BCC L0D931F
L0D931A:
    LDA #0
    STA $78D0
L0D931F:
    LDX $78CF
    LDA $7920,X
    AND #240
    ORA $78D0
    STA $7920,X
    LDA $78D0
    JSR L0D8BB9.w
    LDX $78CF
    LDA $78F8,X
    CLC
    ADC $00
    STA $7908,X
    LDA $7900,X
    CLC
    ADC $01
    STA $7910,X
    RTS

L0D9349:
    LDA $36
    AND #63
    BNE L0D935D
    LDA #4
    JSR L0FC068.w
    CLC
    ADC #1
    STA $78D0
    JMP L0D9362.w

L0D935D:
    LDA #0
    STA $78D0
L0D9362:
    RTS

L0D9363:
    LDA $04
    JSR L0FCEBF.w
    LDY $05
    LDA ($70),Y
    CMP #96
    BCC L0D9371
    SEC
L0D9371:
    RTS

L0D9372:
    LDA $04
    CMP $7908
    BNE L0D9380
    LDA $05
    CMP $7910
    BEQ L0D93BA
L0D9380:
    LDA $04
    CMP $78F8
    BNE L0D938E
    LDA $05
    CMP $7900
    BEQ L0D93BA
L0D938E:
    LDX #1
L0D9390:
    CPX $78CF
    BEQ L0D93B2
    LDA $78F0,X
    BEQ L0D93B2
    LDA $04
    CMP $78F8,X
    BEQ L0D93A6
    CMP $7908,X
    BNE L0D93B2
L0D93A6:
    LDA $05
    CMP $7900,X
    BEQ L0D93BA
    CMP $7910,X
    BEQ L0D93BA
L0D93B2:
    INX
    CPX #16
    BNE L0D9390
    CLC
    BCC L0D93BB
L0D93BA:
    SEC
L0D93BB:
    RTS

L0D93BC:
    LDX $78CF
    LDA $78F0,X
    BEQ L0D93E7
    LDA $7938,X
    CMP $04
    BCS L0D93E6
    INY
    LDA $7948,X
    CMP $05
    BCS L0D93E6
    INY
    LDA $7940,X
    CMP $04
    BCC L0D93E6
    INY
    LDA $7950,X
    CMP $05
    BCC L0D93E6
    CLC
    BCC L0D93E7
L0D93E6:
    SEC
L0D93E7:
    RTS

L0D93E8:
    LDA $78E8
    BEQ L0D940A
    LDX $78E3
    LDA $7920,X
    AND #15
    BEQ L0D9404
    STA $78DA
    LDA $7918,X
    CLC
    ADC $78EA
    STA $7918,X
L0D9404:
    DEC $78E8
    JMP L0D94BE.w

L0D940A:
    LDX $78E3
    LDA $7920,X
    AND #15
    BEQ L0D943B
    AND #2
    BEQ L0D942B
    LDA $7920,X
    AND #1
    BNE L0D9425
    INC $7900,X
    JMP L0D943B.w

L0D9425:
    INC $78F8,X
    JMP L0D943B.w

L0D942B:
    LDA $78DA
    AND #1
    BNE L0D9438
    DEC $7900,X
    JMP L0D943B.w

L0D9438:
    DEC $78F8,X
L0D943B:
    LDA #0
    STA $7918,X
    LDA $78F8,X
    STA $7908,X
    LDA $7900,X
    STA $7910,X
    LDA $78E9
    STA $78E8
    LDA $78E7
    BEQ L0D9473
    DEC $78E7
    LDA $78A1
    BEQ L0D9470
.db $BD
.db $20
.db $79
.db $29
.db $0F
.db $F0
.db $0A
.db $AA
.db $CA
.db $BD
.db $B5
.db $8B
.db $85
.db $8D
.db $20
.db $BB
.db $D0
L0D9470:
    JMP L0D94BE.w

L0D9473:
    LDA $7920,X
    AND #240
    STA $7920,X
    LDA $78E5
    STA $04
    LDA $78E6
    STA $05
    LDY $78E4
    LDA ($04),Y
    STA $78D1
    AND #15
    STA $78E7
    INC $78E4
    LDA $78D1
    JSR L0FC39A.w
    JSR L0FC34C.w
.db $BF
.db $94
.db $F8
.db $94
.db $0A
.db $95
.db $50
.db $95
.db $F7
.db $95
.db $DE
.db $95
.db $EE
.db $97
.db $09
.db $98
.db $43
.db $99
.db $79
.db $98
.db $E0
.db $98
.db $EE
.db $97
.db $8B
.db $98
.db $16
.db $95
.db $EE
.db $98
.db $3B
.db $99
L0D94BE:
    RTS

L0D94BF:
    LDX $78E3
    LDA $7920,X
    AND #240
    STA $7920,X
    LDA $78D1
    BEQ L0D94DA
    LDA #7
    STA $78E8
    STA $78E9
    JMP L0D94F7.w

L0D94DA:
    LDA $78E5
    STA $04
    LDA $78E6
    STA $05
    LDY $78E4
    JSR L0FC38E.w
    LDA $04
    STA $78E5
    LDA $05
    STA $78E6
    JSR L0D99A1.w
L0D94F7:
    RTS

L0D94F8:
    LDX $78E3
    LDA $78E7
    JSR L0FC3A0.w
    STA $7920,X
    LDA #0
    STA $78E7
    RTS

L0D950A:
    LDA #7
    STA $78E8
    STA $78E9
    LDA #2
    BNE L0D9520
    LDA #15
    STA $78E8
    STA $78E9
    LDA #1
L0D9520:
    STA $78EA
    LDX $78E3
    LDA $7920,X
    JSR L0FC39A.w
    STA $00
    LDA $7920,X
    AND #240
    ORA $00
    STA $7920,X
    DEC $78E7
    LDA $78A1
    BEQ L0D954F
.db $BD
.db $20
.db $79
.db $29
.db $0F
.db $AA
.db $CA
.db $BD
.db $B5
.db $8B
.db $85
.db $8D
.db $20
.db $BB
.db $D0
L0D954F:
    RTS

L0D9550:
    LDA #0
    STA $7DA5
    LDA #48
    STA $7DA9
    LDA #1
    STA $7DAC
    LDY $78E4
    LDA ($04),Y
    CMP #76
    BCC L0D9572
    PHA
    LDA #161
    STA $7DA9
    PLA
    SEC
    SBC #76
L0D9572:
    STA $7DA6
    INC $78E4
    LDA #1
    JSR L0FC9BD.w
    LDA #1
    STA $05D8
    LDY $78E7
    LDA $78E5
    STA $04
    LDA $78E6
    STA $05
L0D958F:
    JSR L0FC70D.w
    JSR L0FC336.w
    INC $36
    JSR L0FC288.w
    LDA $DF
    BEQ L0D95AF
    BPL L0D95B9
    LDA #1
    JSR L0FC9BD.w
    JSR L0D9110.w
    JSR L0DADB0.w
    LDA #0
    STA $DF
L0D95AF:
    LDA #3
    STA $3D
    JSR L0D8C0C.w
    JSR L0D9192.w
L0D95B9:
    LDA #0
    STA $3D
    LDA #0
    STA $4A
    LDA #10
    JSR L0FCA94.w
    LDA $7DAC
    BNE L0D958F
    JSR L0DADA0.w
    LDA #1
    JSR L0FC9BD.w
    JSR L0D9110.w
    LDA #128
    STA $28
    JSR L0FC70D.w
    RTS

L0D95DE:
    LDY $78E4
    LDA ($04),Y
    CMP #255
    BNE L0D95ED
.db $20
.db $A3
.db $85
.db $4C
.db $F3
.db $95
L0D95ED:
    STA $78A0
    JSR L0D85AC.w
    INC $78E4
    RTS

L0D95F7:
    LDA $78E7
    JSR L0FC34C.w
.db $EE
.db $96
.db $7B
.db $97
.db $D8
.db $97
.db $13
.db $96
.db $38
.db $97
.db $33
.db $96
.db $51
.db $97
.db $CC
.db $96
.db $98
.db $96
.db $B4
.db $96
.db $5D
.db $96
    LDX #160
    LDA $D1
    STA $78E2
L0D961A:
    JSR L0FC70D.w
    INC $36
    LDA $36
    AND #1
    ASL
    CLC
    ADC $78E2
    STA $D1
    DEX
    BNE L0D961A
    LDA $78E2
    STA $D1
    RTS

L0D9633:
    LDA #3
    STA $6D91
    LDA #22
    STA $78EB
    LDA #1
    STA $6D10
    LDA $05B8
    STA $6D11
L0D9648:
    LDA $78F8
    STA $78E0
    LDA $7900
    STA $78E1
    INC $2A
    LDA #0
    STA $8A
    JMP L0D8E6F.w

L0D965D:
    LDX $78E3
    LDA $78F0,X
    STA $78DF
    LDA #16
    STA $78D5
L0D966B:
    JSR L0FC288.w
    LDA #3
    STA $3D
    JSR L0D8C0C.w
    JSR L0FC70D.w
    INC $36
    LDA $36
    AND #3
    BNE L0D966B
    LDX $78E3
    LDA $78F0,X
    BEQ L0D968C
    LDA #0
    BEQ L0D968F
L0D968C:
    LDA $78DF
L0D968F:
    STA $78F0,X
    DEC $78D5
    BNE L0D966B
    RTS

L0D9698:
    LDA #2
    STA $6D10
    LDA #1
    STA $6D11
    LDA #0
    STA $6D12
    LDA #22
    STA $78EB
    LDA #4
    STA $6D91
    JMP L0D9648.w

L0D96B4:
    LDA #23
    STA $74E2
    LDA $6CD2
    STA $6B
    LDA $6CD3
    STA $6C
    LDA #23
    STA $4A
    LDA #8
    JMP L0FCA94.w

L0D96CC:
    LDA #13
    STA $78A0
    JSR L0D85AC.w
    LDA #5
    STA $78D4
    LDA #0
    STA $78D3
    STA $78D9
    LDA #105
    STA $78D7
    LDA #141
    STA $78D8
    JMP L0D8CCB.w

L0D96EE:
    LDA #8
    STA $A7
L0D96F2:
    JSR L0FC70D.w
    INC $36
    JSR L0D9701.w
    DEC $A7
    BNE L0D96F2
    JMP L0D972B.w

L0D9701:
    LDA $36
    AND #1
    BNE L0D9713
    LDA $36
    AND #2
    BNE L0D9710
    JMP L0D9714.w

L0D9710:
    JSR L0D972B.w
L0D9713:
    RTS

L0D9714:
    LDA #1
    JSR L0FC9BD.w
    JSR L0D9110.w
    LDX #32
    LDA #16
L0D9720:
    STA $7D7F,X
    DEX
    BNE L0D9720
    LDA #128
    STA $28
    RTS

L0D972B:
    LDA #1
    JSR L0FC9BD.w
    JSR L0D9110.w
    LDA #128
    STA $28
    RTS

L0D9738:
    INC $2A
    LDA #0
    STA $05EF
    STA $8A
    LDA #4
    STA $78EC
    LDA #2
    STA $6D91
    LDA #0
    STA $05B8
    RTS

L0D9751:
    LDA #0
    STA $78D5
L0D9756:
    CLC
    ADC #1
    JSR L0DB4DF.w
    LDY #3
    LDA ($04),Y
    BNE L0D9764
.db $A9
.db $00
L0D9764:
    LDX $78D5
    STA $73CF,X
    INC $78D5
    LDA $78D5
    CMP $6CF7
    BNE L0D9756
    LDA #1
    STA $7DA4
    RTS

L0D977B:
    LDA #55
    STA $78D4
    LDA #128
    STA $78D3
    LDA #1
    STA $797F
    LDA $D1
    STA $78E2
    LDA #1
    STA $059C
    LDA #26
    STA $78D7
    LDA #154
    STA $78D8
    LDA #0
    STA $78DA
    LDA #1
    JSR L0FC9BD.w
    LDA #31
    JSR L0FCA48.w
L0D97AD:
    JSR L0FC288.w
    LDA #3
    STA $3D
    JSR L0D8C0C.w
    LDA #5
    STA $4A
    LDA #12
    JSR L0FCA94.w
    LDA $059C
    BEQ L0D97D0
    JSR L0FC336.w
    INC $36
    JSR L0FC70D.w
    JMP L0D97AD.w

L0D97D0:
    LDA $78E2
    STA $D1
    JMP L0D8C59.w

L0D97D8:
    LDA #1
    STA $744B
    LDA #2
    STA $7484
    JSR L0FF8AB.w
    LDA #1
    STA $7486
    JSR L0FF894.w
    RTS

L0D97EE:
    LDX $78E3
    LDA $78E7
    BNE L0D97FD
    LDA #0
    STA $78F0,X
    BEQ L0D9808
L0D97FD:
.db $AC
.db $E4
.db $78
.db $B1
.db $04
.db $9D
.db $F0
.db $78
.db $EE
.db $E4
.db $78
L0D9808:
    RTS

L0D9809:
    LDY $78E4
    LDA ($04),Y
    STA $789F
    INC $78E4
    LDA #0
    STA $0450
    LDX $789F
    DEX
    TXA
    JSR L0DA0C4.w
    JSR L0DB21F.w
    LDA #0
    STA $74B6
    LDA $789F
    STA $74B5
    LDA $05B8
    STA $74DD
    JSR L0FCA0B.w
    LDX #1
    LDA $67AE,X
    SEC
    SBC #1
    ASL
    TAY
    LDA L0FDB73.w,Y
    STA $02
    LDA (L0FDB73.w+1),Y
    STA $03
    LDY #0
L0D984E:
    LDA ($02),Y
    STA $7EB5,Y
    CMP #239
    BEQ L0D985A
    INY
    BNE L0D984E
L0D985A:
    LDA #8
    STA $78A0
    JSR L0D85AC.w
    JSR L0DB1FD.w
    LDA #29
    STA $7DA6
    JSR L0DAD67.w
    JSR L0FFA0D.w
    LDA #2
    STA $7DA6
    JSR L0DAD67.w
    RTS

L0D9879:
    DEC $05EF
    LDA #50
    STA $8A
    LDA $78E7
    STA $78EF
    LDA #9
    JMP L0DAE26.w

L0D988B:
    LDY $78E4
    LDA ($04),Y
    STA $78D4
    INY
    LDA ($04),Y
    STA $78D3
    INY
    STY $78E4
L0D989D:
    LDA $78D4
    CMP $69
    BEQ L0D98B6
    BCC L0D98AC
.db $A9
.db $04
.db $85
.db $8D
.db $D0
.db $04
L0D98AC:
    LDA #8
    STA $8D
    JSR L0FD0BB.w
    JMP L0D98CC.w

L0D98B6:
    LDA $78D3
    CMP $6A
    BEQ L0D98DF
.db $90
.db $06
.db $A9
.db $01
.db $85
.db $8D
.db $D0
.db $04
.db $A9
.db $02
.db $85
.db $8D
.db $20
.db $BB
.db $D0
L0D98CC:
    JSR L0FC288.w
    JSR L0D8C0C.w
    JSR L0D85EF.w
    JSR L0FC70D.w
    LDA $8E
    BNE L0D98CC
    JMP L0D989D.w

L0D98DF:
    RTS

L0D98E0:
    LDY $78E4
    LDA ($04),Y
    STA $0570
    INC $78E4
    JMP L0FFACC.w

L0D98EE:
    LDA $78E7
    STA $78EF
    INC $744C
    LDA $78EF
    SEC
    SBC #1
    ASL
    TAX
    LDA L0DBEF0.w,X
    STA $04
    LDA L0DBEF1.w,X
    STA $05
    LDY #0
    LDA ($04),Y
    STA $7434
    INY
    LDA ($04),Y
    STA $78E0
    INY
    LDA ($04),Y
    STA $78E1
    INC $2A
    LDA #0
    STA $05EF
    STA $78A1
    STA $78A0
    LDA #2
    STA $8A
    LDA #3
    STA $78EC
    LDA #3
    STA $4A
    LDA #12
    JMP L0FCA94.w

L0D993B:
    LDA #33
    STA $8A
    DEC $05EF
    RTS

L0D9943:
    LDX $78E7
    DEX
    TXA
    ASL
    TAX
    LDA L0DB96B.w,X
    STA $02
    LDA (L0DB96B.w + 1),X
    STA $03
    LDX $78E3
    LDY #0
    LDA ($02),Y
    STA $78F8,X
    STA $7908,X
    INY
    LDA ($02),Y
    STA $7900,X
    STA $7910,X
    INY
    LDA ($02),Y
    STA $7938,X
    INY
    LDA ($02),Y
    STA $7940,X
    INY
    LDA ($02),Y
    STA $7948,X
    INY
    LDA ($02),Y
    STA $7950,X
    INY
    LDA ($02),Y
    STA $78F0,X
    INY
    LDA #64
    STA $7920,X
    LDA ($02),Y
    AND #248
    STA $7930,X
    INY
    LDA ($02),Y
    STA $7928,X
    LDA #0
    STA $7918,X
    RTS

L0D99A1:
    LDA $78E5
    STA $04
    LDA $78E6
    STA $05
    LDY #0
    STY $78E4
    STY $78E7
    LDA ($04),Y
    CMP #239
    BEQ L0D99CD
    STA $78E3
    DEC $78E3
    INC $78E4
    LDA #0
    STA $78E8
    STA $78E9
    JMP L0D99D5.w

L0D99CD:
    LDA #0
    STA $05EF
    JSR L0DADA0.w
L0D99D5:
    RTS

L0D99D6:
    LDA $78D7
    STA $08
    LDA $78D8
    STA $09
    LDY #0
    LDA ($08),Y
    STA $0C
    INY
    LDA ($08),Y
    STA $0D
    INY
    STY $18
L0D99EE:
    LDY $18
    LDA ($08),Y
    CMP #255
    BEQ L0D9A09
    PHA
    LDA $0C
    STA $04
    LDA $0D
    STA $05
    PLA
    JSR L0FD611.w
    INC $0D
    INC $18
    BNE L0D99EE
L0D9A09:
    INC $18
    LDA $18
    CLC
    ADC $78D7
    STA $78D7
    BCC L0D9A19
.db $EE
.db $D8
.db $78
L0D9A19:
    RTS

.db $02
.db $07
.db $00
.db $00
.db $00
.db $FF
.db $03
.db $07
.db $00
.db $00
.db $00
.db $FF
.db $01
.db $07
.db $4C
.db $4C
.db $4C
.db $FF
.db $01
.db $07
.db $00
.db $00
.db $00
.db $FF
L0D9A32:
    JSR L0FC288.w
    LDA $DF
    BNE L0D9A43
    LDA #3
    STA $3D
    JSR L0D8C0C.w
    JMP L0D9A56.w

L0D9A43:
    LDA $DF
    BPL L0D9A56
.db $A9
.db $01
.db $20
.db $BD
.db $C9
.db $20
.db $10
.db $91
.db $20
.db $B0
.db $AD
.db $A9
.db $00
.db $85
.db $DF
L0D9A56:
    LDA #0
    STA $78A2
    LDA $8A
    JSR L0FC34C.w
.db $3D
.db $C7
.db $EC
.db $9A
.db $FB
.db $9A
.db $0E
.db $9B
.db $1D
.db $9B
.db $36
.db $9B
.db $F1
.db $AA
.db $AE
.db $9B
.db $F1
.db $AA
.db $D2
.db $9B
.db $0F
.db $9C
.db $57
.db $9D
.db $79
.db $9D
.db $57
.db $9D
.db $A2
.db $9D
.db $2C
.db $A9
.db $F1
.db $AA
.db $20
.db $A2
.db $F3
.db $A1
.db $F1
.db $AA
.db $0E
.db $A2
.db $28
.db $AB
.db $B4
.db $AB
.db $F1
.db $AA
.db $FC
.db $AB
.db $72
.db $A5
.db $27
.db $AC
.db $F1
.db $AA
.db $95
.db $AC
.db $72
.db $A5
.db $14
.db $A5
.db $72
.db $A5
.db $2B
.db $A2
.db $F6
.db $B2
.db $18
.db $B3
.db $F1
.db $AA
.db $72
.db $A5
.db $37
.db $B3
.db $F1
.db $AA
.db $8A
.db $B3
.db $18
.db $B3
.db $AC
.db $B3
.db $F1
.db $AA
.db $B6
.db $B3
.db $F1
.db $AA
.db $72
.db $A5
.db $AE
.db $A6
.db $04
.db $AB
.db $9D
.db $AE
.db $7D
.db $AF
.db $B3
.db $AF
.db $F1
.db $AA
.db $C0
.db $AF
.db $C4
.db $AF
.db $F5
.db $AF
.db $F1
.db $AA
.db $72
.db $A5
.db $4B
.db $B0
.db $F1
.db $AA
.db $84
.db $B0
.db $F1
.db $AA
.db $72
.db $A5
.db $6F
.db $A7
.db $33
.db $B2
.db $73
.db $B2
.db $9B
.db $B2
.db $F1
.db $AA
.db $C6
.db $B2
.db $DE
.db $B2
.db $E5
.db $B3
L0D9AEC:
    LDA #1
    STA $78A2
    LDA #0
    STA $78CC
    LDA #16
    STA $8A
    RTS

L0D9AFB:
    LDA #1
    STA $78A2
    LDA #0
    STA $2C
    STA $78CC
    LDA #44
    STA $8A
    INC $8A
    RTS

.db $A9
.db $01
.db $8D
.db $A2
.db $78
.db $A9
.db $00
.db $8D
.db $CC
.db $78
.db $A9
.db $08
.db $85
.db $8A
.db $60
L0D9B1D:
    LDA #0
    JSR L0DAE26.w
    LDA #0
    STA $78CC
    LDA #1
    JSR L0FC9BD.w
    JSR L0D9110.w
    LDA #0
    STA $2C
    INC $8A
    RTS

L0D9B36:
    JSR L0D9192.w
    LDA #0
    STA $3D
    JSR L0FE684.w
    LDA $05AC
    CMP #1
    BEQ L0D9B60
    CMP #2
    BEQ L0D9B66
    CMP #3
    BEQ L0D9B59
    CMP #4
    BEQ L0D9B6D
    LDA #15
    STA $8A
    BNE L0D9BAD
L0D9B59:
    LDA #8
    STA $8A
    JMP L0D9BA6.w

L0D9B60:
    LDA #44
    STA $8A
    BNE L0D9BA6
L0D9B66:
    LDA #16
    STA $8A
    JMP L0D9BA6.w

L0D9B6D:
.db $AD
.db $A4
.db $7D
.db $F0
.db $0B
.db $A9
.db $03
.db $8D
.db $CC
.db $78
.db $A9
.db $3C
.db $85
.db $8A
.db $D0
.db $29
.db $A9
.db $06
.db $85
.db $8A
.db $A9
.db $01
.db $8D
.db $9C
.db $05
.db $AD
.db $F8
.db $78
.db $8D
.db $E0
.db $78
.db $AD
.db $00
.db $79
.db $8D
.db $E1
.db $78
.db $A9
.db $01
.db $20
.db $BD
.db $C9
.db $20
.db $10
.db $91
.db $A9
.db $00
.db $8D
.db $D8
.db $05
.db $4C
.db $A6
.db $9B
.db $A9
.db $3C
.db $85
.db $8A
L0D9BA6:
    LDX #0
    LDA #0
    STA $7D73,X
L0D9BAD:
    RTS

.db $20
.db $92
.db $91
.db $A9
.db $00
.db $85
.db $3D
.db $A5
.db $8A
.db $8D
.db $CB
.db $78
.db $A9
.db $07
.db $85
.db $4A
.db $A9
.db $07
.db $20
.db $94
.db $CA
.db $AD
.db $CB
.db $78
.db $85
.db $8A
.db $AD
.db $9C
.db $05
.db $D0
.db $04
.db $A9
.db $0F
.db $85
.db $8A
.db $60
L0D9BD2:
    JSR L0FC288.w
    JSR L0FE684.w
    LDA $058F
    BEQ L0D9BE6
    CMP #2
    BEQ L0D9BEB
    LDA #10
    JMP L0DAE26.w

L0D9BE6:
    LDA #2
    JMP L0DAE26.w

L0D9BEB:
    LDA #0
    STA $78CD
    LDA $78DD
    CLC
    ADC $78E2
    STA $78DE
    JSR L0D9E9C.w
    LDA #22
    JSR L0FCA48.w
    JSR L0FCA50.w
    LDA #2
    STA $28
    JSR L0FC70D.w
    INC $8A
    RTS

L0D9C0F:
    JSR L0FC288.w
    LDA #0
    STA $3D
    LDA $1E
    AND #4
    BNE L0D9C8A
    LDA $1E
    AND #8
    BNE L0D9C6B
    LDA $1A
    AND #64
    BNE L0D9C37
    LDA $1A
    AND #2
    BNE L0D9CA7
    LDA $1A
    AND #1
    BNE L0D9CA7
    JMP L0D9D0D.w

L0D9C37:
    LDA $058F
    CMP #2
    BEQ L0D9C41
.db $4C
.db $D6
.db $9C
L0D9C41:
    JSR L0FC288.w
    LDA $78A2
    BEQ L0D9C4D
.db $A9
.db $03
.db $D0
.db $0A
L0D9C4D:
    LDA #1
    JSR L0FC9BD.w
    JSR L0D9110.w
    LDA #128
    STA $28
    JSR L0FC70D.w
    LDA #30
    JSR L0FCA48.w
    JSR L0FCA50.w
    LDA #15
    STA $8A
    JMP L0D9D2C.w

L0D9C6B:
    LDX $78DD
    CPX #1
    BEQ L0D9C7C
.db $20
.db $6C
.db $F5
.db $CA
.db $8E
.db $DD
.db $78
L0D9C79:
    JMP L0D9CD6.w

L0D9C7C:
    LDA $78E2
    BEQ L0D9C79
.db $CE
.db $E2
.db $78
.db $20
.db $64
.db $A9
.db $4C
.db $D6
.db $9C
L0D9C8A:
    LDA $78DD
    CLC
    ADC $78E2
    CMP $78DC
    BEQ L0D9C79
.db $AE
.db $DD
.db $78
.db $E0
.db $0A
.db $F0
.db $27
.db $20
.db $6C
.db $F5
.db $E8
.db $8E
.db $DD
.db $78
.db $4C
.db $D6
.db $9C
L0D9CA7:
    LDA $058F
    CMP #2
    BNE L0D9D0D
    LDA $748F
    BEQ L0D9D0D
.db $AD
.db $CD
.db $78
.db $F0
.db $06
.db $CE
.db $CD
.db $78
.db $4C
.db $E6
.db $9C
.db $EE
.db $CD
.db $78
.db $4C
.db $E6
.db $9C
.db $AD
.db $DD
.db $78
.db $18
.db $6D
.db $E2
.db $78
.db $CD
.db $DC
.db $78
.db $F0
.db $06
.db $EE
.db $E2
.db $78
.db $20
.db $64
.db $A9
L0D9CD6:
    LDA #0
    STA $78CD
    LDA $058F
    CMP #2
    BEQ L0D9CE6
.db $E6
.db $8A
.db $D0
.db $2D
L0D9CE6:
    LDA $78DD
    CLC
    ADC $78E2
    STA $78DE
    JSR L0D9E9C.w
    JMP L0D9D13.w

L0D9CF6:
.db $20
.db $72
.db $F5
.db $AD
.db $8F
.db $05
.db $C9
.db $02
.db $F0
.db $04
.db $E6
.db $8A
.db $D0
.db $28
.db $A9
.db $03
.db $18
.db $65
.db $8A
.db $85
.db $8A
.db $D0
.db $1F
L0D9D0D:
    LDA $1A
    AND #128
    BNE L0D9CF6
L0D9D13:
    JSR L0D9D2D.w
    LDA $058F
    CMP #2
    BNE L0D9D23
    JSR L0D9E0C.w
    JMP L0D9D2C.w

L0D9D23:
.db $A9
.db $02
.db $85
.db $4A
.db $A9
.db $09
.db $20
.db $94
.db $CA
L0D9D2C:
    RTS

L0D9D2D:
    LDY #1
    JSR L0DADC2.w
    LDA $78DD
    TAX
    DEX
    LDY #4
    LDA ($74),Y
    CLC
    ADC L0DA958.w,X
    STA $3A
    INY
    LDA ($74),Y
    CLC
    ADC #8
    STA $3B
    LDA #0
    STA $41
    LDA #8
    STA $0587
    LDA #197
    JMP L0FE80F.w

.db $20
.db $88
.db $C2
.db $20
.db $84
.db $E6
.db $AD
.db $8F
.db $05
.db $C9
.db $01
.db $F0
.db $03
.db $4C
.db $96
.db $E6
.db $A9
.db $16
.db $20
.db $48
.db $CA
.db $20
.db $50
.db $CA
.db $A9
.db $02
.db $85
.db $28
.db $20
.db $0D
.db $C7
.db $E6
.db $8A
.db $60
.db $20
.db $88
.db $C2
.db $20
.db $84
.db $E6
.db $AD
.db $8F
.db $05
.db $C9
.db $02
.db $F0
.db $05
.db $A9
.db $0A
.db $4C
.db $26
.db $AE
.db $A9
.db $00
.db $8D
.db $CD
.db $78
.db $AD
.db $DD
.db $78
.db $18
.db $6D
.db $E2
.db $78
.db $8D
.db $DE
.db $78
.db $20
.db $9C
.db $9E
.db $C6
.db $8A
.db $C6
.db $8A
.db $60
.db $20
.db $88
.db $C2
.db $20
.db $84
.db $E6
.db $AD
.db $8F
.db $05
.db $C9
.db $02
.db $F0
.db $3A
.db $C9
.db $03
.db $F0
.db $4C
.db $AD
.db $DD
.db $78
.db $18
.db $6D
.db $E2
.db $78
.db $AA
.db $CA
.db $BD
.db $77
.db $78
.db $8D
.db $DD
.db $7D
.db $8D
.db $84
.db $74
.db $20
.db $AB
.db $F8
.db $A9
.db $70
.db $8D
.db $D5
.db $7D
.db $A9
.db $30
.db $8D
.db $D7
.db $7D
.db $A9
.db $00
.db $8D
.db $A5
.db $7D
.db $A9
.db $05
.db $85
.db $4A
.db $A9
.db $09
.db $20
.db $94
.db $CA
.db $A9
.db $03
.db $85
.db $4A
.db $A9
.db $09
.db $4C
.db $94
.db $CA
.db $A5
.db $95
.db $8D
.db $DF
.db $78
.db $A5
.db $6A
.db $85
.db $95
.db $A9
.db $84
.db $85
.db $7A
.db $A9
.db $74
.db $85
.db $7B
.db $A9
.db $2F
.db $4C
.db $B8
.db $E6
.db $AD
.db $DF
.db $78
.db $85
.db $95
.db $A5
.db $8A
.db $38
.db $E9
.db $04
.db $85
.db $8A
.db $60
L0D9E0C:
    LDA $78CD
    BNE L0D9E44
    LDA #52
    STA $08
    LDA #136
    STA $09
    LDA $78DD
    CLC
    ADC $78E2
    JMP L0D9E72.w

.db $A9
.db $01
.db $8D
.db $D5
.db $78
.db $20
.db $A0
.db $C3
.db $18
.db $69
.db $34
.db $85
.db $08
.db $A9
.db $74
.db $85
.db $09
.db $AD
.db $D5
.db $78
.db $20
.db $72
.db $9E
.db $EE
.db $D5
.db $78
.db $AD
.db $D5
.db $78
.db $C9
.db $0B
.db $D0
.db $E4
L0D9E44:
.db $60
L0D9E45:
    LDA $74B4
    CMP #3
    BNE L0D9E71
    LDA #1
    STA $78D5
L0D9E51:
    JSR L0FC3A0.w
    CLC
    ADC #52
    STA $08
    LDA #112
    STA $09
    LDA $78D5
    CLC
    ADC $78E2
    JSR L0D9E72.w
    INC $78D5
    LDA $78D5
    CMP #11
    BNE L0D9E51
L0D9E71:
    RTS

L0D9E72:
    TAX
    DEX
    LDA $08
    STA $3A
    LDA $09
    STA $3B
    LDA #0
    STA $41
    STA $3F
    LDA #8
    STA $0587
    LDA $78A3,X
    BEQ L0D9E9B
    BPL L0D9E90
    INC $3F
L0D9E90:
    LDA $78A3,X
    AND #127
    CLC
    ADC #212
    JSR L0FE80F.w
L0D9E9B:
    RTS

L0D9E9C:
    LDY #2
    JSR L0DADC2.w
    LDY #4
    LDA ($74),Y
    CLC
    ADC #8
    STA $00
    STA $78D4
    INY
    LDA ($74),Y
    CLC
    ADC #16
    STA $01
    STA $78D3
    JSR L0FC517.w
    LDA $04
    STA $7E
    LDA $05
    STA $7F
    LDA #0
    STA $0450
    LDA $78DE
    JSR L0DA0BA.w
    LDX $0450
    LDA #173
    STA $0451,X
    INX
    STX $0450
    LDA $78DE
    JSR L0DA1A0.w
    LDX #0
    STX $16
    LDA #10
    JSR L0DADDC.w
    LDX $16
    LDA #237
    STA $0451,X
    INX
    LDA $0450
    LDA #239
    STA $0451,X
    LDY #22
    LDA #255
L0D9EFD:
    STA $0311,Y
    DEY
    BPL L0D9EFD
    JSR L0DAE6C.w
    JSR L0DAE02.w
    LDX $7E
    LDY $7F
    LDA #75
    STA $0310
    JSR L0FC842.w
    JSR L0FC70D.w
    LDA $78D4
    CLC
    ADC #16
    STA $78D4
    LDA $78D3
    CLC
    ADC #24
    STA $78D3
    LDA $78CD
    BEQ L0D9F35
.db $20
.db $61
.db $A8
.db $4C
.db $3B
.db $9F
L0D9F35:
    LDA $78DE
    JSR L0DA820.w
    LDX $78DE
    DEX
    LDA $7877,X
    JSR L0D9FF3.w
    LDA $78D4
    CLC
    ADC #16
    STA $00
    LDA $78D3
    CLC
    ADC #40
    STA $01
    JSR L0FC517.w
    LDA $04
    STA $7E
    LDA $05
    STA $7F
    LDY #8
    LDA #255
L0D9F64:
    STA $0311,Y
    DEY
    BPL L0D9F64
    LDX #0
    STX $78D5
L0D9F6F:
    LDA #3
    STA $78D8
    LDA #19
    STA $78D7
L0D9F79:
    LDY $78D5
    LDX L0D9FE9.w,Y
    LDA $7484,X
    CMP #255
    BNE L0D9F88
.db $A9
.db $00
L0D9F88:
    STA $00
    LDA #2
    STA $01
    LDA $78D7
    STA $08
    LDA $78D8
    STA $09
    JSR L0FC7EA.w
    LDA $78D7
    CLC
    ADC #4
    STA $78D7
    BCC L0D9FA9
.db $EE
.db $D8
.db $78
L0D9FA9:
    INC $78D5
    LDA $78D5
    AND #1
    BNE L0D9F79
    LDX $7E
    LDY $7F
    LDA #130
    STA $0310
    JSR L0FC842.w
    JSR L0FC70D.w
    LDA $7E
    STA $00
    LDA $7F
    STA $01
    JSR L0FC81C.w
    JSR L0FC81C.w
    JSR L0FC81C.w
    JSR L0FC81C.w
    LDA $00
    STA $7E
    LDA $01
    STA $7F
    LDA $78D5
    CMP #10
    BEQ L0D9FE8
    JMP L0D9F6F.w

L0D9FE8:
    RTS

L0D9FE9:
.db $02
.db $03
.db $05
.db $06
.db $07
.db $08
.db $09
.db $0C
.db $0D
.db $04
L0D9FF3:
    STA $7484
    JSR L0FF8AB.w
    LDX $7485
    DEX
    LDA L0FEDD3.w,X
.db $8D
L0DA001:
    STA ($74),Y
    LDX $7484
    DEX
    LDA L0FEE00.w,X
    LDX $7485
    CPX #10
    BNE L0DA014
.db $18
.db $69
.db $0F
L0DA014:
    STA $7490
    LDA $78CD
    BNE L0D9FE8
    LDA #132
    STA $7A
    LDA #116
    STA $7B
    LDA $748F
    JSR L0FF460.w
    BVS L0DA02E
    BCS L0D9FE8
L0DA02E:
    LDA $748F
    CMP #23
    BCC L0DA094
.db $C9
.db $30
.db $90
.db $AF
.db $C9
.db $36
.db $90
.db $21
.db $C9
.db $37
.db $F0
.db $15
.db $C9
.db $38
.db $D0
.db $74
.db $AD
.db $91
.db $74
.db $18
.db $69
.db $05
.db $8D
.db $91
.db $74
.db $A9
.db $28
.db $8D
.db $8B
.db $74
.db $4C
.db $B9
.db $A0
.db $A9
.db $28
.db $8D
.db $8C
.db $74
.db $4C
.db $B9
.db $A0
.db $AD
.db $8F
.db $74
.db $C9
.db $33
.db $F0
.db $54
.db $C9
.db $34
.db $F0
.db $50
.db $A2
.db $00
.db $BD
.db $38
.db $F5
.db $CD
.db $8F
.db $74
.db $F0
.db $03
.db $E8
.db $D0
.db $F5
.db $BD
.db $3D
.db $F5
.db $18
.db $6D
.db $8D
.db $74
.db $8D
.db $8D
.db $74
.db $AD
.db $8F
.db $74
.db $C9
.db $35
.db $D0
.db $0A
.db $AD
.db $90
.db $74
.db $18
.db $7D
.db $3D
.db $F5
.db $8D
.db $90
.db $74
.db $4C
.db $B9
.db $A0
L0DA094:
    LDX $748F
    LDA $748B
    SEC
    SBC L0FDA24.w,X
    STA $748B
    LDX $748F
    CPX #15
    BEQ L0DA0B4
    LDA L0FD9B9.w,X
    CLC
    ADC $7489
    STA $7489
    BNE L0DA0B9
L0DA0B4:
.db $A9
.db $0F
.db $8D
.db $89
.db $74
L0DA0B9:
    RTS

L0DA0BA:
    TAX
    DEX
    LDA $7877,X
    BEQ L0DA0E5
    SEC
    SBC #1
L0DA0C4:
    ASL
    TAY
    LDA L0FDEA9.w,Y
    STA $02
    LDA (L0FDEA9.w+1),Y
    STA $03
    LDY #0
    LDX $0450
L0DA0D5:
    LDA ($02),Y
    CMP #239
    BEQ L0DA0E2
    STA $0451,X
    INX
    INY
    BNE L0DA0D5
L0DA0E2:
    STX $0450
L0DA0E5:
    RTS

L0DA0E6:
    TAX
    DEX
    LDA $7877,X
    BEQ L0DA0FC
    STA $7484
    JSR L0FF8AB.w
    LDA $7487
    STA $7492
    LDA $748F
L0DA0FC:
    PHA
    ASL
    TAY
    LDA L0FDCAD.w,Y
    STA $02
    LDA (L0FDCAD.w + 1),Y
    STA $03
    LDY #0
    LDX $0450
    STX $16
L0DA110:
    LDA ($02),Y
    CMP #239
    BEQ L0DA11D
    STA $0451,X
    INX
    INY
    BNE L0DA110
L0DA11D:
    STX $0450
    LDA #7
    JSR L0DADDC.w
    STX $0450
    LDX $78D9
    LDA #0
    STA $78A3,X
    LDA #132
    STA $7A
    LDA #116
    STA $7B
    PLA
    BEQ L0DA160
    JSR L0FF460.w
    BCC L0DA14A
    BVS L0DA14A
    LDX $78D9
    LDA #128
    STA $78A3,X
L0DA14A:
    JSR L0DA161.w
    LDX $78D9
    LDA $05EC
    CMP #6
    BCC L0DA15A
    SEC
    SBC #2
L0DA15A:
    ORA $78A3,X
    STA $78A3,X
L0DA160:
    RTS

L0DA161:
    LDY #0
L0DA163:
    LDA $748F
    CMP L0FF50C.w,Y
    BCC L0DA173
    INY
    STY $05EC
    CPY #6
    BCC L0DA163
L0DA173:
    LDA $748F
    CMP #54
    BCC L0DA17D
.db $EE
.db $EC
.db $05
L0DA17D:
    RTS

L0DA17E:
    STA $00
    DEC $00
    LDA #12
    STA $01
    JSR L0FC6C9.w
    LDX $05B8
    TXA
    ASL
    TAX
    LDA $6CD2,X
    CLC
    ADC $00
    STA $04
    INX
    LDA $6CD2,X
    ADC $01
    STA $05
    RTS

L0DA1A0:
    TAX
    DEX
    LDA $7877,X
    STA $7484
    JSR L0FF8AB.w
    LDA $7484
    CMP #1
    BEQ L0DA1C2
.db $C9
.db $02
.db $D0
.db $16
.db $AD
.db $4B
.db $74
.db $F0
.db $11
.db $A9
.db $18
.db $8D
.db $85
.db $74
.db $D0
.db $0A
L0DA1C2:
    LDA $744A
    BEQ L0DA1CC
.db $A9
.db $17
.db $8D
.db $85
.db $74
L0DA1CC:
    LDY $7485
    DEY
    TYA
    ASL
    TAY
    LDA L0FDB73.w,Y
    STA $02
    LDA (L0FDB73.w+1),Y
    STA $03
    LDY #0
    LDX $0450
L0DA1E2:
    LDA ($02),Y
    CMP #239
    BEQ L0DA1EF
    STA $0451,X
    INX
    INY
    BNE L0DA1E2
L0DA1EF:
    STX $0450
    RTS

L0DA1F3:
    JSR L0D9192.w
    LDA #0
    STA $3D
    JSR L0FE684.w
    LDA $05AC
    BNE L0DA208
    LDA #15
    STA $8A
    BNE L0DA20D
L0DA208:
    STA $78D1
    INC $8A
L0DA20D:
    RTS

L0DA20E:
    LDX $78D1
    DEX
    LDA L0DA21D.w,X
    STA $8A
    LDA #0
    STA $78CC
    RTS

L0DA21D:
.db $1F
.db $1D
.db $15
L0DA220:
    INC $8A
    LDA #0
    STA $2C
    LDA #4
    JMP L0DAE26.w

L0DA22B:
    JSR L0DA5F4.w
    JSR L0D9E45.w
    LDA $1A
    AND #128
    BNE L0DA259
    LDA $1A
    AND #64
    BEQ L0DA26D
    LDA $78DE
    BNE L0DA24B
    JSR L0DADB0.w
    LDA #16
    STA $8A
    BNE L0DA28F
L0DA24B:
.db $A9
.db $00
.db $8D
.db $DE
.db $78
.db $20
.db $88
.db $C2
.db $A9
.db $00
.db $85
.db $3D
.db $F0
.db $14
L0DA259:
.db $20
.db $72
.db $F5
.db $AD
.db $DE
.db $78
.db $F0
.db $06
.db $20
.db $87
.db $A4
.db $4C
.db $6D
.db $A2
.db $AD
.db $DD
.db $78
.db $8D
.db $DE
.db $78
L0DA26D:
    LDA $78DD
    CMP $78DE
    BNE L0DA279
.db $A9
.db $01
.db $D0
.db $02
L0DA279:
    LDA #3
    STA $3F
    LDA $78DD
    JSR L0DA305.w
    LDA #2
    STA $3F
    LDA $78DE
    BEQ L0DA304
.db $20
.db $05
.db $A3
L0DA28F:
    RTS

.db $20
.db $88
.db $C2
.db $A9
.db $00
.db $85
.db $3D
.db $A5
.db $1E
.db $29
.db $04
.db $D0
.db $36
.db $A5
.db $1E
.db $29
.db $08
.db $F0
.db $61
.db $AD
.db $DD
.db $78
.db $C9
.db $01
.db $F0
.db $23
.db $20
.db $6C
.db $F5
.db $AD
.db $DD
.db $78
.db $38
.db $E9
.db $01
.db $8D
.db $49
.db $05
.db $CD
.db $E2
.db $78
.db $D0
.db $12
.db $AD
.db $E2
.db $78
.db $38
.db $E9
.db $0A
.db $8D
.db $E2
.db $78
.db $CE
.db $F0
.db $05
.db $20
.db $79
.db $A3
.db $AD
.db $49
.db $05
.db $8D
.db $DD
.db $78
.db $4C
.db $04
.db $A3
.db $AD
.db $DD
.db $78
.db $CD
.db $DC
.db $78
.db $F0
.db $26
.db $20
.db $6C
.db $F5
.db $AD
.db $DD
.db $78
.db $18
.db $69
.db $01
.db $8D
.db $49
.db $05
.db $38
.db $ED
.db $E2
.db $78
.db $C9
.db $0B
.db $D0
.db $0F
.db $AD
.db $E2
.db $78
.db $18
.db $69
.db $0A
.db $8D
.db $E2
.db $78
.db $EE
.db $F0
.db $05
.db $20
.db $79
.db $A3
.db $AD
.db $49
.db $05
.db $8D
.db $DD
.db $78
L0DA304:
    RTS

L0DA305:
    PHA
    LDY #2
    JSR L0DADC2.w
    PLA
    JSR L0DA501.w
    BCS L0DA33D
    SEC
    SBC $78E2
    TAX
    DEX
    LDY #4
    LDA ($74),Y
    CLC
    ADC L0DA958.w,X
    STA $3A
    INY
    LDA $36
    AND #1
    JSR L0FC3A0.w
    ASL
    CLC
    ADC #128
    STA $3B
    LDA #0
    STA $41
    LDA #8
    STA $0587
    LDA #218
    JSR L0FE80F.w
L0DA33D:
    RTS

L0DA33E:
    PHA
    LDY #2
    JSR L0DADC2.w
    PLA
    JSR L0DA501.w
    BCS L0DA378
    SEC
    SBC $78E2
    TAX
    DEX
    LDY #4
    LDA ($74),Y
    CLC
    ADC L0DA958.w,X
    STA $3A
    INY
    LDA $36
    AND #1
    JSR L0FC3A0.w
    CLC
    ADC ($74),Y
    CLC
    ADC #16
    STA $3B
    LDA #0
    STA $41
    LDA #8
    STA $0587
    LDA #201
    JSR L0FE80F.w
L0DA378:
    RTS

.db $A9
.db $38
.db $8D
.db $D4
.db $78
.db $A9
.db $30
.db $8D
.db $D3
.db $78
.db $A9
.db $01
.db $8D
.db $D5
.db $78
.db $18
.db $6D
.db $E2
.db $78
.db $20
.db $82
.db $A8
.db $AD
.db $D4
.db $78
.db $18
.db $69
.db $10
.db $8D
.db $D4
.db $78
.db $EE
.db $D5
.db $78
.db $AD
.db $D5
.db $78
.db $C9
.db $0B
.db $D0
.db $E6
.db $A9
.db $38
.db $8D
.db $D4
.db $78
.db $A9
.db $70
.db $8D
.db $D3
.db $78
.db $A9
.db $01
.db $8D
.db $D5
.db $78
.db $18
.db $6D
.db $E2
.db $78
.db $20
.db $20
.db $A8
.db $AD
.db $D4
.db $78
.db $18
.db $69
.db $10
.db $8D
.db $D4
.db $78
.db $EE
.db $D5
.db $78
.db $AD
.db $D5
.db $78
.db $C9
.db $0B
.db $D0
.db $E6
.db $A9
.db $18
.db $8D
.db $D4
.db $78
.db $A9
.db $30
.db $8D
.db $D3
.db $78
.db $20
.db $8A
.db $AD
.db $A9
.db $46
.db $20
.db $B8
.db $E6
.db $A6
.db $7E
.db $A4
.db $7F
.db $A9
.db $43
.db $8D
.db $10
.db $03
.db $20
.db $42
.db $C8
.db $A9
.db $02
.db $85
.db $28
.db $20
.db $0D
.db $C7
.db $60
L0DA3F1:
    LDA #24
    STA $78D4
    LDA #104
    STA $78D3
    JSR L0DAD8A.w
    LDA #43
    JSR L0FE6B8.w
    LDX $7E
    LDY $7F
    LDA #75
    STA $0310
    JSR L0FC842.w
    JSR L0FC70D.w
    LDA #24
    STA $78D4
    LDA #64
    STA $78D3
    JSR L0DAD8A.w
    LDA #70
    JSR L0FE6B8.w
    LDX $7E
    LDY $7F
    LDA #67
    STA $0310
    JSR L0FC842.w
    JSR L0FC70D.w
    LDA #56
    STA $78D4
    LDA #104
    STA $78D3
    LDA #1
    STA $78D5
L0DA442:
    CLC
    ADC $78E2
    JSR L0DA8C8.w
    LDA $78D4
    CLC
    ADC #16
    STA $78D4
    INC $78D5
    LDA $78D5
    CMP #11
    BNE L0DA442
    RTS

L0DA45D:
    LDA #56
    STA $78D4
    LDA #64
    STA $78D3
    LDA #1
    STA $78D5
L0DA46C:
    CLC
    ADC $78E2
    JSR L0DA882.w
    LDA $78D4
    CLC
    ADC #16
    STA $78D4
    INC $78D5
    LDA $78D5
    CMP #11
    BNE L0DA46C
    RTS

.db $AE
.db $DE
.db $78
.db $CA
.db $BD
.db $77
.db $78
.db $8D
.db $84
.db $74
.db $20
.db $AB
.db $F8
.db $AD
.db $8F
.db $74
.db $8D
.db $4A
.db $05
.db $AE
.db $DD
.db $78
.db $CA
.db $BD
.db $77
.db $78
.db $8D
.db $84
.db $74
.db $20
.db $AB
.db $F8
.db $AD
.db $8F
.db $74
.db $8D
.db $4B
.db $05
.db $AD
.db $4A
.db $05
.db $8D
.db $8F
.db $74
.db $20
.db $94
.db $F8
.db $AE
.db $DE
.db $78
.db $CA
.db $BD
.db $77
.db $78
.db $8D
.db $84
.db $74
.db $20
.db $AB
.db $F8
.db $AD
.db $4B
.db $05
.db $8D
.db $8F
.db $74
.db $20
.db $94
.db $F8
.db $20
.db $F1
.db $A3
.db $A9
.db $00
.db $8D
.db $DE
.db $78
.db $20
.db $88
.db $C2
.db $A9
.db $00
.db $85
.db $3D
.db $60
.db $48
.db $A0
.db $02
.db $20
.db $C2
.db $AD
.db $68
.db $38
.db $ED
.db $E2
.db $78
.db $AA
.db $CA
.db $A0
.db $04
.db $B1
.db $74
.db $18
.db $7D
.db $58
.db $A9
.db $38
.db $E9
.db $08
.db $8D
.db $D4
.db $78
.db $C8
.db $B1
.db $74
.db $18
.db $69
.db $50
.db $8D
.db $D3
.db $78
.db $60
L0DA501:
    PHA
    SEC
    SBC $78E2
    CMP #1
    BCC L0DA511
    CMP #11
    BCS L0DA511
    CLC
    BCC L0DA512
L0DA511:
.db $38
L0DA512:
    PLA
    RTS

L0DA514:
    JSR L0DA5F4.w
    JSR L0D9E45.w
    LDA $1A
    AND #128
    BNE L0DA530
    LDA $1A
    AND #64
    BEQ L0DA567
    JSR L0DADB0.w
    LDA #16
    STA $8A
    JMP L0DA571.w

L0DA530:
.db $20
.db $72
.db $F5
.db $AD
.db $4D
.db $74
.db $18
.db $6D
.db $4E
.db $74
.db $C9
.db $27
.db $F0
.db $02
.db $B0
.db $31
.db $AE
.db $DD
.db $78
.db $CA
.db $BD
.db $77
.db $78
.db $8D
.db $84
.db $74
.db $20
.db $AB
.db $F8
.db $AD
.db $8F
.db $74
.db $F0
.db $15
.db $85
.db $16
.db $A9
.db $00
.db $8D
.db $8F
.db $74
.db $20
.db $94
.db $F8
.db $AE
.db $B8
.db $05
.db $A5
.db $16
.db $20
.db $89
.db $FA
.db $20
.db $F1
.db $A3
L0DA567:
    LDA #3
    STA $3F
    LDA $78DD
    JSR L0DA305.w
L0DA571:
    RTS

L0DA572:
    JSR L0D9192.w
    JSR L0FE684.w
    LDA $058F
    BEQ L0DA59B
    CMP #1
    BNE L0DA5A0
    JSR L0DACFB.w
    LDA #48
    STA $77
    LDA #48
    STA $76
    LDA $78CC
    BNE L0DA596
    LDA #41
    JMP L0FE6B8.w

L0DA596:
.db $A9
.db $0B
.db $4C
.db $26
.db $AE
L0DA59B:
    LDA #42
    JMP L0FE6B8.w

L0DA5A0:
    LDX #0
    STX $78DE
    STX $78E2
    STX $05F0
    INX
    STX $78DD
    LDA $78DC
    STA $4E
    LDA #0
    STA $4F
    LDA #10
    STA $50
    JSR L0FC6EB.w
    LDX $4E
    LDA $51
    BNE L0DA5C6
.db $CA
L0DA5C6:
    STX $05F1
    JSR L0FC288.w
    LDA #0
    STA $74B4
    LDA $8A
    CMP #44
    BCS L0DA5DC
    LDA #3
    STA $74B4
L0DA5DC:
    JSR L0DA45D.w
    JSR L0DA3F1.w
    LDA #2
    STA $28
    JSR L0FC70D.w
    LDA #22
    JSR L0FCA48.w
    JSR L0FCA50.w
    INC $8A
    RTS

L0DA5F4:
    JSR L0FC288.w
    LDA #0
    STA $3D
    LDA $1E
    AND #4
    BNE L0DA64C
    LDA $1A
    AND #1
    BNE L0DA649
    LDA $1E
    AND #8
    BNE L0DA616
    LDA $1A
    AND #2
    BNE L0DA68C
    JMP L0DA6AD.w

L0DA616:
.db $AD
.db $DD
.db $78
.db $C9
.db $01
.db $F0
.db $26
.db $20
.db $6C
.db $F5
.db $AD
.db $DD
.db $78
.db $38
.db $E9
.db $01
.db $CD
.db $E2
.db $78
.db $D0
.db $18
.db $8D
.db $DD
.db $78
.db $AD
.db $E2
.db $78
.db $38
.db $E9
.db $0A
.db $8D
.db $E2
.db $78
.db $CE
.db $F0
.db $05
.db $20
.db $F1
.db $A3
.db $20
.db $5D
.db $A4
.db $4C
.db $AD
.db $A6
.db $8D
.db $DD
.db $78
.db $4C
.db $AD
.db $A6
L0DA649:
    JMP L0DA69B.w

L0DA64C:
    LDA $78DD
    CMP $78DC
    BEQ L0DA686
    JSR L0FF56C.w
    LDA $78DD
    CLC
    ADC #1
    STA $0549
    SEC
    SBC $78E2
    CMP #11
    BNE L0DA683
.db $AD
.db $49
.db $05
.db $8D
.db $DD
.db $78
.db $AD
.db $E2
.db $78
.db $18
.db $69
.db $0A
.db $8D
.db $E2
.db $78
.db $EE
.db $F0
.db $05
.db $20
.db $F1
.db $A3
.db $20
.db $5D
.db $A4
.db $4C
.db $AD
.db $A6
L0DA683:
    LDA $0549
L0DA686:
    STA $78DD
    JMP L0DA6AD.w

L0DA68C:
    DEC $74B4
    LDA $74B4
    BPL L0DA6AA
    LDA #3
    STA $74B4
    BNE L0DA6AA
L0DA69B:
    INC $74B4
    LDA $74B4
    CMP #4
    BNE L0DA6AA
    LDA #0
    STA $74B4
L0DA6AA:
    JSR L0DA3F1.w
L0DA6AD:
    RTS

L0DA6AE:
    JSR L0DA5F4.w
    LDA $1A
    AND #128
    BNE L0DA6D9
    LDA $1A
    AND #64
    BEQ L0DA6F4
    LDA $78DE
    BNE L0DA6CB
    JSR L0DADB0.w
    LDA #15
    STA $8A
    BNE L0DA719
L0DA6CB:
    LDA #0
    STA $78DE
    JSR L0FC288.w
    LDA #0
    STA $3D
    BEQ L0DA6F4
L0DA6D9:
    LDA $78DD
    CMP #1
    BEQ L0DA6F4
    JSR L0FF572.w
    LDA $78DE
    BEQ L0DA6EE
.db $20
.db $ED
.db $A7
.db $4C
.db $F4
.db $A6
L0DA6EE:
    LDA $78DD
    STA $78DE
L0DA6F4:
    JSR L0D9E45.w
    LDA $78DD
    CMP $78DE
    BNE L0DA703
    LDA #1
    BNE L0DA705
L0DA703:
    LDA #3
L0DA705:
    STA $3F
    LDA $78DD
    JSR L0DA33E.w
    LDA #2
    STA $3F
    LDA $78DE
    BEQ L0DA719
    JSR L0DA33E.w
L0DA719:
    RTS

.db $20
.db $F4
.db $A5
.db $A5
.db $1A
.db $29
.db $80
.db $D0
.db $0F
.db $A5
.db $1A
.db $29
.db $40
.db $F0
.db $38
.db $20
.db $B0
.db $AD
.db $A9
.db $0F
.db $85
.db $8A
.db $D0
.db $3C
.db $AD
.db $DD
.db $78
.db $C9
.db $01
.db $F0
.db $28
.db $20
.db $72
.db $F5
.db $AE
.db $DD
.db $78
.db $CA
.db $BD
.db $77
.db $78
.db $F0
.db $1C
.db $8D
.db $84
.db $74
.db $A9
.db $00
.db $9D
.db $77
.db $78
.db $20
.db $FF
.db $F8
.db $AD
.db $B8
.db $05
.db $49
.db $01
.db $8D
.db $DD
.db $74
.db $20
.db $6E
.db $F9
.db $20
.db $F1
.db $A3
.db $20
.db $5D
.db $A4
.db $20
.db $45
.db $9E
.db $A9
.db $03
.db $85
.db $3F
.db $AD
.db $DD
.db $78
.db $20
.db $3E
.db $A3
.db $60
.db $20
.db $88
.db $C2
.db $A9
.db $00
.db $85
.db $3D
.db $A5
.db $1A
.db $29
.db $08
.db $D0
.db $21
.db $A5
.db $1A
.db $29
.db $04
.db $D0
.db $2F
.db $A5
.db $1A
.db $29
.db $02
.db $D0
.db $40
.db $A5
.db $1A
.db $29
.db $01
.db $D0
.db $49
.db $A5
.db $1A
.db $29
.db $40
.db $F0
.db $55
.db $20
.db $B0
.db $AD
.db $A9
.db $0F
.db $85
.db $8A
.db $D0
.db $4F
.db $AD
.db $E2
.db $78
.db $38
.db $E9
.db $0A
.db $90
.db $44
.db $8D
.db $E2
.db $78
.db $CE
.db $F0
.db $05
.db $20
.db $5D
.db $A4
.db $4C
.db $E6
.db $A7
.db $AD
.db $E2
.db $78
.db $18
.db $69
.db $0A
.db $CD
.db $DC
.db $78
.db $B0
.db $2D
.db $8D
.db $E2
.db $78
.db $EE
.db $F0
.db $05
.db $20
.db $5D
.db $A4
.db $4C
.db $E6
.db $A7
.db $CE
.db $B4
.db $74
.db $AD
.db $B4
.db $74
.db $10
.db $16
.db $A9
.db $03
.db $8D
.db $B4
.db $74
.db $D0
.db $0F
.db $EE
.db $B4
.db $74
.db $AD
.db $B4
.db $74
.db $C9
.db $04
.db $D0
.db $05
.db $A9
.db $00
.db $8D
.db $B4
.db $74
.db $20
.db $F1
.db $A3
.db $20
.db $45
.db $9E
.db $60
.db $AE
.db $DD
.db $78
.db $CA
.db $BD
.db $77
.db $78
.db $8D
.db $84
.db $74
.db $AC
.db $DE
.db $78
.db $88
.db $B9
.db $77
.db $78
.db $8D
.db $9F
.db $74
.db $9D
.db $77
.db $78
.db $AD
.db $84
.db $74
.db $99
.db $77
.db $78
.db $20
.db $C2
.db $F8
.db $20
.db $5D
.db $A4
.db $20
.db $F1
.db $A3
.db $A9
.db $00
.db $8D
.db $DE
.db $78
.db $20
.db $88
.db $C2
.db $A9
.db $00
.db $85
.db $3D
.db $60
L0DA820:
    PHA
    STA $78D9
    DEC $78D9
    JSR L0DAD8A.w
    LDA #0
    STA $0450
    PLA
    JSR L0DA0E6.w
    LDX $0450
    LDA #237
    STA $0451,X
    INX
    LDA #239
    STA $0451,X
    LDY $10
    LDA #255
L0DA845:
    STA $0311,Y
    DEY
    BPL L0DA845
    JSR L0DAE6C.w
    JSR L0DAE02.w
    LDX $7E
    LDY $7F
    LDA #72
    STA $0310
    JSR L0FC842.w
    JSR L0FC70D.w
    RTS

.db $20
.db $8A
.db $AD
.db $A2
.db $00
.db $BD
.db $79
.db $A8
.db $C9
.db $EF
.db $F0
.db $06
.db $9D
.db $51
.db $04
.db $E8
.db $D0
.db $F3
.db $8E
.db $50
.db $04
.db $4C
.db $33
.db $A8
.db $77
.db $78
.db $7B
.db $76
.db $6A
.db $75
.db $FF
.db $FF
.db $EF
L0DA882:
    PHA
    JSR L0DAD8A.w
    LDA #0
    STA $0450
    PLA
    JSR L0DA0BA.w
    LDX #0
    STX $16
    LDA #4
    JSR L0DADDC.w
    LDX $16
    LDA #237
    STA $0451,X
    INX
    LDA $0450
    LDA #239
    STA $0451,X
    LDY #10
    LDA #255
L0DA8AC:
    STA $0311,Y
    DEY
    BPL L0DA8AC
    JSR L0DAE6C.w
    JSR L0DAE02.w
    LDX $7E
    LDY $7F
    LDA #69
    STA $0310
    JSR L0FC842.w
    JSR L0FC70D.w
    RTS

L0DA8C8:
    PHA
    JSR L0DAD8A.w
    PLA
    STA $16
    TAX
    DEX
    STX $78D9
    LDA #0
    STA $78A3,X
    LDA $7877,X
    BEQ L0DA912
    LDX $78CC
    CPX #1
    BEQ L0DA8FC
    LDA $16
    JSR L0DA0E6.w
    LDA $78CC
    CMP #3
    BNE L0DA90A
.db $AE
.db $D9
.db $78
.db $BD
.db $CF
.db $73
.db $8D
.db $87
.db $74
.db $D0
.db $0E
L0DA8FC:
.db $8D
.db $84
.db $74
.db $20
.db $AB
.db $F8
.db $A9
.db $00
.db $8D
.db $8F
.db $74
.db $8D
.db $88
.db $74
L0DA90A:
    LDA #39
    JSR L0FE6B8.w
    JMP L0DA91C.w

L0DA912:
    LDY #24
    LDA #255
L0DA916:
    STA $0311,Y
    DEY
    BPL L0DA916
L0DA91C:
    LDX $7E
    LDY $7F
    LDA #76
    STA $0310
    JSR L0FC842.w
    JSR L0FC70D.w
    RTS

L0DA92C:
    JSR L0D9192.w
    JSR L0FE684.w
    LDA $058F
    BEQ L0DA93D
    JSR L0FE696.w
    JMP L0DA957.w

L0DA93D:
    LDA #30
    JSR L0FCA48.w
    JSR L0FCA50.w
    LDA $78A2
    BNE L0DA952
    LDA #31
    JSR L0FCA58.w
    JSR L0FCA60.w
L0DA952:
    LDA #0
    STA $05EF
L0DA957:
    RTS

L0DA958:
.db $10
.db $20
.db $30
.db $40
.db $50
.db $60
.db $70
.db $80
.db $90
.db $A0
.db $B0
.db $C0
.db $A0
.db $01
.db $20
.db $C2
.db $AD
.db $A0
.db $04
.db $B1
.db $74
.db $18
.db $69
.db $08
.db $85
.db $00
.db $C8
.db $B1
.db $74
.db $18
.db $69
.db $10
.db $85
.db $01
.db $20
.db $17
.db $C5
.db $A5
.db $04
.db $85
.db $7E
.db $A5
.db $05
.db $85
.db $7F
.db $A9
.db $00
.db $8D
.db $50
.db $04
.db $A9
.db $00
.db $8D
.db $95
.db $05
.db $C9
.db $0A
.db $D0
.db $25
.db $18
.db $6D
.db $E2
.db $78
.db $CD
.db $DC
.db $78
.db $F0
.db $0E
.db $A2
.db $02
.db $A9
.db $FF
.db $8D
.db $51
.db $04
.db $A9
.db $F3
.db $8D
.db $52
.db $04
.db $D0
.db $1B
.db $A2
.db $02
.db $A9
.db $FF
.db $8D
.db $51
.db $04
.db $A9
.db $9F
.db $8D
.db $52
.db $04
.db $D0
.db $0D
.db $AD
.db $95
.db $05
.db $18
.db $6D
.db $E2
.db $78
.db $18
.db $69
.db $01
.db $20
.db $BA
.db $A0
.db $8E
.db $50
.db $04
.db $A2
.db $00
.db $86
.db $16
.db $A9
.db $05
.db $20
.db $DC
.db $AD
.db $A6
.db $16
.db $A9
.db $ED
.db $9D
.db $51
.db $04
.db $E8
.db $A9
.db $EF
.db $9D
.db $51
.db $04
.db $A0
.db $0C
.db $A9
.db $FF
.db $99
.db $11
.db $03
.db $88
.db $10
.db $FA
.db $20
.db $6C
.db $AE
.db $20
.db $02
.db $AE
.db $A6
.db $7E
.db $A4
.db $7F
.db $A9
.db $46
.db $8D
.db $10
.db $03
.db $20
.db $42
.db $C8
.db $20
.db $0D
.db $C7
.db $A5
.db $7E
.db $85
.db $00
.db $A5
.db $7F
.db $85
.db $01
.db $20
.db $1C
.db $C8
.db $20
.db $1C
.db $C8
.db $A5
.db $00
.db $85
.db $7E
.db $A5
.db $01
.db $85
.db $7F
.db $A9
.db $00
.db $8D
.db $50
.db $04
.db $EE
.db $95
.db $05
.db $AD
.db $95
.db $05
.db $C9
.db $0B
.db $F0
.db $03
.db $4C
.db $8F
.db $A9
.db $60
.db $A2
.db $0A
.db $A9
.db $00
.db $9D
.db $A3
.db $78
.db $CA
.db $10
.db $FA
.db $A0
.db $02
.db $20
.db $C2
.db $AD
.db $A0
.db $04
.db $B1
.db $74
.db $18
.db $69
.db $08
.db $85
.db $00
.db $C8
.db $B1
.db $74
.db $18
.db $69
.db $20
.db $85
.db $01
.db $20
.db $17
.db $C5
.db $A5
.db $04
.db $85
.db $7E
.db $A5
.db $05
.db $85
.db $7F
.db $A9
.db $00
.db $8D
.db $50
.db $04
.db $A9
.db $00
.db $8D
.db $95
.db $05
.db $C9
.db $09
.db $D0
.db $28
.db $48
.db $A0
.db $16
.db $A9
.db $FF
.db $99
.db $11
.db $03
.db $88
.db $10
.db $FA
.db $68
.db $18
.db $6D
.db $E2
.db $78
.db $CD
.db $DC
.db $78
.db $F0
.db $0A
.db $A0
.db $0E
.db $A9
.db $F3
.db $99
.db $11
.db $03
.db $4C
.db $B4
.db $AA
.db $A0
.db $0E
.db $A9
.db $9F
.db $99
.db $11
.db $03
.db $D0
.db $2D
.db $AD
.db $95
.db $05
.db $18
.db $6D
.db $E2
.db $78
.db $18
.db $6D
.db $EE
.db $78
.db $8D
.db $F1
.db $74
.db $AA
.db $BD
.db $4F
.db $74
.db $8D
.db $8F
.db $74
.db $20
.db $61
.db $A1
.db $AE
.db $95
.db $05
.db $AD
.db $EC
.db $05
.db $C9
.db $06
.db $90
.db $03
.db $38
.db $E9
.db $02
.db $9D
.db $A3
.db $78
.db $A9
.db $1E
.db $20
.db $B8
.db $E6
.db $A6
.db $7E
.db $A4
.db $7F
.db $A9
.db $4B
.db $8D
.db $10
.db $03
.db $20
.db $42
.db $C8
.db $20
.db $0D
.db $C7
.db $A5
.db $7E
.db $85
.db $00
.db $A5
.db $7F
.db $85
.db $01
.db $20
.db $1C
.db $C8
.db $20
.db $1C
.db $C8
.db $A5
.db $00
.db $85
.db $7E
.db $A5
.db $01
.db $85
.db $7F
.db $A9
.db $00
.db $8D
.db $50
.db $04
.db $EE
.db $95
.db $05
.db $AD
.db $95
.db $05
.db $CD
.db $DC
.db $78
.db $F0
.db $07
.db $C9
.db $0A
.db $F0
.db $03
.db $4C
.db $5B
.db $AA
.db $60
L0DAAF1:
    JSR L0D9192.w
    JSR L0FE684.w
    LDA $058F
    BNE L0DAB00
    INC $8A
    BNE L0DAB03
L0DAB00:
    JSR L0FE696.w
L0DAB03:
    RTS

L0DAB04:
    LDA #1
    JSR L0FC9BD.w
    JSR L0D9110.w
    LDA #5
    STA $7DA6
    JSR L0DAD67.w
    LDA $05B8
    STA $74DD
    LDA #13
    STA $4A
    LDA #8
    JSR L0FCA94.w
    LDA #15
    STA $8A
    RTS

L0DAB28:
    JSR L0FC288.w
    JSR L0FE684.w
    LDA $058F
    BEQ L0DAB90
    CMP #1
    BNE L0DAB95
    LDA $6CF7
    BEQ L0DAB61
.db $AD
.db $4C
.db $74
.db $C9
.db $03
.db $90
.db $1E
.db $AD
.db $8C
.db $6E
.db $D0
.db $08
.db $AD
.db $C0
.db $6C
.db $CD
.db $C1
.db $6C
.db $D0
.db $11
.db $AD
.db $4D
.db $74
.db $18
.db $6D
.db $4E
.db $74
.db $8D
.db $ED
.db $78
L0DAB5A:
    LDA #0
    STA $78EE
    BEQ L0DAB75
L0DAB61:
    LDX $05B8
    LDA $744D,X
    STA $78ED
    LDA $05B8
    BEQ L0DAB5A
.db $AD
.db $4D
.db $74
.db $8D
.db $EE
.db $78
L0DAB75:
    LDA $78ED
    BNE L0DAB8B
    JSR L0DB1FD.w
    LDA #34
    STA $7DA6
    JSR L0DAD67.w
    LDA #16
    STA $8A
    BNE L0DABB3
L0DAB8B:
.db $A9
.db $06
.db $4C
.db $26
.db $AE
L0DAB90:
    LDA #8
    JMP L0DAE26.w

L0DAB95:
.db $A9
.db $00
.db $8D
.db $E2
.db $78
.db $A9
.db $01
.db $8D
.db $DD
.db $78
.db $20
.db $26
.db $AA
.db $A9
.db $16
.db $20
.db $48
.db $CA
.db $20
.db $50
.db $CA
.db $A9
.db $02
.db $85
.db $28
.db $20
.db $0D
.db $C7
.db $E6
.db $8A
L0DABB3:
    RTS

.db $20
.db $9A
.db $AC
.db $A5
.db $1A
.db $29
.db $80
.db $D0
.db $10
.db $A5
.db $1A
.db $29
.db $40
.db $F0
.db $27
.db $20
.db $B0
.db $AD
.db $A9
.db $10
.db $85
.db $8A
.db $4C
.db $FB
.db $AB
.db $AD
.db $DD
.db $78
.db $18
.db $6D
.db $E2
.db $78
.db $18
.db $6D
.db $EE
.db $78
.db $8D
.db $E4
.db $78
.db $AA
.db $CA
.db $BD
.db $4F
.db $74
.db $8D
.db $D1
.db $78
.db $20
.db $B0
.db $AD
.db $E6
.db $8A
.db $D0
.db $11
.db $A9
.db $03
.db $85
.db $3F
.db $AD
.db $DD
.db $78
.db $18
.db $6D
.db $E2
.db $78
.db $20
.db $05
.db $A3
.db $20
.db $23
.db $9E
.db $60
.db $AD
.db $D1
.db $78
.db $0A
.db $AA
.db $BD
.db $AD
.db $DC
.db $85
.db $02
.db $BD
.db $AE
.db $DC
.db $85
.db $03
.db $A0
.db $00
.db $B1
.db $02
.db $99
.db $A5
.db $7E
.db $C9
.db $EF
.db $F0
.db $03
.db $C8
.db $D0
.db $F4
.db $20
.db $FD
.db $B1
.db $A9
.db $15
.db $8D
.db $A6
.db $7D
.db $20
.db $67
.db $AD
.db $E6
.db $8A
.db $60
.db $20
.db $F4
.db $A5
.db $20
.db $45
.db $9E
.db $A5
.db $1A
.db $29
.db $80
.db $D0
.db $29
.db $A5
.db $1A
.db $29
.db $40
.db $D0
.db $09
.db $A5
.db $1A
.db $29
.db $0F
.db $D0
.db $10
.db $4C
.db $8A
.db $AC
.db $20
.db $B0
.db $AD
.db $20
.db $96
.db $E6
.db $A9
.db $10
.db $85
.db $8A
.db $4C
.db $94
.db $AC
.db $AD
.db $D1
.db $78
.db $D0
.db $36
.db $20
.db $B0
.db $AD
.db $E6
.db $8A
.db $4C
.db $94
.db $AC
.db $AD
.db $D1
.db $78
.db $F0
.db $F3
.db $AE
.db $DD
.db $78
.db $CA
.db $BD
.db $77
.db $78
.db $8D
.db $84
.db $74
.db $20
.db $AB
.db $F8
.db $AD
.db $8F
.db $74
.db $D0
.db $17
.db $AD
.db $D1
.db $78
.db $8D
.db $8F
.db $74
.db $A9
.db $00
.db $8D
.db $D1
.db $78
.db $20
.db $94
.db $F8
.db $AD
.db $E4
.db $78
.db $20
.db $31
.db $AE
.db $20
.db $F1
.db $A3
.db $A9
.db $03
.db $85
.db $3F
.db $AD
.db $DD
.db $78
.db $20
.db $05
.db $A3
.db $60
.db $A9
.db $15
.db $85
.db $8A
.db $60
.db $20
.db $88
.db $C2
.db $A9
.db $00
.db $85
.db $3D
.db $A5
.db $1E
.db $29
.db $04
.db $D0
.db $25
.db $A5
.db $1E
.db $29
.db $08
.db $F0
.db $4D
.db $AE
.db $DD
.db $78
.db $E0
.db $01
.db $F0
.db $0A
.db $20
.db $6C
.db $F5
.db $CA
.db $8E
.db $DD
.db $78
.db $4C
.db $FA
.db $AC
.db $AD
.db $E2
.db $78
.db $F0
.db $F8
.db $CE
.db $E2
.db $78
.db $20
.db $26
.db $AA
.db $4C
.db $FA
.db $AC
.db $AD
.db $DD
.db $78
.db $18
.db $6D
.db $E2
.db $78
.db $CD
.db $DC
.db $78
.db $F0
.db $E3
.db $AE
.db $DD
.db $78
.db $E0
.db $09
.db $F0
.db $0A
.db $20
.db $6C
.db $F5
.db $E8
.db $8E
.db $DD
.db $78
.db $4C
.db $FA
.db $AC
.db $A9
.db $09
.db $18
.db $6D
.db $E2
.db $78
.db $CD
.db $DC
.db $78
.db $F0
.db $06
.db $EE
.db $E2
.db $78
.db $20
.db $26
.db $AA
.db $60
L0DACFB:
    LDX #39
    LDA #0
L0DACFF:
    STA $7877,X
    STA $78A3,X
    DEX
    BPL L0DACFF
    LDA $78CC
    CMP #1
    BEQ L0DAD45
    CMP #3
    BNE L0DAD17
.db $A9
.db $01
.db $D0
.db $03
L0DAD17:
    LDA $05B8
    STA $0A
    TAX
    LDA $6CF6,X
    STA $16
    LDA $0A
    ASL
    TAX
    LDA $6CD2,X
    STA $04
    LDA $6CD3,X
    STA $05
    LDX #0
L0DAD32:
    LDY #0
    LDA ($04),Y
    STA $7877,X
    INX
    LDY #12
    JSR L0FC38E.w
    DEC $16
    BNE L0DAD32
    BEQ L0DAD63
L0DAD45:
.db $AD
.db $08
.db $6D
.db $85
.db $04
.db $AD
.db $09
.db $6D
.db $85
.db $05
.db $A2
.db $00
.db $A0
.db $00
.db $B1
.db $04
.db $F0
.db $0C
.db $9D
.db $77
.db $78
.db $E8
.db $A0
.db $0C
.db $20
.db $8E
.db $C3
.db $4C
.db $51
.db $AD
L0DAD63:
    STX $78DC
    RTS

L0DAD67:
    JSR L0FC70D.w
    JSR L0D9192.w
    LDA #0
    STA $3D
    LDA #0
    STA $4A
    LDA #10
    JSR L0FCA94.w
    JSR L0FC336.w
    INC $36
    LDA $7DBF
    BNE L0DAD89
    LDA $7DB9
    BEQ L0DAD67
L0DAD89:
    RTS

L0DAD8A:
    LDA $78D4
    STA $00
    LDA $78D3
    STA $01
    JSR L0FC517.w
    LDA $04
    STA $7E
    LDA $05
    STA $7F
    RTS

L0DADA0:
    LDA #31
    JSR L0FCA58.w
    JSR L0FCA60.w
    LDA #30
    JSR L0FCA48.w
    JMP L0FCA50.w

L0DADB0:
    JSR L0FC288.w
    LDA #128
    STA $28
    JSR L0FC70D.w
    LDA #30
    JSR L0FCA48.w
    JMP L0FCA50.w

L0DADC2:
    DEY
    TYA
    ASL
    TAY
    LDA L0DADD2.w,Y
    STA $74
    INY
    LDA L0DADD2.w,Y
    STA $75
    RTS

L0DADD2:
.db $35
.db $7C
.db $3B
.db $7C
.db $41
.db $7C
.db $47
.db $7C
.db $4D
.db $7C
L0DADDC:
    STA $17
    LDX $16
L0DADE0:
    LDA $0451,X
    CMP #15
    BEQ L0DADED
    CMP #31
    BEQ L0DADED
    DEC $17
L0DADED:
    INX
    CPX $0450
    BNE L0DADE0
    INC $17
L0DADF5:
    LDA #255
    STA $0451,X
    INX
    DEC $17
    BNE L0DADF5
    STX $16
    RTS

L0DAE02:
    LDX #0
L0DAE04:
    INX
    LDA $0311,X
    CMP #237
    BNE L0DAE04
    STX $04
    TXA
    SEC
    ADC #17
    STA $00
    STA $02
    DEC $02
    LDA #3
    STA $01
    STA $03
    LDA #0
    STA $05
    JSR L0FC209.w
    RTS

L0DAE26:
    STA $0A
    LDA #8
    STA $4A
    LDA #12
    JMP L0FCA94.w

.db $85
.db $10
.db $C6
.db $10
.db $98
.db $48
.db $AD
.db $4D
.db $74
.db $18
.db $6D
.db $4E
.db $74
.db $38
.db $E5
.db $10
.db $85
.db $11
.db $A4
.db $10
.db $C0
.db $26
.db $B0
.db $0B
.db $B9
.db $50
.db $74
.db $99
.db $4F
.db $74
.db $C8
.db $C6
.db $11
.db $D0
.db $F1
.db $A9
.db $00
.db $99
.db $4F
.db $74
.db $A5
.db $10
.db $CD
.db $4D
.db $74
.db $90
.db $06
.db $CE
.db $4E
.db $74
.db $4C
.db $69
.db $AE
.db $CE
.db $4D
.db $74
.db $68
.db $A8
.db $60
L0DAE6C:
    LDA #13
    STA $4A
    LDA #11
    JMP L0FCA94.w

L0DAE75:
    LDA #6
    STA $4A
    LDA #12
    JMP L0FCA94.w

.db $AD
.db $B5
.db $05
.db $F0
.db $09
.db $A9
.db $02
.db $85
.db $4A
.db $A9
.db $04
.db $4C
.db $94
.db $CA
.db $A9
.db $00
.db $8D
.db $8F
.db $05
.db $85
.db $8A
.db $8D
.db $EF
.db $05
.db $20
.db $9A
.db $D3
.db $20
.db $A0
.db $AD
.db $60
L0DAE9D:
    LDX $78DB
    LDA $7920,X
    STA $78DA
    AND #15
    STA $00
    LDA $7920
    JSR L0FC39A.w
    SEC
    SBC #1
    EOR #2
    CLC
    ADC #1
    JSR L0FC3A0.w
    ORA $00
    STA $7920,X
    LDX $7434
    DEX
    TXA
    ASL
    TAX
    LDA L0DB4FA.w,X
    STA $04
    LDA L0DB4FB.w,X
    STA $05
    LDX $7434
    DEX
    LDA $6E32,X
    STA $78D1
    LDA #0
    STA $78D5
L0DAEE0:
    LSR $78D1
    BCC L0DAEE8
    JSR L0DAF3D.w
L0DAEE8:
    INC $78D5
    LDA $78D5
    CMP #8
    BNE L0DAEE0
    LDA #0
    STA $7DA5
    LDA #48
    STA $7DA9
    LDA #1
    STA $7DAC
    LDA #1
    JSR L0FC9BD.w
    JSR L0D9110.w
    JSR L0FC288.w
    LDA #3
    STA $3D
    JSR L0D8C0C.w
    LDX $78DB
    LDA $7928,X
    STA $0570
    JSR L0DAE75.w
    LDA $7DA6
    CMP #255
    BNE L0DAF2D
.db $A9
.db $00
.db $8D
.db $EF
.db $05
.db $F0
.db $0F
L0DAF2D:
    LDA #1
    STA $05D8
    LDA $0570
    BEQ L0DAF3A
    JSR L0FFACC.w
L0DAF3A:
    INC $8A
    RTS

L0DAF3D:
    LDA $78D5
    ASL
    CLC
    ADC $78D5
    CLC
    ADC $04
    STA $02
    LDA $05
    ADC #0
    STA $03
    LDY #0
    LDA ($02),Y
    BPL L0DAF7C
    INY
    LDA $78DB
    CLC
    ADC #1
    CMP ($02),Y
    BNE L0DAF7C
    INY
    LDA ($02),Y
    ASL
    TAX
    LDA L0DB61B.w,X
    STA $78E5
    LDA (L0DB61B.w + 1),X
    STA $78E6
    JSR L0D99A1.w
    LDA #2
    STA $05EF
    PLA
    PLA
L0DAF7C:
    RTS

L0DAF7D:
    JSR L0D9192.w
    LDA #0
    STA $3D
    LDA #0
    STA $4A
    LDA #10
    JSR L0FCA94.w
    LDA $7DAC
    BNE L0DAFB2
    LDA $78DA
    LDX $78DB
    STA $7920,X
    JSR L0DADA0.w
    LDA #1
    JSR L0FC9BD.w
    JSR L0D9110.w
    LDA #128
    STA $28
    JSR L0FC70D.w
    LDA #0
    STA $05EF
L0DAFB2:
    RTS

L0DAFB3:
    JSR L0D9192.w
    JSR L0FE684.w
    LDA $1A
    BEQ L0DAFBF
    INC $8A
L0DAFBF:
    RTS

L0DAFC0:
    INC $05EF
    RTS

L0DAFC4:
    LDX $78D1
    LDA L0DBED2.w,X
    STA $0A
    LDA #9
    STA $4A
    LDA #12
    JSR L0FCA94.w
    JSR L0DB1FD.w
    LDA #160
    STA $7DA9
    LDA #3
    STA $7DA6
    JSR L0DAD67.w
    LDA #1
    JSR L0DAE26.w
    LDA #112
    STA $77
    LDA #48
    STA $76
    INC $8A
    RTS

L0DAFF5:
    JSR L0D9192.w
    LDA #0
    STA $3D
    JSR L0FE684.w
    LDA $05AC
    CMP #1
    BEQ L0DB00C
    LDA #15
    STA $8A
    BNE L0DB04A
L0DB00C:
    LDA #0
    STA $78CC
    LDX $78D1
    LDA L0DBED2.w,X
    CMP #7
    BNE L0DB040
.db $EE
.db $CC
.db $78
.db $AD
.db $08
.db $6D
.db $85
.db $04
.db $AD
.db $09
.db $6D
.db $85
.db $05
.db $A0
.db $00
.db $B1
.db $04
.db $D0
.db $0E
.db $A9
.db $1C
.db $8D
.db $A6
.db $7D
.db $20
.db $67
.db $AD
.db $A9
.db $0F
.db $85
.db $8A
.db $D0
.db $0E
.db $A9
.db $08
.db $D0
.db $02
L0DB040:
    LDA #9
    STA $7DA6
    JSR L0DAD67.w
    INC $8A
L0DB04A:
    RTS

L0DB04B:
    JSR L0DA5F4.w
    JSR L0D9E45.w
    LDA $1A
    AND #128
    BNE L0DB066
    LDA $1A
    AND #64
    BEQ L0DB07A
.db $20
.db $96
.db $E6
.db $A9
.db $0F
.db $85
.db $8A
.db $D0
.db $02
L0DB066:
    INC $8A
    JSR L0FC288.w
    LDA #128
    STA $28
    JSR L0FC70D.w
    LDA #30
    JSR L0FCA48.w
    JSR L0FCA50.w
L0DB07A:
    LDA #3
    STA $3F
    LDA $78DD
    JMP L0DA33E.w

L0DB084:
    LDX #0
    STX $0450
    LDA $78DD
    JSR L0DA0BA.w
    LDA #239
    STA $0451,X
    JSR L0DB21F.w
    LDX $78DD
    DEX
    LDA $7877,X
    STA $7484
    JSR L0FF8AB.w
    LDX $78D1
    LDA L0DBED2.w,X
    CMP #7
    BEQ L0DB0E9
    CMP #2
    BNE L0DB0C3
    PHA
    LDA #2
    STA $7EB5
    LDA #47
    STA $7EB6
    LDA #239
    STA $7EB7
    PLA
L0DB0C3:
    STA $0A
    JSR L0DB19F.w
    BCS L0DB0CE
    LDA #4
    BNE L0DB0D0
L0DB0CE:
    LDA #10
L0DB0D0:
    STA $7DA6
    LDA #1
    STA $7DAC
    LDA #1
    JSR L0FC9BD.w
    JSR L0D9110.w
    JSR L0DAD67.w
    JSR L0FF894.w
    JMP L0DB0EC.w

L0DB0E9:
.db $20
.db $D9
.db $B1
L0DB0EC:
    LDA $78D1
    LSR
    LSR
    TAX
    LDA $6E64,X
    STA $09
    BCC L0DB111
    JSR L0FC39A.w
    SEC
    SBC #1
    STA $08
    JSR L0FC3A0.w
    PHA
    LDA $09
    AND #15
    STA $09
    PLA
    ORA $09
    JMP L0DB11E.w

L0DB111:
    AND #15
    SEC
    SBC #1
    STA $08
    LDA $09
    AND #240
    ORA $08
L0DB11E:
    STA $6E64,X
    LDA $08
    BNE L0DB13A
.db $20
.db $47
.db $B1
.db $AD
.db $D1
.db $78
.db $49
.db $01
.db $8D
.db $D1
.db $78
.db $20
.db $47
.db $B1
.db $A9
.db $0D
.db $8D
.db $A6
.db $7D
.db $D0
.db $05
L0DB13A:
    LDA #2
    STA $7DA6
    JSR L0DAD67.w
    LDA #15
    STA $8A
    RTS

.db $AE
.db $34
.db $74
.db $CA
.db $8A
.db $0A
.db $AA
.db $BD
.db $70
.db $BD
.db $85
.db $04
.db $BD
.db $71
.db $BD
.db $85
.db $05
.db $A9
.db $00
.db $8D
.db $E7
.db $78
.db $A0
.db $02
.db $B1
.db $04
.db $C9
.db $01
.db $D0
.db $08
.db $C8
.db $B1
.db $04
.db $CD
.db $D1
.db $78
.db $F0
.db $12
.db $EE
.db $E7
.db $78
.db $AD
.db $E7
.db $78
.db $C9
.db $08
.db $F0
.db $CF
.db $A0
.db $04
.db $20
.db $8E
.db $C3
.db $4C
.db $5D
.db $B1
.db $A0
.db $00
.db $B1
.db $04
.db $8D
.db $D4
.db $78
.db $C8
.db $B1
.db $04
.db $8D
.db $D3
.db $78
.db $AE
.db $34
.db $74
.db $CA
.db $AC
.db $E7
.db $78
.db $B9
.db $B1
.db $D9
.db $1D
.db $00
.db $6E
.db $9D
.db $00
.db $6E
.db $4C
.db $59
.db $8C
L0DB19F:
    LDY $0A
    LDA L0DB1D2.w,Y
    CLC
    ADC #1
    STA $0549
    LDX $0A
    LDA L0DB1CB.w,Y
    TAY
    CPX #6
    BNE L0DB1B8
    LDA #99
    BNE L0DB1BE
L0DB1B8:
    LDA $7484,Y
    CLC
    ADC #1
L0DB1BE:
    CMP $0549
    BCS L0DB1C9
    STA $7484,Y
    CLC
    BCC L0DB1CA
L0DB1C9:
    SEC
L0DB1CA:
    RTS

L0DB1CB:
.db $09
.db $05
.db $08
.db $07
.db $06
.db $03
.db $04
L0DB1D2:
.db $28
.db $28
.db $28
.db $28
.db $28
.db $34
.db $63
.db $A9
.db $00
.db $8D
.db $88
.db $74
.db $A9
.db $00
.db $8D
.db $8F
.db $74
.db $AD
.db $B8
.db $05
.db $8D
.db $DD
.db $74
.db $20
.db $94
.db $F8
.db $20
.db $6E
.db $F9
.db $A9
.db $01
.db $8D
.db $AC
.db $7D
.db $A9
.db $07
.db $8D
.db $A6
.db $7D
.db $20
.db $67
.db $AD
.db $60
L0DB1FD:
    LDA #0
    STA $05D8
    LDA #0
    STA $7DA5
    LDA #1
    STA $7DAC
    LDA #160
    STA $7DA9
    LDA $78A2
    BNE L0DB21E
    LDA #1
    JSR L0FC9BD.w
    JSR L0D9110.w
L0DB21E:
    RTS

L0DB21F:
    LDX #0
L0DB221:
    LDA $0451,X
    STA $7EA5,X
    INX
    CPX $0450
    BNE L0DB221
    LDA #239
    STA $7EA5,X
    RTS

L0DB233:
    JSR L0D9192.w
    LDA #0
    STA $3D
    JSR L0FE684.w
    LDA $05AC
    CMP #1
    BEQ L0DB24A
    LDA #15
    STA $8A
    BNE L0DB261
L0DB24A:
    LDA #1
    STA $78EC
    LDA #0
    STA $8A
    STA $058F
    INC $2A
    LDA #11
    STA $4A
    LDA #8
    JSR L0FCA94.w
L0DB261:
    RTS

L0DB262:
    LDX $7434
    DEX
    LDA L0DB9AC.w,X
    SEC
    SBC #1
    CLC
    ADC #49
    STA $7434
    RTS

L0DB273:
    JSR L0DB1FD.w
    LDA $78EF
    CLC
    ADC #96
    STA $7EA5
    LDA #239
    STA $7EA6
    LDA #6
    STA $7DA6
    JSR L0DAD67.w
    INC $8A
    LDA #96
    STA $76
    LDA #32
    STA $77
    LDA #1
    JMP L0DAE26.w

L0DB29B:
    JSR L0D9192.w
    LDA #0
    STA $3D
    JSR L0FE684.w
    LDA $05AC
    CMP #1
    BEQ L0DB2B5
.db $A5
.db $8A
.db $18
.db $69
.db $03
.db $85
.db $8A
.db $D0
.db $10
L0DB2B5:
    LDA #85
    STA $D7
    LDA #1
    STA $05AF
    LDA #0
    STA $059C
    INC $8A
    RTS

L0DB2C6:
    JSR L0D9192.w
    LDA #0
    STA $3D
    LDA #5
    STA $4A
    LDA #11
    JSR L0FCA94.w
    LDA $059C
    BEQ L0DB2DD
    INC $8A
L0DB2DD:
    RTS

L0DB2DE:
    JSR L0FC288.w
    INC $2A
    LDA #0
    STA $78EC
    STA $8A
    STA $05EF
    STA $058F
    LDA #2
    STA $7479
    RTS

L0DB2F6:
    JSR L0D9192.w
    LDA #0
    STA $3D
    JSR L0DB1FD.w
    LDA #12
    STA $7DA6
    JSR L0DAD67.w
    LDA #1
    JSR L0DAE26.w
    LDA #112
    STA $77
    LDA #48
    STA $76
    INC $8A
    RTS

L0DB318:
    JSR L0D9192.w
    LDA #0
    STA $3D
    JSR L0FE684.w
    LDA $05AC
    CMP #1
    BEQ L0DB32F
    LDA #15
    STA $8A
    BNE L0DB336
L0DB32F:
    LDA #0
    STA $78CC
    INC $8A
L0DB336:
    RTS

L0DB337:
    JSR L0DA5F4.w
    LDA $1A
    AND #128
    BNE L0DB35C
    LDA $1A
    AND #64
    BEQ L0DB34F
    JSR L0DADB0.w
    LDA #15
    STA $8A
    BNE L0DB336
L0DB34F:
    JSR L0D9E45.w
    LDA #3
    STA $3F
    LDA $78DD
    JMP L0DA305.w

L0DB35C:
    JSR L0FF572.w
    LDA $78DD
    JSR L0DA0E6.w
    LDA $748F
    BEQ L0DB389
    ASL
    TAY
    LDA L0FDCAD.w,Y
    STA $02
    LDA (L0FDCAD.w + 1),Y
    STA $03
    LDY #0
L0DB378:
    LDA ($02),Y
    STA $7EA5,Y
    CMP #239
    BEQ L0DB384
    INY
    BNE L0DB378
L0DB384:
    JSR L0DADB0.w
    INC $8A
L0DB389:
    RTS

L0DB38A:
    JSR L0D9192.w
    LDA #0
    STA $3D
    JSR L0DB1FD.w
    LDA #23
    STA $7DA6
    JSR L0DAD67.w
    LDA #1
    JSR L0DAE26.w
    LDA #112
    STA $77
    LDA #48
    STA $76
    INC $8A
    RTS

L0DB3AC:
    INC $8A
    LDA #27
    STA $7DA6
    JMP L0DAD67.w

L0DB3B6:
    LDX $78DD
    DEX
    LDA $7877,X
    STA $7484
    JSR L0FF8AB.w
    LDA $748F
    STA $16
    LDA #0
    STA $748F
    JSR L0FF894.w
    LDA $05B8
    EOR #1
    TAX
    LDA $16
    JSR L0FFA89.w
    LDA #2
    STA $05EF
    LDA #0
    STA $8A
    RTS

L0DB3E5:
    JSR L0DB4A2.w
    BCS L0DB458
    LDA #28
    STA $78A0
    JSR L0D85AC.w
    JSR L0DB1FD.w
    LDA #24
    STA $7DA6
    JSR L0DAD67.w
    LDA #0
    STA $0450
    LDA $78DD
    JSR L0DB4DF.w
    LDY #0
    LDA ($04),Y
    SEC
    SBC #1
    JSR L0DA0C4.w
    JSR L0DB21F.w
    LDA $78E7
    CLC
    ADC #96
    STA $7EB5
    LDA #239
    STA $7EB6
    LDA #25
    STA $7DA6
    JSR L0DAD67.w
    LDX $78DD
    DEX
    LDA $73CF,X
    SEC
    SBC $78E7
    STA $73CF,X
    BEQ L0DB43D
    BCS L0DB440
L0DB43D:
.db $20
.db $5D
.db $B4
L0DB440:
    JSR L0DB4A2.w
    BCS L0DB448
.db $4C
.db $FD
.db $B3
L0DB448:
    LDA #2
    STA $7DA6
    JSR L0DAD67.w
    LDA #26
    STA $78A0
    JSR L0D85AC.w
L0DB458:
    LDA #15
    STA $8A
    RTS

.db $A9
.db $1A
.db $8D
.db $A6
.db $7D
.db $20
.db $67
.db $AD
.db $AD
.db $DD
.db $78
.db $20
.db $DF
.db $B4
.db $A0
.db $00
.db $B1
.db $04
.db $8D
.db $84
.db $74
.db $20
.db $AB
.db $F8
.db $A9
.db $FF
.db $8D
.db $88
.db $74
.db $AD
.db $8F
.db $74
.db $F0
.db $05
.db $A2
.db $01
.db $20
.db $89
.db $FA
.db $A9
.db $3E
.db $8D
.db $8F
.db $74
.db $20
.db $94
.db $F8
.db $20
.db $FF
.db $F8
.db $AE
.db $DD
.db $78
.db $CA
.db $EC
.db $F7
.db $6C
.db $F0
.db $09
.db $BD
.db $D0
.db $73
.db $9D
.db $CF
.db $73
.db $E8
.db $D0
.db $F2
.db $60
L0DB4A2:
    JSR L0FC04E.w
    STA $0B
    BMI L0DB4DA
    AND #3
    CLC
    ADC #1
    STA $78E7
    LDA $0B
    AND #60
    BNE L0DB4C7
    LDA $78E7
    CMP $73CF
    BCS L0DB4DA
    LDA $0B
    AND #64
    BEQ L0DB4DA
    LDA #0
L0DB4C7:
    LSR
    LSR
    CLC
    ADC #1
    STA $78DD
    CMP #11
    BCS L0DB4DA
    CMP $6CF7
    BEQ L0DB4DD
    BCC L0DB4DD
L0DB4DA:
    SEC
    BCS L0DB4DE
L0DB4DD:
    CLC
L0DB4DE:
    RTS

L0DB4DF:
    STA $00
    DEC $00
    LDA #12
    STA $01
    JSR L0FC6C9.w
    LDA $6CD4
    CLC
    ADC $00
    STA $04
    LDA $6CD5
    ADC $01
    STA $05
    RTS

L0DB4FA:
.db $5E
L0DB4FB:
.db $B5
.db $73
.db $B5
.db $76
.db $B5
.db $7C
.db $B5
.db $82
.db $B5
.db $8E
.db $B5
.db $91
.db $B5
.db $9A
.db $B5
.db $9A
.db $B5
.db $A0
.db $B5
.db $A6
.db $B5
.db $A6
.db $B5
.db $A9
.db $B5
.db $B5
.db $B5
.db $B5
.db $B5
.db $B5
.db $B5
.db $BB
.db $B5
.db $C1
.db $B5
.db $C1
.db $B5
.db $CA
.db $B5
.db $D9
.db $B5
.db $DC
.db $B5
.db $DC
.db $B5
.db $E8
.db $B5
.db $E8
.db $B5
.db $E8
.db $B5
.db $E8
.db $B5
.db $E8
.db $B5
.db $E8
.db $B5
.db $E8
.db $B5
.db $EE
.db $B5
.db $EE
.db $B5
.db $F1
.db $B5
.db $F4
.db $B5
.db $F7
.db $B5
.db $F7
.db $B5
.db $F7
.db $B5
.db $00
.db $B6
.db $00
.db $B6
.db $00
.db $B6
.db $00
.db $B6
.db $06
.db $B6
.db $06
.db $B6
.db $0C
.db $B6
.db $15
.db $B6
.db $18
.db $B6
.db $1B
.db $B6
.db $1B
.db $B6
.db $1B
.db $B6
.db $1B
.db $B6
.db $FF
.db $06
.db $01
.db $FF
.db $03
.db $02
.db $FF
.db $04
.db $03
.db $FF
.db $05
.db $04
.db $0A
.db $05
.db $00
.db $FF
.db $02
.db $11
.db $FF
.db $06
.db $23
.db $FF
.db $02
.db $05
.db $FF
.db $02
.db $06
.db $FF
.db $03
.db $08
.db $FF
.db $02
.db $21
.db $02
.db $03
.db $28
.db $FF
.db $03
.db $0A
.db $FF
.db $04
.db $0B
.db $FF
.db $05
.db $0C
.db $10
.db $07
.db $12
.db $FF
.db $04
.db $15
.db $FF
.db $02
.db $0D
.db $FF
.db $03
.db $0E
.db $FF
.db $04
.db $0F
.db $FF
.db $02
.db $1F
.db $FF
.db $03
.db $20
.db $FF
.db $04
.db $16
.db $FF
.db $05
.db $2A
.db $FF
.db $02
.db $17
.db $FF
.db $03
.db $18
.db $FF
.db $04
.db $19
.db $FF
.db $02
.db $1A
.db $08
.db $0B
.db $25
.db $FF
.db $06
.db $1B
.db $FF
.db $07
.db $29
.db $FF
.db $02
.db $1C
.db $FF
.db $03
.db $07
.db $FF
.db $02
.db $26
.db $0A
.db $08
.db $27
.db $FF
.db $03
.db $1D
.db $FF
.db $02
.db $39
.db $FF
.db $04
.db $3A
.db $FF
.db $05
.db $3B
.db $FF
.db $06
.db $3C
.db $FF
.db $07
.db $3D
.db $FF
.db $02
.db $2D
.db $FF
.db $02
.db $2B
.db $FF
.db $03
.db $2E
.db $FF
.db $04
.db $2F
.db $FF
.db $05
.db $30
.db $FF
.db $02
.db $35
.db $0F
.db $0B
.db $38
.db $FF
.db $02
.db $14
.db $FF
.db $02
.db $09
.db $FF
.db $02
.db $2C
.db $FF
.db $02
.db $31
.db $15
.db $06
.db $36
.db $17
.db $0B
.db $37
.db $07
.db $03
.db $34
.db $08
.db $03
.db $34
.db $FF
.db $02
.db $32
.db $04
.db $0E
.db $33
.db $FF
.db $03
.db $10
.db $FF
.db $02
.db $13
.db $06
.db $06
.db $22
.db $FF
.db $02
.db $24
.db $FF
.db $02
.db $1E

L0DB61B:
.dw L0DB697
.dw L0DB6AA
.dw L0DB6B4
.dw L0DB6BE
.dw L0DB6C8
.dw L0DB6D2
.dw L0DB6E0
.dw L0DB6EC
.dw L0DB6EC
.dw L0DB6F6
.dw L0DB700
.dw L0DB70A
.dw L0DB714
.dw L0DB71E
.dw L0DB728
.dw L0DB732
.dw L0DB73C
.dw L0DB746
.dw L0DB755
.dw L0DB75E
.dw L0DB76D
.dw L0DB777
.dw L0DB781
.dw L0DB78B
.dw L0DB795
.dw L0DB79F
.dw L0DB7A9
.dw L0DB7B3
.dw L0DB7BD
.dw L0DB7C7
.dw L0DB7D1
.dw L0DB7DE
.dw L0DB7E8
.dw L0DB7F2
.dw L0DB7FB
.dw L0DB801
.dw L0DB808
.dw L0DB825
.dw L0DB83C
.dw L0DB85C
.dw L0DB864
.dw L0DB87A
.dw L0DB883
.dw L0DB88C
.dw L0DB896
.dw L0DB8A2
.dw L0DB8AC
.dw L0DB8BD
.dw L0DB8CE
.dw L0DB8DB
.dw L0DB8E3
.dw L0DB8EB
.dw L0DB8F5
.dw L0DB902
.dw L0DB90D
.dw L0DB91E
.dw L0DB924
.dw L0DB92A
.dw L0DB933
.dw L0DB93C
.dw L0DB94D
.dw L0DB95E


L0DB697:
.db $01 $13 $91 $11 $D1 $13 $D1 $11
.db $D2 $13 $D2 $A0 $11 $00 $02 $30
.db $00 $00 $EF

L0DB6AA:
.db $06 $30 $07 $70 $05 $60 $A0 $01
.db $00 $EF

L0DB6B4:
.db $03 $30 $0B $70 $06 $60 $A0 $02
.db $00 $EF

L0DB6BE:
.db $04 $30 $0A $70 $07 $60 $A0 $03
.db $00 $EF

L0DB6C8:
.db $05 $30 $09 $70 $08 $60 $A0 $04
.db $00 $EF

L0DB6D2:
.db $02 $30 $0C $70 $09 $60 $A0 $05
.db $A0 $59 $A0 $5A $00 $EF

L0DB6E0:
.db $02 $30 $10 $70 $0B $60 $A0 $06
.db $A0 $18 $00 $EF

L0DB6EC:
.db $03 $30 $0F $70 $0C $60 $A0 $08
.db $00 $EF

L0DB6F6:
.db $02 $30 $3F $70 $14 $60 $A0 $09
.db $00 $EF

L0DB700:
.db $03 $30 $13 $70 $0F $60 $A0 $0A
.db $00 $EF

L0DB70A:
.db $04 $30 $14 $70 $10 $60 $A0 $0B
.db $00 $EF

L0DB714:
.db $05 $30 $15 $70 $0D $60 $A0 $0C
.db $00 $EF

L0DB71E:
.db $02 $30 $1A $70 $11 $60 $A0 $0D
.db $00 $EF

L0DB728:
.db $03 $30 $1B $70 $15 $60 $A0 $0E
.db $00 $EF

L0DB732:
.db $04 $30 $1D $70 $12 $60 $A0 $0F
.db $00 $EF

L0DB73C:
.db $03 $30 $11 $A0 $10 $A0 $4D $E1
.db $00 $EF

L0DB746:
.db $02 $30 $06 $A0 $13 $00 $06 $60
.db $81 $00 $05 $60 $83 $00 $EF

L0DB755:
.db $01 $13 $92 $30 $12 $A0 $14 $00
.db $EF

L0DB75E:
.db $01 $30 $21 $13 $D5 $01 $30 $16
.db $A0 $16 $A0 $2B $E2 $00 $EF

L0DB76D:
.db $02 $30 $17 $70 $0E $60 $A0 $17
.db $00 $EF

L0DB777:
.db $04 $30 $3E $A0 $1A $70 $1B $60
.db $00 $EF

L0DB781:
.db $04 $30 $24 $A0 $19 $70 $16 $60
.db $00 $EF

L0DB78B:
.db $02 $30 $26 $A0 $2C $70 $17 $60
.db $00 $EF

L0DB795:
.db $03 $30 $27 $A0 $34 $70 $1A $60
.db $00 $EF

L0DB79F:
.db $04 $30 $28 $A0 $33 $70 $19 $60
.db $00 $EF

L0DB7A9:
.db $02 $30 $2A $A0 $1E $70 $21 $60
.db $00 $EF

L0DB7B3:
.db $06 $30 $41 $A0 $20 $70 $1C $60
.db $00 $EF

L0DB7BD:
.db $02 $30 $44 $A0 $21 $70 $13 $60
.db $00 $EF

L0DB7C7:
.db $03 $30 $46 $A0 $22 $70 $1D $60
.db $00 $EF

L0DB7D1:
.db $02 $30 $47 $13 $2A $60 $A0 $24
.db $A0 $23 $60 $00 $EF

L0DB7DE:
.db $02 $30 $2B $A0 $26 $70 $20 $60
.db $00 $EF

L0DB7E8:
.db $03 $30 $29 $A0 $27 $70 $1F $60
.db $00 $EF

L0DB7F2:
.db $02 $30 $20 $A0 $28 $A0 $15 $00
.db $EF

L0DB7FB:
.db $01 $93 $A0 $29 $00 $EF

L0DB801:
.db $02 $60 $82 $A0 $12 $00 $EF

L0DB808:
.db $02 $30 $2D $30 $2E $12 $D2 $03
.db $C0 $00 $00 $50 $17 $41 $50 $00
.db $50 $02 $A0 $2F $A0 $30 $14 $D2
.db $13 $30 $2F $00 $EF

L0DB825:
.db $01 $11 $D3 $00 $05 $30 $4D $11
.db $03 $13 $30 $4E $30 $53 $42 $A0
.db $2D $A0 $2E $A0 $3A $00 $EF

L0DB83C:
.db $02 $30 $51 $12 $D2 $03 $C0 $00
.db $00 $50 $17 $41 $50 $00 $50 $11
.db $A0 $31 $A0 $39 $A0 $3F $A0 $5B
.db $14 $D2 $13 $30 $52 $E3 $00 $EF

L0DB85C:
.db $01 $94 $A0 $32 $A0 $5C $00 $EF

L0DB864:
.db $03 $50 $00 $50 $17 $43 $50 $00
.db $50 $11 $14 $2F $11 $30 $55 $12
.db $2F $60 $A0 $35 $00 $EF

L0DB87A:
.db $07 $F0 $12 $D7 $60 $A0 $3D $00
.db $EF

L0DB883:
.db $05 $F0 $12 $D7 $60 $A0 $3E $00
.db $EF

L0DB88C:
.db $02 $30 $57 $70 $1E $A0 $1F $60
.db $00 $EF

L0DB896:
.db $02 $30 $59 $70 $04 $A0 $40 $A0
.db $41 $60 $00 $EF

L0DB8A2:
.db $02 $30 $58 $70 $22 $A0 $36 $60
.db $00 $EF

L0DB8AC:
.db $03 $F0 $13 $22 $12 $21 $13 $26
.db $12 $22 $13 $21 $60 $A0 $45 $00
.db $EF

L0DB8BD:
.db $04 $F0 $13 $22 $14 $21 $13 $26
.db $12 $22 $13 $21 $60 $A0 $46 $00
.db $EF

L0DB8CE:
.db $05 $F0 $13 $27 $12 $22 $13 $21
.db $60 $A0 $47 $00 $EF

L0DB8DB:
.db $02 $A0 $49 $A0 $50 $45 $00 $EF

L0DB8E3:
.db $02 $30 $0E $A0 $4A $44 $00 $EF

L0DB8EB:
.db $02 $30 $63 $11 $D2 $60 $A0 $4B
.db $00 $EF

L0DB8F5:
.db $01 $50 $17 $47 $46 $50 $00 $50
.db $1A $A0 $4C $00 $EF

L0DB902:
.db $02 $30 $64 $70 $03 $60 $A0 $4E
.db $E4 $00 $EF

L0DB90D:
.db $01 $11 $30 $68 $00 $03 $13 $23
.db $14 $25 $13 $30 $62 $A0 $51 $00
.db $EF

L0DB91E:
.db $01 $A0 $52 $48 $00 $EF

L0DB924:
.db $01 $95 $A0 $53 $00 $EF

L0DB92A:
.db $02 $30 $6C $49 $40 $A0 $54 $00
.db $EF

L0DB933:
.db $04 $30 $6B $4A $60 $A0 $55 $00
.db $EF

L0DB93C:
.db $05 $F0 $13 $21 $12 $21 $13 $23
.db $14 $2B $13 $26 $60 $A0 $56 $00
.db $EF

L0DB94D:
.db $06 $F0 $13 $21 $14 $21 $13 $23
.db $14 $2B $13 $26 $60 $A0 $57 $00
.db $EF

L0DB95E:
.db $07 $F0 $13 $23 $14 $2B $13 $26
.db $60 $A0 $58 $00 $EF

L0DB96B:
.dw L0DB971
.dw L0DB97A
.dw L0DB983

L0DB971:
.db $08 $10 $02 $06 $10 $18 $07 $04
.db $00

L0DB97A:
.db $02 $06 $02 $06 $10 $18 $03 $03
.db $00

L0DB983:
.db $08 $15 $02 $06 $10 $18 $0E $04
.db $00

L0DB98C:
.db $01
.db $02
.db $21
.db $04
.db $05
.db $06
.db $07
.db $4E
.db $09
.db $0A
.db $4F
.db $0C
.db $0D
.db $50
.db $0F
.db $10
.db $11
.db $51
.db $13
.db $14
.db $15
.db $52
.db $17
.db $53
.db $19
.db $1A
.db $1C
.db $1C
.db $1D
.db $1E
.db $01
.db $55

L0DB9AC:
.db $01
.db $02
.db $03
.db $04
.db $05
.db $06
.db $07
.db $08
.db $09
.db $0A
.db $0B
.db $0C
.db $0D
.db $0E
.db $0F
.db $10
.db $11
.db $12
.db $13
.db $14
.db $15
.db $16
.db $17
.db $18
.db $19
.db $1A
.db $00
.db $1B
.db $1D
.db $1E
.db $01
.db $01
.db $03
.db $08
.db $0B
.db $0E
.db $12
.db $00
.db $16
.db $18
.db $00
.db $1B
.db $00
.db $00
.db $00
.db $01
.db $01
.db $03
.db $08
.db $0B
.db $0E
.db $12
.db $00
.db $1B
.db $18
.db $1B
.db $20
.db $00
.db $00
.db $00
.db $01
.db $01
.db $03
.db $08
.db $0B
.db $0E
.db $12
.db $00
.db $16
.db $18
.db $1B
.db $20
.db $00
.db $00
.db $00
.db $01
.db $01
.db $08
.db $0B
.db $0E
.db $12
.db $16
.db $18
.db $1B
.db $20
L0DBA01:
.db $32
L0DBA02:
.db $00
L0DBA03:
.db $01
.db $33
.db $01
.db $01
.db $34
.db $02
.db $01
.db $35
.db $03
.db $01
.db $2E
.db $04
.db $01
.db $38
.db $06
.db $01
.db $39
.db $07
.db $01
.db $3B
.db $09
.db $01
.db $2F
.db $0A
.db $02
.db $44
.db $0B
.db $02
.db $45
.db $0D
.db $04
.db $46
.db $0E
.db $08
.db $48
.db $0F
.db $10
.db $4A
.db $11
.db $20
.db $3C
.db $13
.db $01
.db $3D
.db $14
.db $02
.db $3E
.db $15
.db $04
.db $61
.db $17
.db $01
.db $5E
.db $18
.db $02
.db $5C
.db $19
.db $04
.db $69
.db $1A
.db $08
.db $6A
.db $1B
.db $10
.db $6E
.db $1C
.db $20
.db $4C
.db $1D
.db $01
.db $64
.db $1E
.db $02
.db $76
.db $1F
.db $04
.db $EF
L0DBA50:
.db $3A
L0DBA51:
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3B
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $41
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $52
.db $BB
.db $4C
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $58
.db $BB
.db $C2
.db $BB
.db $28
.db $BC
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $EB
.db $BB
.db $7A
.db $BC
.db $3A
.db $BB
.db $C8
.db $BB
.db $F1
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $89
.db $BB
.db $8F
.db $BB
.db $95
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $DF
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $77
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $9B
.db $BB
.db $A6
.db $BB
.db $B1
.db $BB
.db $BC
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $83
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $CE
.db $BB
.db $D4
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $E5
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $A7
.db $BC
.db $01
.db $BC
.db $BC
.db $BC
.db $0C
.db $BC
.db $33
.db $BC
.db $D1
.db $BC
.db $17
.db $BC
.db $FB
.db $BC
.db $E6
.db $BC
.db $3A
.db $BB
.db $33
.db $BD
.db $3A
.db $BB
.db $80
.db $BC
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $86
.db $BC
.db $91
.db $BC
.db $9C
.db $BC
.db $22
.db $BC
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $3A
.db $BB
.db $7D
.db $BB
.db $EF
.db $01
.db $03
.db $2C
.db $0D
.db $03
.db $EF
.db $0B
.db $02
.db $2D
.db $11
.db $0A
.db $0A
.db $13
.db $37
.db $08
.db $07
.db $EF
.db $06
.db $0B
.db $19
.db $07
.db $07
.db $EF
.db $07
.db $07
.db $1A
.db $06
.db $0B
.db $EF
.db $14
.db $0F
.db $3C
.db $0C
.db $07
.db $10
.db $0F
.db $3C
.db $03
.db $07
.db $0E
.db $18
.db $3D
.db $0C
.db $07
.db $0A
.db $18
.db $3D
.db $03
.db $07
.db $09
.db $09
.db $3E
.db $0C
.db $07
.db $05
.db $09
.db $3E
.db $03
.db $07
.db $EF
.db $09
.db $07
.db $0F
.db $0A
.db $13
.db $EF
.db $05
.db $0B
.db $43
.db $0B
.db $07
.db $EF
.db $0A
.db $07
.db $75
.db $05
.db $0B
.db $EF
.db $01
.db $0E
.db $25
.db $0E
.db $08
.db $EF
.db $0D
.db $03
.db $04
.db $02
.db $03
.db $EF
.db $10
.db $0A
.db $0F
.db $0B
.db $02
.db $EF
.db $0C
.db $07
.db $1D
.db $15
.db $0F
.db $02
.db $07
.db $1D
.db $10
.db $0F
.db $EF
.db $0C
.db $07
.db $1D
.db $0F
.db $18
.db $02
.db $07
.db $1D
.db $0A
.db $18
.db $EF
.db $0C
.db $07
.db $1D
.db $0A
.db $09
.db $02
.db $07
.db $1D
.db $05
.db $09
.db $EF
.db $05
.db $0B
.db $41
.db $05
.db $04
.db $EF
.db $0F
.db $13
.db $56
.db $04
.db $06
.db $EF
.db $04
.db $07
.db $75
.db $08
.db $0A
.db $EF
.db $08
.db $07
.db $4B
.db $03
.db $04
.db $EF
.db $02
.db $04
.db $4A
.db $08
.db $07
.db $0B
.db $03
.db $31
.db $02
.db $07
.db $EF
.db $01
.db $07
.db $4B
.db $0B
.db $03
.db $EF
.db $03
.db $06
.db $1E
.db $0F
.db $13
.db $EF
.db $0F
.db $0A
.db $28
.db $0E
.db $0A
.db $EF
.db $03
.db $05
.db $5C
.db $04
.db $05
.db $0F
.db $0D
.db $6B
.db $10
.db $12
.db $0D
.db $0A
.db $24
.db $0E
.db $0A
.db $EF
.db $03
.db $05
.db $28
.db $03
.db $05
.db $0A
.db $07
.db $5E
.db $03
.db $0B
.db $EF
.db $02
.db $0B
.db $5C
.db $0A
.db $07
.db $06
.db $0B
.db $61
.db $03
.db $0B
.db $EF
.db $02
.db $0B
.db $5E
.db $06
.db $0B
.db $06
.db $0B
.db $1F
.db $03
.db $0B
.db $EF
.db $09
.db $0B
.db $1F
.db $07
.db $0B
.db $EF
.db $02
.db $0B
.db $61
.db $06
.db $0B
.db $09
.db $0B
.db $6E
.db $0A
.db $0B
.db $EF
.db $0E
.db $08
.db $25
.db $1B
.db $06
.db $12
.db $08
.db $62
.db $0F
.db $08
.db $06
.db $07
.db $62
.db $06
.db $07
.db $06
.db $08
.db $62
.db $06
.db $08
.db $06
.db $09
.db $62
.db $06
.db $09
.db $07
.db $06
.db $62
.db $07
.db $06
.db $07
.db $0A
.db $62
.db $07
.db $0A
.db $08
.db $06
.db $62
.db $08
.db $06
.db $08
.db $0A
.db $62
.db $08
.db $0A
.db $09
.db $06
.db $62
.db $09
.db $06
.db $09
.db $0A
.db $62
.db $09
.db $0A
.db $0A
.db $07
.db $62
.db $0A
.db $07
.db $0A
.db $08
.db $62
.db $0A
.db $08
.db $0A
.db $09
.db $62
.db $0A
.db $09
.db $EF
.db $1B
.db $06
.db $5F
.db $0F
.db $08
.db $EF
.db $0F
.db $12
.db $6D
.db $13
.db $12
.db $EF
.db $0F
.db $12
.db $28
.db $0F
.db $0D
.db $13
.db $12
.db $6C
.db $10
.db $12
.db $EF
.db $0F
.db $12
.db $6B
.db $13
.db $12
.db $13
.db $12
.db $6D
.db $10
.db $12
.db $EF
.db $0F
.db $12
.db $6C
.db $13
.db $12
.db $13
.db $12
.db $67
.db $10
.db $12
.db $EF
.db $0F
.db $0D
.db $5D
.db $06
.db $04
.db $0F
.db $11
.db $5D
.db $06
.db $08
.db $12
.db $0D
.db $5D
.db $09
.db $04
.db $12
.db $11
.db $5D
.db $09
.db $08
.db $EF
.db $06
.db $04
.db $60
.db $06
.db $04
.db $06
.db $08
.db $60
.db $06
.db $08
.db $09
.db $04
.db $60
.db $09
.db $04
.db $09
.db $08
.db $60
.db $09
.db $08
.db $EF
.db $06
.db $04
.db $63
.db $06
.db $04
.db $06
.db $08
.db $63
.db $06
.db $08
.db $09
.db $04
.db $63
.db $09
.db $04
.db $09
.db $08
.db $63
.db $09
.db $08
.db $EF
.db $06
.db $04
.db $66
.db $06
.db $04
.db $06
.db $08
.db $66
.db $06
.db $08
.db $09
.db $04
.db $66
.db $09
.db $04
.db $09
.db $08
.db $66
.db $09
.db $08
.db $EF
.db $12
.db $08
.db $65
.db $12
.db $08
.db $0E
.db $08
.db $5F
.db $12
.db $08
.db $07
.db $06
.db $65
.db $07
.db $06
.db $07
.db $0A
.db $65
.db $07
.db $0A
.db $08
.db $06
.db $65
.db $08
.db $06
.db $08
.db $0A
.db $65
.db $08
.db $0A
.db $09
.db $06
.db $65
.db $09
.db $06
.db $09
.db $0A
.db $65
.db $09
.db $0A
.db $0A
.db $07
.db $65
.db $0A
.db $07
.db $0A
.db $08
.db $65
.db $0A
.db $08
.db $0A
.db $09
.db $65
.db $0A
.db $09
.db $EF
.db $12
.db $08
.db $62
.db $12
.db $08
.db $06
.db $07
.db $68
.db $06
.db $07
.db $06
.db $08
.db $68
.db $06
.db $08
.db $06
.db $09
.db $68
.db $06
.db $09
.db $07
.db $06
.db $68
.db $07
.db $06
.db $07
.db $0A
.db $68
.db $07
.db $0A
.db $08
.db $06
.db $68
.db $08
.db $06
.db $08
.db $0A
.db $68
.db $08
.db $0A
.db $09
.db $06
.db $68
.db $09
.db $06
.db $0A
.db $07
.db $68
.db $0A
.db $07
.db $0A
.db $08
.db $68
.db $0A
.db $08
.db $0A
.db $09
.db $68
.db $0A
.db $09
.db $EF
L0DBD70:
.db $D4
L0DBD71:
.db $BD
.db $D5
.db $BD
.db $DA
.db $BD
.db $E3
.db $BD
.db $E8
.db $BD
.db $D4
.db $BD
.db $F1
.db $BD
.db $F6
.db $BD
.db $FF
.db $BD
.db $D4
.db $BD
.db $08
.db $BE
.db $11
.db $BE
.db $D4
.db $BD
.db $16
.db $BE
.db $1F
.db $BE
.db $28
.db $BE
.db $2D
.db $BE
.db $32
.db $BE
.db $3B
.db $BE
.db $40
.db $BE
.db $D4
.db $BD
.db $45
.db $BE
.db $D4
.db $BD
.db $4E
.db $BE
.db $57
.db $BE
.db $D4
.db $BD
.db $5C
.db $BE
.db $D4
.db $BD
.db $61
.db $BE
.db $D4
.db $BD
.db $83
.db $BE
.db $7A
.db $BE
.db $D4
.db $BD
.db $D4
.db $BD
.db $88
.db $BE
.db $8D
.db $BE
.db $D4
.db $BD
.db $92
.db $BE
.db $9B
.db $BE
.db $A0
.db $BE
.db $D4
.db $BD
.db $A5
.db $BE
.db $D4
.db $BD
.db $D4
.db $BD
.db $AA
.db $BE
.db $D4
.db $BD
.db $B7
.db $BE
.db $BC
.db $BE
.db $CD
.db $BE
.db $D4
.db $BD
.db $EF
.db $03
.db $12
.db $00
.db $0F
.db $EF
.db $02
.db $07
.db $01
.db $00
.db $02
.db $0F
.db $01
.db $01
.db $EF
.db $11
.db $0F
.db $00
.db $06
.db $EF
.db $03
.db $03
.db $01
.db $02
.db $03
.db $0C
.db $01
.db $03
.db $EF
.db $03
.db $0F
.db $00
.db $0B
.db $EF
.db $02
.db $07
.db $01
.db $04
.db $02
.db $0F
.db $01
.db $05
.db $EF
.db $01
.db $03
.db $04
.db $00
.db $0D
.db $03
.db $04
.db $00
.db $EF
.db $02
.db $07
.db $01
.db $08
.db $02
.db $0F
.db $01
.db $09
.db $EF
.db $03
.db $0C
.db $00
.db $02
.db $EF
.db $02
.db $07
.db $01
.db $0A
.db $02
.db $0F
.db $01
.db $0B
.db $EF
.db $01
.db $0B
.db $06
.db $00
.db $0B
.db $14
.db $00
.db $39
.db $EF
.db $04
.db $06
.db $00
.db $05
.db $EF
.db $04
.db $0D
.db $00
.db $12
.db $EF
.db $02
.db $07
.db $01
.db $0C
.db $02
.db $0F
.db $01
.db $0D
.db $EF
.db $01
.db $07
.db $03
.db $00
.db $EF
.db $05
.db $08
.db $01
.db $12
.db $EF
.db $02
.db $07
.db $01
.db $0E
.db $02
.db $0F
.db $01
.db $0F
.db $EF
.db $02
.db $07
.db $01
.db $10
.db $02
.db $0F
.db $01
.db $11
.db $EF
.db $05
.db $07
.db $02
.db $70
.db $EF
.db $07
.db $07
.db $00
.db $03
.db $EF
.db $14
.db $06
.db $01
.db $14
.db $14
.db $18
.db $01
.db $15
.db $08
.db $04
.db $01
.db $16
.db $04
.db $18
.db $01
.db $17
.db $02
.db $0A
.db $01
.db $18
.db $02
.db $13
.db $01
.db $19
.db $EF
.db $02
.db $07
.db $01
.db $06
.db $02
.db $0F
.db $01
.db $07
.db $EF
.db $04
.db $0C
.db $02
.db $4C
.db $EF
.db $07
.db $07
.db $00
.db $16
.db $EF
.db $06
.db $15
.db $00
.db $07
.db $EF
.db $02
.db $07
.db $01
.db $1C
.db $02
.db $0F
.db $01
.db $1D
.db $EF
.db $03
.db $07
.db $00
.db $38
.db $EF
.db $02
.db $07
.db $00
.db $11
.db $EF
.db $07
.db $07
.db $00
.db $0C
.db $EF
.db $01
.db $07
.db $03
.db $00
.db $0D
.db $03
.db $01
.db $1A
.db $0D
.db $0C
.db $01
.db $1B
.db $EF
.db $0B
.db $04
.db $00
.db $10
.db $EF
.db $03
.db $03
.db $00
.db $15
.db $03
.db $0F
.db $00
.db $32
.db $03
.db $11
.db $00
.db $33
.db $05
.db $12
.db $02
.db $35
.db $EF
.db $08
.db $07
.db $00
.db $34
.db $EF
L0DBED2:
.db $00
.db $01
.db $01
.db $03
.db $04
.db $05
.db $03
.db $05
.db $07
.db $07
.db $02
.db $05
.db $05
.db $06
.db $03
.db $02
.db $07
.db $00
.db $00
.db $01
.db $02
.db $03
.db $04
.db $05
.db $00
.db $01
.db $01
.db $06
.db $07
.db $07
L0DBEF0:
.db $F8
L0DBEF1:
.db $BE
.db $FB
.db $BE
.db $FE
.db $BE
.db $01
.db $BF
.db $05
.db $10
.db $07
.db $2C
.db $06
.db $06
.db $13
.db $0A
.db $08
.db $1E
.db $0F
.db $0B
.db $80
.db $03
.db $00
.db $08
.db $B4
.db $29
.db $02
.db $1B
.db $7F
.db $82
.db $E6
.db $63
.db $00
.db $00
.db $08
.db $01
.db $08
.db $00
.db $00
.db $39
.db $0F
.db $CA
.db $B7
.db $0B
.db $80
.db $80
.db $00
.db $14
.db $10
.db $00
.db $08
.db $80
.db $00
.db $40
.db $00
.db $60
.db $05
.db $90
.db $B2
.db $FE
.db $BD
.db $EF
.db $5F
.db $04
.db $00
.db $01
.db $13
.db $45
.db $08
.db $80
.db $01
.db $00
.db $9F
.db $D5
.db $47
.db $34
.db $54
.db $B7
.db $12
.db $0C
.db $02
.db $00
.db $00
.db $00
.db $03
.db $00
.db $00
.db $80
.db $C7
.db $ED
.db $C7
.db $91
.db $3C
.db $08
.db $07
.db $6E
.db $89
.db $80
.db $00
.db $05
.db $03
.db $00
.db $20
.db $82
.db $EF
.db $D3
.db $EC
.db $7D
.db $8D
.db $54
.db $C7
.db $34
.db $82
.db $00
.db $20
.db $0D
.db $00
.db $04
.db $08
.db $10
.db $6C
.db $19
.db $0E
.db $BB
.db $B2
.db $F0
.db $08
.db $67
.db $88
.db $40
.db $92
.db $00
.db $09
.db $80
.db $00
.db $40
.db $10
.db $E5
.db $17
.db $16
.db $5A
.db $55
.db $46
.db $54
.db $08
.db $00
.db $32
.db $41
.db $00
.db $91
.db $00
.db $20
.db $F7
.db $FC
.db $6B
.db $63
.db $4A
.db $86
.db $43
.db $F4
.db $11
.db $00
.db $00
.db $60
.db $00
.db $28
.db $40
.db $C1
.db $16
.db $C3
.db $E8
.db $21
.db $79
.db $17
.db $BD
.db $44
.db $00
.db $85
.db $B5
.db $85
.db $FE
.db $8F
.db $0C
.db $8C
.db $5B
.db $9A
.db $D6
.db $99
.db $FB
.db $AC
.db $8A
.db $91
.db $00
.db $00
.db $00
.db $06
.db $00
.db $0B
.db $18
.db $24
.db $DD
.db $D4
.db $D1
.db $85
.db $3B
.db $9A
.db $69
.db $5C
.db $2A
.db $92
.db $01
.db $00
.db $2C
.db $20
.db $00
.db $20
.db $A7
.db $33
.db $EA
.db $C7
.db $D7
.db $90
.db $5A
.db $B5
.db $00
.db $84
.db $00
.db $59
.db $00
.db $08
.db $01
.db $00
.db $29
.db $6D
.db $37
.db $D5
.db $09
.db $C0
.db $1C
.db $27
.db $22
.db $00
.db $00
.db $00
.db $00
.db $00
.db $80
.db $A2
.db $0F
.db $4F
.db $F9
.db $EF
.db $2A
.db $69
.db $C6
.db $F4
.db $80
.db $00
.db $00
.db $00
.db $00
.db $00
.db $20
.db $FF
.db $55
.db $69
.db $05
.db $00
.db $53
.db $44
.db $05
.db $FF

.ENDS
