.BANK 8
.ORG $0000

.SECTION "Bank7" FORCE

.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $2E
.db $2F
.db $2E
.db $2F
.db $3F
.db $3F
.db $3E
.db $3E
.db $2E
.db $2B
.db $3C
.db $3E
.db $2A
.db $2F
.db $3E
.db $3D
.db $2C
.db $3F
.db $2E
.db $3B
.db $3F
.db $2D
.db $3A
.db $2F
.db $95
.db $96
.db $A5
.db $A6
.db $45
.db $44
.db $46
.db $46
.db $46
.db $46
.db $55
.db $54
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $ED
.db $ED
.db $C0
.db $C2
.db $ED
.db $ED
.db $C2
.db $C1
.db $B0
.db $B2
.db $ED
.db $ED
.db $B2
.db $B1
.db $ED
.db $ED
.db $81
.db $58
.db $58
.db $FE
.db $66
.db $80
.db $FE
.db $66
.db $FE
.db $91
.db $4E
.db $80
.db $92
.db $FE
.db $81
.db $4F
.db $70
.db $71
.db $80
.db $81
.db $B3
.db $81
.db $B4
.db $B5
.db $C4
.db $C5
.db $B6
.db $B7
.db $4E
.db $4F
.db $5E
.db $5F
.db $6E
.db $6F
.db $7E
.db $7F
.db $70
.db $71
.db $81
.db $80
.db $5E
.db $5F
.db $8E
.db $8F
.db $7E
.db $7F
.db $6E
.db $6F
.db $FE
.db $4E
.db $FE
.db $5E
.db $4F
.db $FE
.db $5F
.db $FE
.db $FE
.db $6E
.db $FE
.db $7E
.db $6F
.db $FE
.db $7F
.db $FE
.db $FE
.db $5E
.db $FE
.db $8E
.db $5F
.db $FE
.db $8F
.db $FE
.db $FE
.db $7E
.db $FE
.db $6E
.db $7F
.db $FE
.db $6F
.db $FE
.db $71
.db $DB
.db $EA
.db $EB
.db $C6
.db $C7
.db $D6
.db $D7
.db $BC
.db $70
.db $CC
.db $CD
.db $00
.db $00
.db $00
.db $00
.db $92
.db $93
.db $A2
.db $A3
.db $FE
.db $FE
.db $A4
.db $FE
.db $E3
.db $E2
.db $D3
.db $D2
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $71
.db $70
.db $80
.db $81
.db $80
.db $81
.db $71
.db $70
.db $81
.db $80
.db $58
.db $66
.db $92
.db $91
.db $71
.db $70
.db $6E
.db $80
.db $7E
.db $80
.db $81
.db $6F
.db $81
.db $7F
.db $4E
.db $80
.db $5E
.db $80
.db $81
.db $4F
.db $81
.db $5F
.db $7E
.db $81
.db $6E
.db $81
.db $80
.db $7F
.db $80
.db $6F
.db $5E
.db $80
.db $8E
.db $80
.db $70
.db $5F
.db $70
.db $8F
.db $90
.db $93
.db $A0
.db $A3
.db $92
.db $91
.db $A2
.db $A1
.db $91
.db $92
.db $A1
.db $A2
.db $93
.db $FE
.db $A3
.db $A4
.db $92
.db $91
.db $80
.db $81
.db $91
.db $92
.db $80
.db $81
.db $70
.db $71
.db $A2
.db $A1
.db $70
.db $71
.db $A1
.db $A2
.db $A0
.db $A3
.db $FE
.db $FE
.db $A2
.db $A1
.db $FE
.db $FE
.db $A1
.db $A2
.db $FE
.db $FE
.db $A3
.db $A4
.db $FE
.db $FE
.db $FE
.db $FE
.db $90
.db $93
.db $FE
.db $FE
.db $92
.db $91
.db $FE
.db $FE
.db $91
.db $92
.db $FE
.db $FE
.db $93
.db $FE
.db $9C
.db $9D
.db $AC
.db $AD
.db $B0
.db $B1
.db $C0
.db $C1
.db $FE
.db $5E
.db $FE
.db $5E
.db $5F
.db $FE
.db $5F
.db $FE
.db $68
.db $25
.db $6C
.db $35
.db $26
.db $69
.db $36
.db $6D
.db $76
.db $25
.db $86
.db $35
.db $26
.db $77
.db $36
.db $86
.db $64
.db $11
.db $20
.db $21
.db $12
.db $65
.db $22
.db $23
.db $72
.db $73
.db $82
.db $83
.db $74
.db $75
.db $84
.db $85
.db $04
.db $05
.db $14
.db $15
.db $06
.db $07
.db $16
.db $17
.db $27
.db $25
.db $37
.db $35
.db $26
.db $27
.db $36
.db $37
.db $08
.db $09
.db $18
.db $19
.db $D4
.db $D5
.db $E4
.db $E5
.db $FE
.db $31
.db $40
.db $41
.db $32
.db $FE
.db $42
.db $43
.db $50
.db $51
.db $60
.db $61
.db $52
.db $53
.db $62
.db $63
.db $FE
.db $7A
.db $9B
.db $8A
.db $7B
.db $FE
.db $8B
.db $24
.db $FE
.db $FE
.db $FE
.db $6A
.db $FE
.db $FE
.db $6B
.db $FE
.db $FE
.db $FE
.db $FE
.db $01
.db $FE
.db $FE
.db $02
.db $FE
.db $78
.db $79
.db $88
.db $89
.db $00
.db $03
.db $FE
.db $56
.db $30
.db $34
.db $59
.db $FE
.db $5C
.db $25
.db $6C
.db $35
.db $48
.db $5D
.db $36
.db $6D
.db $BA
.db $BB
.db $CA
.db $CB
.db $9E
.db $9E
.db $9E
.db $9E
.db $7C
.db $FE
.db $8C
.db $8D
.db $10
.db $11
.db $20
.db $21
.db $12
.db $13
.db $22
.db $23
.db $0A
.db $0B
.db $1A
.db $1B
.db $D0
.db $D1
.db $E0
.db $E1
.db $FE
.db $4A
.db $4A
.db $39
.db $4B
.db $FE
.db $39
.db $4B
.db $39
.db $39
.db $39
.db $39
.db $FE
.db $4A
.db $FE
.db $5A
.db $4B
.db $FE
.db $5B
.db $FE
.db $FE
.db $FE
.db $4A
.db $4B
.db $5A
.db $5B
.db $FE
.db $FE
.db $39
.db $5B
.db $5B
.db $FE
.db $5A
.db $39
.db $FE
.db $5A
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $2E
.db $2F
.db $2E
.db $2F
.db $3F
.db $3F
.db $3E
.db $3E
.db $2E
.db $2B
.db $3C
.db $3E
.db $2A
.db $2F
.db $3E
.db $3D
.db $2C
.db $3F
.db $2E
.db $3B
.db $3F
.db $2D
.db $3A
.db $2F
.db $95
.db $96
.db $A5
.db $A6
.db $4B
.db $4A
.db $39
.db $39
.db $39
.db $39
.db $5B
.db $5A
.db $00
.db $00
.db $00
.db $00
.db $0C
.db $0D
.db $0F
.db $1F
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $FF
.db $FF
.db $FF
.db $FF
.db $00
.db $00
.db $00
.db $00
.db $FE
.db $FE
.db $FE
.db $FE
.db $95
.db $97
.db $A5
.db $A7
.db $97
.db $96
.db $A7
.db $A6
.db $B0
.db $B2
.db $C0
.db $C2
.db $B2
.db $B1
.db $C2
.db $C1
.db $44
.db $46
.db $54
.db $46
.db $46
.db $45
.db $46
.db $55
.db $4A
.db $39
.db $5A
.db $39
.db $39
.db $4B
.db $39
.db $5B
.db $4C
.db $4D
.db $4D
.db $4C
.db $33
.db $33
.db $29
.db $29
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $EF
.db $0C
.db $0C
.db $4C
.db $0D
.db $EF
.db $4D
.db $0D
.db $1C
.db $4D
.db $EF
.db $1C
.db $4C
.db $1D
.db $1D
.db $EF
.db $0E
.db $0E
.db $4D
.db $4C
.db $4C
.db $4D
.db $1E
.db $1E
.db $0F
.db $4D
.db $0F
.db $4C
.db $4C
.db $1F
.db $4D
.db $1F
.db $1D
.db $1C
.db $0D
.db $0C
.db $0F
.db $1F
.db $0F
.db $1F
.db $0E
.db $0E
.db $1E
.db $1E
.db $0C
.db $0E
.db $0F
.db $4C
.db $0E
.db $0D
.db $4D
.db $1F
.db $0F
.db $4D
.db $1C
.db $1E
.db $4C
.db $1F
.db $1E
.db $1D
.db $0E
.db $0D
.db $1E
.db $1D
.db $46
.db $55
.db $55
.db $FE
.db $54
.db $46
.db $FE
.db $54
.db $FE
.db $44
.db $44
.db $46
.db $45
.db $FE
.db $46
.db $45
.db $46
.db $46
.db $46
.db $46
.db $FE
.db $44
.db $FE
.db $54
.db $45
.db $FE
.db $55
.db $FE
.db $FE
.db $FE
.db $44
.db $45
.db $54
.db $55
.db $FE
.db $FE
.db $00
.db $00
.db $00
.db $00
.db $2C
.db $3F
.db $3C
.db $3E
.db $3F
.db $2D
.db $3E
.db $3D
.db $2C
.db $2D
.db $2E
.db $2F
.db $2E
.db $2F
.db $3C
.db $3D
.db $98
.db $99
.db $A8
.db $A9
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $01
.db $01
.db $01
.db $01
.db $01
.db $01
.db $01
.db $01
.db $01
.db $00
.db $00
.db $00
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $00
.db $02
.db $02
.db $02
.db $00
.db $00
.db $00
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $02
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $02
.db $02
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $02
.db $00
.db $00
.db $00
.db $00
.db $00
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $02
.db $02
.db $00
.db $03
.db $00
.db $00
.db $00
.db $00
.db $00
.db $03
.db $00
.db $01
.db $01
.db $01
.db $02
.db $02
.db $01
.db $01
.db $02
.db $02
.db $03
.db $03
.db $00
.db $00
.db $00
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $03
.db $01
.db $01
.db $01
.db $01
.db $01
.db $01
.db $01
.db $01
.db $01
.db $00
.db $01
.db $01
.db $01
.db $01
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00
.db $00

L078500:
    LDA $0499
    JSR L0FC34C.w

.dw L0FC73D
.dw L078512
.dw L078512
.dw L078512
.dw L078512
.dw L0785D8

L078512:
    LDA $27
    BNE L07854E
    LDY $0499
    DEY
    TYA
    ASL
    TAY
    LDA L07854F.w,Y
    STA $00
    LDA (L07854F.w + 1),Y
    STA $01
    LDA #7
    STA $03
    LDA #129
    STA $02
    LDA L078557.w
    STA $04
    LDA #0
    STA $05
    JSR L0FC209.w
    LDA #1
    STA $27
    INC $0499
    LDA $0499
    CMP #5
    BNE L07854E
    LDA #0
    STA $0499
L07854E:
    RTS

L07854F:
.dw L078558
.dw L078578
.dw L078598
.dw L0785B8

L078557:
.db $20 ; size of those 4 "blocks"

L078558:
.db $22 $42 $1C $F5 $F7 $F7 $F7 $F7
.db $F7 $F7 $F7 $F7 $F7 $F7 $F7 $F7
.db $F7 $F7 $F7 $F7 $F7 $F7 $F7 $F7
.db $F7 $F7 $F7 $F7 $F7 $F7 $F6 $00

L078578:
.db $22 $62 $1C $FB $FF $FF $FF $FF
.db $FF $FF $FF $FF $FF $FF $FF $FF
.db $FF $FF $FF $FF $FF $FF $FF $FF
.db $FF $FF $FF $FF $FF $FF $FC $00

L078598:
.db $22 $82 $1C $FB $FF $FF $FF $FF
.db $FF $FF $FF $FF $FF $FF $FF $FF
.db $FF $FF $FF $FF $FF $FF $FF $FF
.db $FF $FF $FF $FF $FF $FF $FC $00

L0785B8:
.db $22 $A2 $1C $F9 $F8 $F8 $F8 $F8
.db $F8 $F8 $F8 $F8 $F8 $F8 $F8 $F8
.db $F8 $F8 $F8 $F8 $F8 $F8 $F8 $F8
.db $F8 $F8 $F8 $F8 $F8 $F8 $FA $00

L0785D8:
    LDA $0498
    JSR L0FC34C.w

.dw L0787AE
.dw L0786EE
.dw L0785F8
.dw L0786AE
.dw L078725
.dw L078732
.dw L0786BE
.dw L0786CE
.dw L078706
.dw L0786A0
.dw L078769
.dw L0786F6
.dw L0786FE

L0785F8:
    LDX #0
    LDA $047C
    BNE L078616
    LDA $049A
    BEQ L078616
    BPL L078609
    JMP L078685.w

L078609:
    LDY #9
L07860B:
    LDA L07889F.w,Y
    STA $7DC3,Y
    DEY
    BPL L07860B
    LDX #10
L078616:
    LDA $047C
    BEQ L07863E
    LDA $0304
    STA $0384
    LDA $0305
    STA $0304
    JSR L0789B4.w
    LDA $0384
    STA $0304
    LDA #10
    JSR L07883A.w
    JSR L07882A.w
    DEX
    LDA $049B
    BPL L078643
L07863E:
    LDA $049B
    BEQ L07867B
L078643:
    JSR L078648.w
    BEQ L07866C
L078648:
    STA $00
    LDA #0
    STA $01
    LDA #68
    STA $08
    LDA #4
    STA $09
    JSR L0FC7BA.w
    LDY #0
L07865B:
    LDA $0446,Y
    CMP #255
    BEQ L078666
    STA $7DC3,X
    INX
L078666:
    INY
    CPY #3
    BNE L07865B
    RTS

L07866C:
    LDA #5
    LDY $047C
    BEQ L078675
    LDA #9
L078675:
    JSR L07883A.w
    JMP L07880A.w

L07867B:
    LDX #0
    LDA #6
    JSR L07883A.w
    JMP L07880A.w

L078685:
    LDA $03E8
    EOR #1
    STA $03E8
    JSR L0789B4.w
    LDA #7
    JSR L07883A.w
    LDA $03E8
    EOR #1
    STA $03E8
    JMP L07880A.w

L0786A0:
    LDA #18
    JSR L07883A.w
    JSR L07882A.w
    LDA $0312
    JMP L078643.w

L0786AE:
    LDX #0
    LDA $0320
    JSR L0786DE.w
    LDA #12
    JSR L07883A.w
    JMP L07880A.w

L0786BE:
    LDX #0
    LDA $0320
    JSR L0786DE.w
    LDA #15
    JSR L07883A.w
    JMP L07880A.w

L0786CE:
    LDX #0
    LDA $0321
    JSR L0786DE.w
    LDA #16
    JSR L07883A.w
    JMP L07880A.w

L0786DE:
    ASL
    TAY
    LDA L0FDCAD.w,Y
    STA $08
    LDA (L0FDCAD.w + 1),Y
    STA $09
    JSR L07882A.w
    RTS

L0786EE:
    LDA #3
    JSR L07883A.w
    JMP L07880A.w

L0786F6:
    LDA #23
    JSR L07883A.w
    JMP L07880A.w

L0786FE:
    LDA #25
    JSR L07883A.w
    JMP L07880A.w

L078706:
    LDX #0
    LDA $0304
    STA $0384
    LDA $0305
    STA $0304
    JSR L0789B4.w
    LDA $0384
    STA $0304
    LDA #17
    JSR L07883A.w
    JMP L07880A.w

L078725:
    LDX #0
    JSR L078753.w
    LDA #13
    JSR L07883A.w
    JMP L07880A.w

L078732:
    LDX #0
    JSR L0789B4.w
    LDA #14
    JSR L07883A.w
    JSR L07882A.w
    LDA $049B
    BNE L078748
    LDA #24
    BNE L07874D
L078748:
    JSR L078648.w
    LDA #22
L07874D:
    JSR L07883A.w
    JMP L07880A.w

L078753:
    LDA $0304
    STA $0384
    LDA $0305
    STA $0304
    JSR L0789B4.w
    LDA $0384
    STA $0304
    RTS

L078769:
    LDX #0
    LDA #20
    JSR L07883A.w
    JMP L07880A.w

L078773:
    LDX #0
    LDA #19
    JSR L07883A.w
    JMP L07880A.w

L07877D:
    LDX #0
    LDA #11
    JSR L07883A.w
    JMP L078805.w

L078787:
    RTS

L078788:
    LDX #0
    LDA #21
    JSR L07883A.w
    JMP L078805.w

L078792:
    LDX #0
    JSR L0789B4.w
    LDA #26
    STA $7DC3,X
    INX
    LDA #255
    STA $7DC3,X
    INX
    JSR L0789EA.w
    LDA #8
    JSR L07883A.w
    JMP L07880A.w

L0787AE:
    LDX $03E8
    LDA $0320,X
    CMP #47
    BEQ L078788
    LDA $0357,X
    BNE L07877D
    CPX #1
    BEQ L0787D1
    LDA $04CD
    BEQ L0787D1
    LDA $0306,X
    CMP #3
    BEQ L078773
    CMP #5
    BEQ L078773
L0787D1:
    LDA $0306,X
    CMP #11
    BEQ L0787E0
    CMP #17
    BEQ L0787E0
    CMP #18
    BNE L0787F1
L0787E0:
    CPX #0
    BNE L0787FD
    LDA $0320,X
    CMP #23
    BCC L0787FD
    CMP #47
    BCS L0787FD
    BCC L078792
L0787F1:
    CMP #16
    BEQ L078792
    CMP #15
    BEQ L078792
    CMP #19
    BEQ L078792
L0787FD:
    LDX $03F3
    DEX
    TXA
    JSR L07883A.w
L078805:
    LDX #0
    JSR L0789B4.w
L07880A:
    JSR L07882A.w
    LDA #125
    STA $01
    LDA #195
    STA $00
    LDA #34
    STA $03
    LDA #131
    STA $02
    LDA #22
    STA $04
    JSR L0FE584.w
    LDA #0
    STA $0499
    RTS

L07882A:
    LDY #0
L07882C:
    LDA ($08),Y
    STA $7DC3,X
    CMP #239
    BEQ L078839
    INX
    INY
    BNE L07882C
L078839:
    RTS

L07883A:
    ASL
    TAY
    LDA L07884B.w,Y
    STA $08
    LDA (L07884B.w + 1),Y
    STA $09
    RTS

L078847:
.dw L0FDEA9
.dw L0FDFBA

L07884B:
.dw L07887F
.dw L078887
.dw L07888F
.dw L078899
.dw L07889F
.dw L0788AA
.dw L0788B7
.dw L0788C6
.dw L0788D4
.dw L0788DA
.dw L0788E1
.dw L0788E9
.dw L0788F9
.dw L078905
.dw L07890E
.dw L078914
.dw L078921
.dw L078930
.dw L078942
.dw L078950
.dw L078960
.dw L07896D
.dw L078978
.dw L07897E
.dw L078993
.dw L07899C

L07887F:
ENCODE("の こうげき")
STOP

L078887:
ENCODE("の はんげき")
STOP

L07888F:
ENCODE("の さいこうげき")
STOP

L078899:
ENCODE("はしんだ")
STOP

L07889F:
ENCODE("ひっさつのいちげき")
STOP

L0788AA:
ENCODE("のダメージをあたえた")
STOP

L0788B7:
ENCODE("ダメージをあたえられない")
STOP

L0788C6:
ENCODE("は すばやくみをかわした")
STOP

L0788D4:
ENCODE("をとなえた")
STOP

L0788DA:
ENCODE("かいふくした")
STOP

L0788E1:
ENCODE("は HPが ")
STOP

L0788E9:
ENCODE("は こうげきをふうじられた")
STOP

L0788F9:
ENCODE("は のろいをはなった!")
STOP

L078905:
ENCODE("は ワープした")
STOP

L07890E:
ENCODE("は HPを")
STOP

L078914:
ENCODE("は こわれてしまった!!")
STOP

L078921:
ENCODE("は きょうどがあがった")
STOP

L078930:
ENCODE("の すがたがうかびあがった")
STOP

L078942:
ENCODE("みかたぜんぶのHPが")
STOP

L078950:
ENCODE("トライアングルアターック!!")
STOP

L078960:
ENCODE("しかしこうかがなかった")
STOP

L07896D:
ENCODE("はぶきがない!!")
STOP

L078978:
ENCODE("うばった")
STOP

L07897E:
ENCODE("まふうじのたては まほうをはねかえした")
STOP

L078993:
ENCODE("うばえなかった")
STOP

L07899C:
ENCODE("ルドルフは なぜかこうげきしてこない!!")
STOP

L0789B4:
    STX $0380
    LDX $03E8
    TXA
    ASL
    TAY
    LDA L078847.w,Y
    STA $00
    LDA (L078847.w + 1),Y
    STA $01
    LDY $0304,X
    DEY
    TYA
    ASL
    TAY
    LDA ($00),Y
    STA $02
    INY
    LDA ($00),Y
    STA $03
L0789D7:
    LDX $0380
    LDY #0
L0789DC:
    LDA ($02),Y
    CMP #239
    BEQ L0789E9
    STA $7DC3,X
    INX
    INY
    BNE L0789DC
L0789E9:
    RTS

L0789EA:
    STX $0380
    LDX $03E8
    LDA $0320,X
    ASL
    TAX
    LDA L0FDCAD.w,X
    STA $02
    LDA (L0FDCAD.w + 1),X
    STA $03
    JMP L0789D7.w

L078A02:
    RTS

L078A03:
    LDX #0
    JSR L0789B4.w
    LDA $03E8
    ASL
    TAY
    LDA L078A27.w,Y
    STA $00
    LDA (L078A27.w + 1),Y
    STA $01
    TXA
    TAY
    LDA #239
    STA ($00),Y
    DEY
L078A1E:
    LDA $7DC3,Y
    STA ($00),Y
    DEY
    BPL L078A1E
    RTS

L078A27:
.dw $7EAB
.dw $7E8B

L078A2B:
.db $24
.db $21
.db $07
.db $09
.db $10
.db $24
.db $04
.db $04

L078A33:
.db $23
.db $20
.db $39
.db $13
.db $11
.db $25
.db $06
.db $06
.db $00

L078A3C:
    LDA #4
    STA $3D
    JMP L0FD499.w

L078A43:
    LDA $7442
    BNE L078A52
    LDX $744C
    DEX
    LDA L078A58.w,X
    JMP L0FF58A.w

L078A52:
    LDA #1
    STA $06D0
    RTS

L078A58:
.db $A0 $B7 $94 $96 $83

L078A5D:
    LDA $5E
    BNE L078A67
    JSR L0FC288.w
    JMP L078A76.w

L078A67:
    LDX #0
    LDA #244
L078A6B:
    STA $0200,X
    INX
    INX
    INX
    INX
    CPX #36
    BCC L078A6B
L078A76:
    RTS

L078A77:
    LDA $1A
    STA $1B
    LDA $1C
    STA $1D
    LDA $1E
    STA $1F
    RTS

L078A84:
    JSR L078A77.w
    JSR L078A5D.w
    LDA $8A
    JSR L0FC34C.w

L078A8F:
.dw L078E80
.dw L079158
.dw L079248
.dw L07922D
.dw L079506
.dw L07954E
.dw L0795C5
.dw L07960A
.dw L07960B
.dw L079650
.dw L0797A6
.dw L07984A
.dw L07987F
.dw L07989D
.dw L0798B7
.dw L079A91
.dw L079AF4
.dw L079BAB
.dw L079C3B
.dw L079E70
.dw L07A000
.dw L079FD9
.dw L07A157
.dw L07A081
.dw L079A91
.dw L079AF4
.dw L07A0C2
.dw L079C3B
.dw L078B52
.dw L078E1A
.dw L078D28
.dw L078B1F
.dw L078B85
.dw L078AE3
.dw L07A207
.dw L07A21C
.dw L07A247
.dw L07A25F
.dw L07A288
.dw L07A2A0
.dw L07A2C2
.dw L07A370

L078AE3:
    LDA $059C
    JSR L0FC34C.w

.dw L078AEF
.dw L078B0C
.dw RESET

L078AEF:
    JSR L0793B7.w
    LDA #97
    JSR L0FF58A.w
    LDA #3
    JSR L0FC9BD.w
    LDA #128
    STA $28
    JSR L0FC70D.w
    LDA #64
    JSR L0FE6B8.w
    INC $059C
    RTS

L078B0C:
    JSR L0793B7.w
    JSR L0FE783.w
    JSR L0FE674.w
    LDA $1A
    AND #128
    BEQ L078B1E
    INC $059C
L078B1E:
    RTS

L078B1F:
    JSR L078DE1.w
    JSR L0FE674.w
    LDA $059C
    JSR L0FC34C.w

L078B2B:
.dw L078B2F
.dw L078B38

L078B2F:
    LDA #60
    JSR L0FE6B8.w
    INC $059C
    RTS

L078B38:
    LDA $7477
    BEQ L078B41
    LDA $35
    BEQ L078B45
L078B41:
    LDA $1A
    BEQ L078B51
L078B45:
    JSR L0FE696.w
    LDA #0
    STA $059C
    LDA #2
    STA $8A
L078B51:
    RTS

L078B52:
    JSR L078DE1.w
    JSR L0FE674.w
    LDA $05AC
    JSR L0FC34C.w

.dw L078E12
.dw L078B64
.dw L078D1B

L078B64:
    LDA #0
    STA $059C
    JSR L0FE696.w
    LDA #31
    STA $8A
    RTS

L078B71:
    LDA #1
    STA $059C
    JSR L0FC9BD.w
    JSR L0FE696.w
    LDA #32
    STA $8A
    RTS

L078B81:
    LDA #1
    STA $DE
L078B85:
    LDA $059C
    JSR L0FC34C.w

.dw L0FC73D
.dw L078C4B
.dw L078CB4
.dw L078CEE
.dw L078D0A
.dw L078C9F
.dw L078C29
.dw L078C65
.dw L078C8E
.dw L078BAD
.dw L078BCE
.dw L078BDD
.dw L078C74
.dw L078BFE
.dw L078C11
.dw L078C65
.dw L078C8E

L078BAD:
    JSR L078DE1.w
    JSR L0FE684.w
    LDY $058F
    DEY
    LDA #0
    STA $7D73,Y
    LDY $05AC
    BNE L078BC4
    JMP L078C8E.w
L078BC4:
    DEY
    STY $6D
    JSR L0FE696.w
    INC $059C
    RTS

L078BCE:
    JSR L078DE1.w
    JSR L0FE684.w
    LDA #34
    JSR L0FE6B8.w
    INC $059C
    RTS

L078BDD:
    JSR L078DE1.w
    JSR L0FE684.w
    LDA #0
    STA $7DA5
    STA $059D
    LDA #177
    STA $7DA9
    LDA #1
    STA $7DAC
    LDA #83
    STA $7DA6
    INC $059C
    RTS

L078BFE:
    JSR L078DE1.w
    JSR L0FE684.w
    LDA #12
    JSR L0FE6B8.w
    LDA #0
    STA $2C
    INC $059C
    RTS

L078C11:
    JSR L078DE1.w
    JSR L0FE684.w
    LDA $05AC
    CMP #1
    BEQ L078C21
    JMP L078C8E.w
L078C21:
    LDA #2
    STA $4A
    JSR L0FCA94.w
    RTS

L078C29:
    JSR L078DE1.w
    JSR L0FE684.w
    LDY $058F
    DEY
    LDA #0
    STA $7D73,Y
    LDA $05AC
    BEQ L078C8E
    LDA #0
    STA $4A
    LDA #2
    JSR L0FCA94.w
    LDA #0
    STA $2C
    RTS

L078C4B:
    JSR L0795DB.w
    LDA $6D
    STA $7433
    LDA #68
    JSR L0FE6B8.w
    LDA $7433
    STA $6D
    LDA #0
    STA $2C
    INC $059C
    RTS

L078C65:
    JSR L078DE1.w
    JSR L078D01.w
    LDA $7DB9
    BEQ L078C73
    INC $059C
L078C73:
    RTS

L078C74:
    JSR L078DE1.w
    JSR L078D01.w
    LDA $7DBF
    BEQ L078C8D
    LDA $059D
    BEQ L078C8A
    STA $059C
    JMP L078C8D.w
L078C8A:
    INC $059C
L078C8D:
    RTS

L078C8E:
    JSR L078DE1.w
    JSR L0795DB.w
    LDA $7433
    STA $6D
    LDA #1
    STA $059C
    RTS

L078C9F:
    LDA $7433
    STA $6D
L078CA4:
    JSR L078DE1.w
    JSR L0795DB.w
    LDA #3
    STA $8A
    LDA #0
    STA $059C
    RTS

L078CB4:
    JSR L078DE1.w
    JSR L0FE684.w
    LDY $058F
    DEY
    LDA #0
    STA $7D73,Y
    LDA $05AC
    BEQ L078CA4
    CMP #1
    BEQ L078CDC
    CMP #2
    BEQ L078CE3
    LDA #14
    JSR L0FE6B8.w
    LDA #9
    STA $059C
    BNE L078CED
L078CDC:
    LDA #3
    STA $059C
    BNE L078CED
L078CE3:
    LDA #14
    JSR L0FE6B8.w
    LDA #6
    STA $059C
L078CED:
    RTS

L078CEE:
    JSR L078DE1.w
    JSR L0FE684.w
    LDA #85
    STA $D7
    LDA #1
    STA $05AF
    INC $059C
    RTS

L078D01:
    LDA #0
    STA $4A
    LDA #10
    JMP L0FCA94.w

L078D0A:
    JSR L078DE1.w
    LDA #0
    STA $3D
    LDA #5
    STA $4A
    LDA #11
    JSR L0FCA94.w
    RTS

L078D1B:
    JSR L0FE696.w
    LDA #0
    STA $059C
    LDA #30
    STA $8A
    RTS

L078D28:
    JSR L078DE1.w
    JSR L0FE674.w
    LDA $059C
    JSR L0FC34C.w

L078D34:
.dw L078D3A
.dw L078D46
.dw L078DA7

L078D3A:
    LDA #0
    STA $2C
    INC $059C
    LDA #27
    JMP L0FE6B8.w

L078D46:
    LDX $058F
    DEX
    LDA #0
    STA $7D73,X
    LDX $05AC
    STX $74B4
    CPX #1
    BEQ L078D6B
    CPX #2
    BEQ L078D7F
    CPX #3
    BEQ L078D93
    LDA #2
    STA $8A
    LDA #0
    STA $059C
    RTS

L078D6B:
    INC $059C
    LDX $058F
    LDA $7442
    STA $7D78,X
    INC $7D78,X
    LDA #25
    JMP L0FE6B8.w

L078D7F:
    INC $059C
    LDX $058F
    LDA $7443
    STA $7D78,X
    INC $7D78,X
    LDA #25
    JMP L0FE6B8.w

L078D93:
    INC $059C
    LDX $058F
    LDA $7444
    STA $7D78,X
    INC $7D78,X
    LDA #26
    JMP L0FE6B8.w

L078DA7:
    LDX $05AC
    BEQ L078DD3
    DEX
    LDA $74B4
    CMP #1
    BEQ L078DBC
    CMP #2
    BEQ L078DCA
    CMP #3
    BEQ L078DD0
L078DBC:
    STX $7442
    STX $06D0
    BNE L078DD3
    JSR L078A43.w
    JMP L078DD3.w
L078DCA:
    STX $7443
    JMP L078DD3.w
L078DD0:
    STX $7444
L078DD3:
    LDA #2
    STA $2C
    LDA #0
    STA $059C
    LDA #6
    STA $8A
    RTS

L078DE1:
    JSR L0793B7.w
    JSR L0FE783.w
    LDA #0
    STA $3D
    RTS

L078DEC:
    LDA #0
    STA $059C
    JSR L0FE696.w
    INC $8A
    RTS

L078DF7:
    LDX $05B8
    LDA #0
    STA $7A74,X
    STA $2D
    LDA #1
    STA $7477
    JSR L0795DB.w
    LDA #31
    STA $8A
    LDA #16
    STA $35
    RTS

L078E12:
    JSR L0FE696.w
    LDA #2
    STA $8A
    RTS

L078E1A:
    JSR L078DE1.w
    JSR L0FE674.w
    LDA $059C
    JSR L0FC34C.w
    ROL
    STX L078E41.w
    LDA #59
    JSR L0FE6B8.w
    LDA #2
    STA $2C
    LDA #1
    JSR L0FC9BD.w
    LDA #4
    STA $05B5
    INC $059C
    RTS

L078E41:
    LDA $05B5
    BEQ L078E4F
    LDA #2
    STA $4A
    LDA #4
    JMP L0FCA94.w

L078E4F:
    LDX $05AC
    DEX
    LDA $6C9C,X
    STA $01
    LDA $6CAE,X
    STA $00
    JSR L078EC4.w
    JSR L0FD39A.w
    LDA #29
    JSR L0FCA58.w
    JSR L0FCA60.w
    LDA #30
    JSR L0FCA48.w
    JSR L0FCA50.w
    LDA #2
    STA $8A
    LDA #0
    STA $059C
    STA $058F
    RTS

L078E80:
    JSR L0FC71F.w
    LDA #0
    STA $DE
    STA $7B24
    STA $7C34
    STA $7434
    JSR L0FCCE7.w
    JSR L078F1B.w
    JSR L078F00.w
    LDA $05E9
    BEQ L078EA4
    LDX $05E7
    JMP L078EB4.w

L078EA4:
    LDX $6D0E
    LDA $6CF6,X
    BEQ L078EB1
    LDA $6D90,X
    BEQ L078EB4
L078EB1:
    JSR L0FC9B6.w
L078EB4:
    LDA $6C9C,X
    STA $01
    LDA $6CAE,X
    STA $00
    JSR L078EC4.w
    INC $8A
    RTS

L078EC4:
    LDA $00
    STA $94
    SEC
    SBC #8
    BPL L078ECF
    LDA #0
L078ECF:
    STA $69
    LDA $05F4
    CMP $69
    BCC L078EDA
    STA $69
L078EDA:
    LDA $7440
    SEC
    SBC #14
    CMP $69
    BCS L078EE6
    STA $69
L078EE6:
    LDA $01
    STA $95
    SEC
    SBC #8
    BCS L078EF1
    LDA #0
L078EF1:
    STA $6A
    LDA $7441
    SEC
    SBC #15
    CMP $6A
    BCS L078EFF
    STA $6A
L078EFF:
    RTS

L078F00:
    LDX $744C
    DEX
    LDA L078F11.w,X
    STA $7441
    LDA L078F16.w,X
    STA $05F4
    RTS

L078F11:
.db $1F
.db $1F
.db $1F
.db $1F
.db $1F

L078F16:
.db $19
.db $19
.db $0D
.db $00
.db $00

L078F1B:
    LDX #0
L078F1D:
    LDA $6D93,X
    CMP #255
    BNE L078F56
    CPX #2
    BEQ L078F56
    CPX #5
    BEQ L078F56
    CPX #6
    BEQ L078F56
    CPX #8
    BEQ L078F56
    CPX #3
    BEQ L078F56
    LDA L0FF124.w,X
    SEC
    SBC #1
    ASL
    TAY
    LDA L0FEEF4.w,Y
    STA $00
    LDA (L0FEEF4.w + 1),Y
    JSR L0FCEBF.w
    LDY $00
    LDA #160
    STA ($70),Y
    INY
    LDA #161
    STA ($70),Y
L078F56:
    INX
    CPX #9
    BCC L078F1D
    LDA $6D92
    STA $0C
    LDA #0
    STA $0D
L078F64:
    LSR $0C
    BCC L078F88
    LDX $0D
    LDA L0FE3A3.w,X
    SEC
    SBC #1
    ASL
    TAY
    LDA L0FEEF4.w,Y
    STA $00
    LDA (L0FEEF4.w + 1),Y
    JSR L0FCEBF.w
    LDY $00
    LDA #153
    STA ($70),Y
    INY
    LDA #154
    STA ($70),Y
L078F88:
    INC $0D
    LDA $0D
    CMP #4
    BCC L078F64
    LDA $744C
    CMP #4
    BNE L078FA6
    LDA #15
    JSR L0FCEBF.w
    LDY #63
L078F9E:
    LDA L0790F6.w,Y
    STA ($70),Y
    DEY
    BPL L078F9E
L078FA6:
    JSR L078FE7.w
    JSR L078FAD.w
    RTS

L078FAD:
    LDA $6D8F
    AND #1
    BEQ L078FCA
    LDA #7
    JSR L0FCEBF.w
    LDY #4
    LDA #94
    STA ($70),Y
    LDA #8
    JSR L0FCEBF.w
    LDY #4
    LDA #95
    STA ($70),Y
L078FCA:
    LDA $6D8F
    AND #32
    BEQ L078FE6
    LDA #8
    JSR L0FCEBF.w
    LDY #6
    LDA #106
    STA ($70),Y
    INY
    LDA #108
    STA ($70),Y
    INY
    LDA #109
    STA ($70),Y
L078FE6:
    RTS

L078FE7:
    LDA $744C
    CMP #1
    BNE L07900E
    LDA #28
    STA $0C
    LDX #0
L078FF4:
    LDA $0C
    JSR L0FCEBF.w
    LDY #16
L078FFB:
    LDA L079026.w,X
    STA ($70),Y
    INX
    INY
    CPY #32
    BCC L078FFB
    INC $0C
    LDA $0C
    CMP #41
    BCC L078FF4
L07900E:
    LDA $6D8F
    AND #4
    BEQ L079025
    LDA #29
    JSR L0FCEBF.w
    LDY #13
    LDA #194
L07901E:
    STA ($70),Y
    INY
    CPY #18
    BCC L07901E
L079025:
    RTS

L079026:
.db $C2
.db $8A
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $31
.db $33
.db $D2
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D5
.db $CB
.db $CB
.db $C2
.db $C2
.db $D0
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D3
.db $C2
.db $D2
.db $CB
.db $D1
.db $D0
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $7E
.db $7F
.db $9B
.db $D6
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D3
.db $36
.db $D2
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D1
.db $D0
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D1
.db $96
.db $D0
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D4
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D3
.db $D2
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D3
.db $D2
.db $CB
.db $D5
.db $DE
.db $C2
.db $C2
.db $D6
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D1
.db $C2
.db $8A
.db $C2
.db $C2
.db $9C
.db $9C
.db $D6
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D7
.db $C2
.db $C2
.db $C2
.db $C2
.db $C2
.db $C2
.db $D6
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D7
.db $C2
.db $C2
.db $C2
.db $C2
.db $C2
.db $D0
.db $CB
.db $CB
.db $CB
L0790F6:
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D5
.db $DA
.db $DA
.db $8B
.db $ED
.db $C2
.db $C2
.db $C2
.db $C2
.db $C2
.db $C2
.db $41
.db $71
.db $40
.db $C2
.db $C2
.db $C2
.db $8B
.db $DA
.db $DA
.db $DA
.db $DA
.db $DA
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $CB
.db $D3
.db $C2
.db $C2
.db $C2
.db $9B
.db $88
.db $89
.db $76
.db $78
.db $78
.db $79
.db $C2
.db $C2
.db $C2
.db $C2
.db $C2
.db $C2
.db $8C
.db $8D
.db $E2
.db $37
.db $E4
.db $37
.db $E3
.db $D2
.db $D5
.db $CB
.db $CB

L079136:
    JSR L0FD39A.w
    LDA #29
    JSR L0FCA58.w
    JSR L0FCA60.w
    LDA #30
    JSR L0FCA48.w
    JSR L0FCA50.w
    LDA $6A
    CLC
    ADC #8
    STA $95
    LDA $69
    CLC
    ADC #8
    STA $94
    RTS

L079158:
    JSR L0FD39A.w
    LDA #29
    JSR L0FCA58.w
    JSR L0FCA60.w
    LDA #30
    JSR L0FCA48.w
    JSR L0FCA50.w
    LDA #12
    STA $4A
    LDA #8
    JSR L0FCA94.w
    LDA #0
    STA $05B9
    STA $05D8
    STA $2D
    JSR L079198.w
    JSR L078A43.w
    LDA $05E9
    BEQ L079195
    LDA #0
    STA $05B6
    STA $059C
    LDA #22
    STA $8A
L079195:
    INC $8A
    RTS

L079198:
    LDX #14
L07919A:
    LDA #48
    STA $7ABD,X
    LDA #0
    STA $7ACF,X
    STA $7A74,X
    JSR L0791BC.w
    LDA $7A86,X
    CMP #28
    BNE L0791B6
    LDA #32
    STA $7ABD,X
L0791B6:
    DEX
    BPL L07919A
    RTS

L0791BA:
.db $01 $02

L0791BC:
    LDA $6CF6,X
    BEQ L079211
    CPX #2
    BCS L0791DA
    LDA $6CC0,X
    JSR L079212.w
    BCC L0791D1
    LDA #28
    BNE L0791D4
L0791D1:
    LDA L0791BA.w,X
L0791D4:
    STA $7A86,X
    JMP L079211.w

L0791DA:
    TXA
    ASL
    TAY
    LDA $6CD2,Y
    STA $00
    LDA $6CD3,Y
    STA $01
    LDA $6CC0,X
    JSR L079212.w
    BCC L0791FD
    LDY #2
    LDA ($00),Y
    BNE L0791F9
    LDA #29
    BNE L07920E
L0791F9:
    LDA #30
    BNE L07920E
L0791FD:
    STX $0E
    TXA
    PHA
    LDA #19
    STA $4A
    LDA #8
    JSR L0FCA94.w
    PLA
    TAX
    LDA $0F
L07920E:
    STA $7A86,X
L079211:
    RTS

L079212:
    STA $747B
    TXA
    PHA
    LDX #4
    LDA $747B
L07921C:
    CMP L079228.w,X
    BEQ L079225
    DEX
    BPL L07921C
    CLC
L079225:
    PLA
    TAX
    RTS

L079228:
.db $0E $0F $0C $0A $09

L07922D:
    LDA #0
    STA $A0
    JSR L078A3C.w
    JSR L0793B7.w
    LDA #1
    STA $5E
    LDA $7477
    BNE L079245
    LDA #40
    JSR L0FE6B8.w
L079245:
    INC $8A
    RTS

L079248:
    JSR L079273.w
    JSR L079286.w
    JSR L0FD4FC.w
    LDA #0
    STA $A0
    JSR L07928A.w
    JSR L078A3C.w
    JSR L0793B7.w
    JSR L0FE674.w
    LDA #0
    STA $5E
    LDA $8E
    BNE L079272
    JSR L0792BE.w
    JSR L0792CF.w
    JSR L079432.w
L079272:
    RTS

L079273:
    LDA $7477
    BEQ L079282
    LDA #0
    STA $1B
    STA $1D
    STA $1F
    BEQ L079285
L079282:
    JSR L0FD40C.w
L079285:
    RTS

L079286:
    JSR L0FD0C5.w
    RTS

L07928A:
    LDA #0
    STA $3F
    JSR L079298.w
    BCC L079297
    LDA #2
    STA $3F
L079297:
    RTS

L079298:
    LDA $94
    JSR L0FCEBF.w
    LDY $95
    LDA ($70),Y
    CMP #125
    BCC L0792BC
    CMP #160
    BCS L0792BC
    CMP #146
    BEQ L0792BC
    CMP #147
    BEQ L0792BC
    CMP #156
    BEQ L0792BC
    CMP #139
    BEQ L0792BC
    SEC
    BCS L0792BD
L0792BC:
    CLC
L0792BD:
    RTS

L0792BE:
    LDA $7447
    BEQ L0792CE
    LDA #18
    STA $8A
    LDA #0
    STA $059C
    PLA
    PLA
L0792CE:
    RTS

L0792CF:
    LDA $7447
    BNE L0792D9
    LDA $7477
    BNE L0792DA
L0792D9:
    RTS

L0792DA:
    LDA #0
    STA $1A
    STA $1C
    STA $1E
    LDA $2D
    JSR L0FC34C.w

.dw L0792F1
.dw L079338
.dw L0793AC
.dw L0793AC
.dw L0FC73D

L0792F1:
    LDA #11
    STA $4A
    LDA #8
    JSR L0FCA94.w
    LDA #0
    STA $0581
    STA $0580
    LDA #5
    STA $4A
    LDA #8
    JSR L0FCA94.w
    LDA $0581
    BEQ L079333
    LDA #0
    STA $05B6
    STA $059C
    LDA $95
    STA $0506
    LDA $94
    STA $0507
    LDA #8
    STA $8A
    LDA #22
    STA $2C
    LDA #1
    STA $7447
    LDA #3
    STA $2D
L079333:
    PLA
    PLA
    INC $2D
    RTS

L079338:
    JSR L07A47C.w
    LDA $7AFB
    BEQ L07934E
    JSR L07938A.w
    BCS L07934E
    LDA $7AFA
    STA $05DC
    JMP L07935C.w

L07934E:
    LDA #0
    STA $7477
    JSR L07A1DF.w
    JSR L0FCA1D.w
    PLA
    PLA
    RTS

L07935C:
    LDX $05DC
    LDA $6C9E,X
    STA $0581
    LDA $6CB0,X
    STA $0580
    LDA #0
    STA $05B6
    LDA $95
    STA $0506
    LDA $94
    STA $0507
    STX $05B9
    LDA #8
    STA $8A
    LDA #2
    STA $2C
    INC $2D
    PLA
    PLA
    RTS

L07938A:
    STA $05DB
    SEC
    SBC #1
    ASL
    TAX
    LDA L0FEEF4.w,X
    STA $03
    LDA (L0FEEF4.w + 1),X
    STA $02
    LDA $7AFA
    CLC
    ADC #2
    STA $05B8
    JSR L07A132.w
    BCC L0793AB
    SEC
L0793AB:
    RTS

L0793AC:
    LDA #128
    STA $1B
    STA $1D
    STA $1F
    INC $2D
    RTS

L0793B7:
    LDA $DE
    BEQ L0793BC
L0793BB:
    RTS

L0793BC:
    LDA #19
    STA $3D
    LDA $5E
    CMP #2
    BNE L0793CA
    LDA #35
    STA $3D
L0793CA:
    LDX #0
L0793CC:
    LDA $3D
    CMP #255
    BEQ L0793BB
    LDA $6CF6,X
    BEQ L07942C
    CPX #2
    BCS L0793E0
    LDA $6D90,X
    BNE L07942C
L0793E0:
    TXA
    ASL
    TAY
    LDA $6CD2,Y
    STA $00
    LDA $6CD3,Y
    STA $01
    LDY #0
    LDA ($00),Y
    BEQ L07942C
    LDA $5E
    BEQ L079407
    CMP #1
    BEQ L079402
    CPX $05B8
    BEQ L07942C
    BNE L079407
L079402:
    CPX $05B8
    BNE L07942C
L079407:
    LDA $6C9C,X
    STA $44
    LDA $6CAE,X
    STA $45
    LDA $7ABD,X
    STA $49
    LDA $7ACF,X
    STA $47
    LDA $7A74,X
    STA $46
    LDA $7A86,X
    STA $48
    LDA #248
    STA $43
    JSR L0FCB44.w
L07942C:
    INX
    CPX #15
    BCC L0793CC
    RTS

L079432:
    LDA $1B
    AND #128
    BEQ L079468
    LDA $94
    STA $04
    LDA $95
    STA $05
    JSR L0794CF.w
    BCC L0794BA
    STX $05B8
    LDA #2
    STA $5E
    CPX #2
    BCS L07945B
    LDA $6D90,X
    BNE L0794BA
    LDA $05B8
    STA $6D0E
L07945B:
    LDA $7477
    BNE L079463
    JSR L0FF572.w
L079463:
    INC $8A
    JMP L0794B0.w

L079468:
    LDA $1B
    AND #64
    BEQ L0794B0
    JSR L0794B1.w
    LDX $05DD
    LDA $6D90,X
    BEQ L07947C
    JSR L0794B1.w
L07947C:
    LDX $05DD
    LDA $6CF6,X
    BNE L079487
    JSR L0794B1.w
L079487:
    LDX $05DD
    LDA $6C9C,X
    STA $0581
    LDA $6CAE,X
    STA $0580
    LDA #0
    STA $05B6
    LDA $95
    STA $0506
    LDA $94
    STA $0507
    STX $05B9
    LDA #8
    STA $8A
    LDA #2
    STA $2C
L0794B0:
    RTS

L0794B1:
    LDA $05DD
    EOR #1
    STA $05DD
    RTS

L0794BA:
    LDA $1B
    AND #32
    BNE L0794CE
    JSR L079298.w
    BCC L0794CE
    LDA #40
    STA $8A
    LDA #0
    STA $059C
L0794CE:
    RTS

L0794CF:
    LDX #14
    LDA #0
    BEQ L0794E6
L0794D5:
    LDA $05B8
    CMP #2
    BCS L0794E2
    LDX #1
    LDA #0
    BEQ L0794E6
L0794E2:
    LDX #14
    LDA #2
L0794E6:
    STA $16
L0794E8:
    LDA $6CF6,X
    BEQ L0794FD
    LDA $05
    CMP $6C9C,X
    BNE L0794FD
    LDA $04
    CMP $6CAE,X
    BNE L0794FD
    SEC
    RTS

L0794FD:
    CPX $16
    BEQ L079504
    DEX
    BPL L0794E8
L079504:
    CLC
    RTS

L079506:
    JSR L0793B7.w
    JSR L0FE783.w
    JSR L0FE674.w
    LDA #2
    LDX $05B8
    STA $7A74,X
    LDA $7477
    BEQ L079521
    LDA #2
    JMP L0795A2.w

L079521:
    JSR L0797E7.w
    CMP $7477
    BNE L079535
    LDA #65
    JSR L0FE6B8.w
    LDA #0
    STA $2C
    INC $8A
    RTS

L079535:
    LDA $1B
    AND #64
    BNE L07953C
    RTS

L07953C:
    LDA #0
    LDX $05B8
    STA $7A74,X
    JSR L0795DB.w
    LDA #2
    STA $8A
    JMP L0795AC.w

L07954E:
    LDA #3
    STA $3F
    LDA #0
    STA $92
    LDA $36
    AND #16
    BEQ L07955E
    INC $92
L07955E:
    JSR L078A3C.w
    JSR L0793B7.w
    JSR L0FE783.w
    JSR L0FE674.w
    LDA $05AC
    JSR L0FC34C.w

.dw L07957E
.dw L079593
.dw L0795AD
.dw L0795BD
.dw L0795B5
.dw L078DF7
.dw L078B71

L07957E:
    LDX $05B8
    LDA #0
    STA $7A74,X
    JSR L0795DB.w
    LDA #2
    STA $8A
    LDA #0
    STA $059C
    RTS

L079593:
    LDA $95
    SEC
    SBC $6A
    CMP #8
    BCC L0795A0
    LDA #2
    BNE L0795A2
L0795A0:
    LDA #1
L0795A2:
    STA $7AF9
    JSR L0795DB.w
    LDA #9
    STA $8A
L0795AC:
    RTS

L0795AD:
    JSR L0795DB.w
    LDA #34
    STA $8A
    RTS

L0795B5:
    JSR L0795DB.w
    LDA #36
    STA $8A
    RTS

L0795BD:
    JSR L0795DB.w
    LDA #38
    STA $8A
    RTS

L0795C5:
    JSR L0793B7.w
    JSR L0FE783.w
    JSR L0FE674.w
    JSR L0FE696.w
    LDA $058F
    BNE L0795DA
    LDA $2C
    STA $8A
L0795DA:
    RTS

L0795DB:
    LDY $058F
    BEQ L0795FF
    DEY
    LDA #0
L0795E3:
    STA $7D73,Y
    DEY
    BPL L0795E3
L0795E9:
    JSR L078A5D.w
    JSR L079600.w
    JSR L0FC336.w
    INC $36
    LDA $058F
    BEQ L0795FF
    JSR L0FC70D.w
    JMP L0795E9.w

L0795FF:
    RTS

L079600:
    JSR L078DE1.w
    JSR L0FE684.w
    JSR L0FE696.w
    RTS

L07960A:
    RTS

L07960B:
    JSR L0793B7.w
    JSR L0FE674.w
    LDA #9
    STA $4A
    LDA #6
    JSR L0FCA94.w
    JSR L079286.w
    LDA $8E
    BNE L079638
    LDA $0506
    STA $95
    LDA $0507
    STA $94
    LDA $8E
    BNE L079638
    LDA $05B6
    BEQ L079638
    LDA $2C
    STA $8A
L079638:
    RTS

L079639:
    TYA
    PHA
    LDY #16
    LDA #0
L07963F:
    STA $74B4,Y
    DEY
    BPL L07963F
    LDY #4
L079647:
    STA $7B28,Y
    DEY
    BPL L079647
    PLA
    TAY
    RTS

L079650:
    JSR L0793B7.w
    JSR L0FE674.w
    LDA #0
    STA $5E
    JSR L079639.w
    JSR L0796D7.w
    JSR L0796F7.w
    LDY #0
    LDX #0
L079667:
    LDA ($00),Y
    CMP #255
    BEQ L079685
    STA $74B5,X
    LDA $7B28,Y
    BEQ L07967C
    LDA #0
    STA $74B5,X
    BEQ L079682
L07967C:
    LDA ($04),Y
    STA $74BC,X
    INX
L079682:
    INY
    BPL L079667
L079685:
    LDA $7477
    BEQ L079693
    STX $74B4
    JSR L079769.w
    JMP L0796C5.w

L079693:
    STX $74B4
    STX $06
    LDA $74B4
    BNE L0796A4
    LDA #41
    STA $8A
    JMP L0FE696.w

L0796A4:
    LDA $74BC
    STA $7AF9
    JSR L079745.w
    BCS L0796B4
    JSR L07A0F3.w
    BCC L0796C5
L0796B4:
    LDA #0
    STA $05BA
L0796B9:
    JSR L07A0F3.w
    BCC L0796C5
    INC $05BA
    DEC $06
    BNE L0796B9
L0796C5:
    LDX $05BA
    LDA $74BC,X
    STA $7AF9
    LDX $05B8
    LDA #2
    STA $7A74,X
    RTS

L0796D7:
    LDX $05B8
    LDA $6CC0,X
    TAX
    DEX
    TXA
    ASL
    TAX
    LDA L0FEF94.w,X
    STA $00
    LDA (L0FEF94.w + 1),X
    STA $01
    LDA L07A9EF.w,X
    STA $04
    LDA (L07A9EF.w + 1),X
    STA $05
    RTS

L0796F7:
    LDX $05B8
    LDA $6CC0,X
    STA $06
    LDA $6D8F
    STA $07
    LDX #0
L079706:
    LSR $07
    BCC L07973F
    LDA $06
    CMP L078A2B.w,X
    BNE L079721
    LDY #0
L079713:
    LDA ($00),Y
    CMP #255
    BEQ L079721
    CMP L078A33.w,X
    BEQ L07973A
    INY
    BNE L079713
L079721:
    LDA $06
    CMP L078A33.w,X
    BNE L07973F
    LDY #0
L07972A:
    LDA ($00),Y
    CMP #255
    BEQ L07973F
    CMP L078A2B.w,X
    BEQ L07973A
    INY
    BNE L07972A
    BEQ L07973F
L07973A:
    LDA #1
    STA $7B28,Y
L07973F:
    INX
    CPX #8
    BCC L079706
    RTS

L079745:
    AND #15
    STA $0A
    LDY #3
L07974B:
    LDA $74BC,Y
    BEQ L079754
    CMP $0A
    BEQ L079759
L079754:
    DEY
    BPL L07974B
L079757:
    SEC
    RTS

L079759:
    LDA $74B5,Y
    BEQ L079757
    LDA $74BC,Y
    STA $7AF9
    STY $05BA
    CLC
    RTS

L079769:
    LDA $05DB
    ASL
    TAX
    DEX
    DEX
    LDA L0FEEF4.w,X
    STA $03
    LDA (L0FEEF4.w + 1),X
    STA $02
    JSR L07A132.w
    BCS L079794
    LDA $05DB
    STA $05BB
    LDA $05
    STA $7B25
    LDA $04
    STA $7B26
    LDA #10
    STA $8A
    RTS

L079794:
    LDA #0
    STA $7477
    JSR L07A1DF.w
    JSR L0FCA1D.w
    LDA #2
    STA $8A
    PLA
    PLA
    RTS

L0797A6:
    JSR L078DE1.w
    JSR L0FE674.w
    LDA #1
    JSR L0FC9BD.w
    LDA #128
    STA $28
    LDA $7477
    BNE L0797BF
    LDA #44
    JSR L0FE6B8.w
L0797BF:
    INC $8A
    RTS

L0797C2:
    STA $00
    LDA $7477
    BNE L0797D7
L0797C9:
    LDX #12
L0797CB:
    LDA $6CC2,X
    CMP $00
    BEQ L0797E5
    DEX
    BPL L0797CB
    BMI L0797E3
L0797D7:
    LDX #1
L0797D9:
    LDA $6CC0,X
    CMP $00
    BEQ L0797E5
    DEX
    BPL L0797D9
L0797E3:
    CLC
    RTS

L0797E5:
    SEC
    RTS

L0797E7:
    LDA $05B8
    CMP #2
    BCS L0797F2
    LDA #0
    BEQ L0797F4
L0797F2:
    LDA #1
L0797F4:
    RTS

L0797F5:
    LDA #255
    STA $3D
    LDA $7477
    CMP #1
    BEQ L079841
    LDA #0
    STA $42
    STA $41
    STA $3E
    TAX
    LDA $7AF9
L07980C:
    LSR
    BCS L079812
    INX
    BNE L07980C
L079812:
    TXA
    STA $3C
    LDY $05B8
    LDA $6C9C,Y
    CLC
    ADC L079842.w,X
    STA $01
    LDA $6CAE,Y
    CLC
    ADC L079846.w,X
    STA $00
    LDA $01
    SEC
    SBC $6A
    JSR L0FC3A0.w
    STA $3B
    LDA $00
    SEC
    SBC $69
    JSR L0FC3A0.w
    STA $3A
    JSR L0FCAB7.w
L079841:
    RTS

L079842:
.db $01 $FF $00 $00

L079846:
.db $00 $00 $01 $FF

L07984A:
    JSR L0797F5.w
    JSR L0793B7.w
    JSR L0FE783.w
    JSR L0FE674.w
    JSR L0792CF.w
    JSR L0798FB.w
    JSR L0797E7.w
    CMP $7477
    BNE L07987E
    LDA $1B
    AND #15
    BEQ L07987E
    STA $7B27
    JSR L079745.w
    BCS L07987E
    LDA $7B27
    STA $7AF9
    JSR L07A0F3.w
    JSR L0FE696.w
L07987E:
    RTS

L07987F:
    JSR L0793B7.w
    JSR L0FE783.w
    LDA $7477
    BNE L079896
    LDA #0
    STA $3D
    JSR L0FE674.w
    LDA #46
    JSR L0FE6B8.w
L079896:
    INC $8A
    LDA $8A
    STA $2C
    RTS

L07989D:
    JSR L0793B7.w
    JSR L0FE783.w
    LDA #0
    STA $3D
    JSR L0FE674.w
    LDA $058F
    CMP #3
    BCS L0798B3
    INC $8A
L0798B3:
    JSR L0FE696.w
    RTS

L0798B7:
    JSR L0793B7.w
    JSR L0FE783.w
    LDA #0
    STA $3D
    JSR L0FE674.w
    LDA $7477
    BNE L0798DA
    LDA $05AC
    BEQ L0798D2
    CMP #1
    BEQ L0798DA
L0798D2:
    JSR L0795DB.w
    LDA #9
    STA $8A
    RTS

L0798DA:
    JSR L0795DB.w
    LDX $05B8
    LDA $6CC0,X
    STA $6D0B
    LDA $6C9C,X
    STA $6D0C
    LDA $6CAE,X
    STA $6D0D
    LDA $05B8
    JSR L079A56.w
    INC $8A
    RTS

L0798FB:
    LDA $1B
    AND #64
    BEQ L07993E
    JSR L0FE696.w
    LDX $05B8
    LDA #0
    STA $7A74,X
    LDA #1
    STA $28
    JSR L0FC70D.w
    LDX $05B8
    LDA $6C9C,X
    STA $0581
    LDA $6CAE,X
    STA $0580
    LDA #0
    STA $05B6
    STA $059C
    LDA $95
    STA $0506
    LDA $94
    STA $0507
    LDA #8
    STA $8A
    LDA #2
    STA $2C
    BNE L0799A4
L07993E:
    LDA $1B
    AND #128
    BEQ L0799A4
    LDA $7477
    BNE L07994C
    JSR L0FF572.w
L07994C:
    JSR L0795DB.w
    JSR L0799A5.w
    BCC L0799A4
    LDX $05B8
    LDA $6CC0,X
    STA $6D16,X
    LDA $05BB
    CMP #49
    BCC L079973
    LDA $7477
    BNE L07996E
    LDA #48
    JSR L0FE6B8.w
L07996E:
    INC $8A
    JMP L079994.w

L079973:
    LDA $05BB
    JSR L0797C2.w
    BCC L07998A
    LDA $7477
    BNE L079985
    LDA #45
    JSR L0FE6B8.w
L079985:
    INC $8A
    JMP L079994.w

L07998A:
    LDA $05B8
    JSR L079A56.w
    LDA #15
    STA $8A
L079994:
    LDX $05B8
    LDA #0
    STA $7A74,X
    STA $7AF8
    STA $7AF7
    PLA
    PLA
L0799A4:
    RTS

L0799A5:
    LDX $05B8
    LDA $6CC0,X
    STA $00
    LDA $05BB
    STA $01
    LDA #0
    STA $09
    TAY
L0799B7:
    TYA
    ASL
    ASL
    TAX
    LDA L07AB26.w,X
    BEQ L0799E8
    CMP #255
    BEQ L0799E6
    CMP $00
    BNE L0799CF
    LDA (L07AB26.w + 1),X
    CMP $01
    BEQ L0799E8
L0799CF:
    LDA L07AB26.w,X
    CMP $01
    BNE L0799E3
    LDA (L07AB26.w + 1),X
    CMP $00
    BNE L0799E3
    LDA #1
    STA $09
    BNE L0799E8
L0799E3:
    INY
    BPL L0799B7
L0799E6:
    CLC
    RTS

L0799E8:
    LDA (L07AB26.w + 3),X
    STA $7AF6
    BEQ L079A32
    STA $08
    LDA (L07AB26.w + 2),X
    ASL
    TAX
    LDA L07ABD3.w,X
    STA $00
    LDA (L07ABD3.w + 1),X
    STA $01
    LDX #0
    LDA $09
    BNE L079A1C
    LDY #0
L079A09:
    LDA ($00),Y
    STA $7AE2,X
    INY
    LDA ($00),Y
    STA $7AEC,X
    INY
    INX
    DEC $08
    BNE L079A09
    BEQ L079A32
L079A1C:
    LDA $08
    ASL
    TAY
    DEY
L079A21:
    LDA ($00),Y
    STA $7AEC,X
    DEY
    LDA ($00),Y
    STA $7AE2,X
    DEY
    INX
    DEC $08
    BNE L079A21
L079A32:
    SEC
    RTS

L079A34:
    LDA #0
    STA $05D5
    LDA $05BB
    SEC
    SBC #1
    ASL
    TAX
    LDA L0FEEF4.w,X
    STA $03
    LDA (L0FEEF4.w + 1),X
    STA $02
    JSR L07A132.w
    BCS L079A55
    LDA #1
    STA $05D5
L079A55:
    RTS

L079A56:
    CMP #2
    BCS L079A71
    TAX
    LDA $7A86,X
    CMP #28
    BEQ L079A7F
    LDA $6CC0,X
    CMP #11
    BEQ L079A7F
    CMP #13
    BEQ L079A7F
    LDA #128
    BNE L079A7C
L079A71:
    TAX
    LDA $7A86,X
    SEC
    SBC #48
    TAX
    LDA L079A80.w,X
L079A7C:
    STA $06D3
L079A7F:
    RTS

L079A80:
.db $80
.db $80
.db $80
.db $80
.db $80
.db $80
.db $40
.db $40
.db $40
.db $40
.db $80
.db $80
.db $80
.db $80
.db $80
.db $08
.db $80

L079A91:
    JSR L0793B7.w
    JSR L0FE783.w
    LDA #0
    STA $5E
    LDA $05BB
    JSR L079212.w
    BCC L079AB3
    LDX $05B8
    CPX #2
    BCC L079AAE
    LDA #29
    BNE L079AB0
L079AAE:
    LDA #28
L079AB0:
    STA $7A86,X
L079AB3:
    LDA $7AF8
    BEQ L079AC2
    LDA #1
    STA $06D3
    INC $8A
    INC $8A
    RTS

L079AC2:
    LDA $7AF6
    BNE L079ADA
    LDA $7B25
    STA $0506
    LDA $7B26
    STA $0507
    LDA #1
    STA $7AF8
    BNE L079AEC
L079ADA:
    LDX $7AF7
    LDA $7AE2,X
    STA $0506
    LDA $7AEC,X
    STA $0507
    INC $7AF7
L079AEC:
    LDA #0
    STA $7AE1
    INC $8A
    RTS

L079AF4:
    LDX $05B8
    LDA $7AE1
    BNE L079B4A
    LDA $0507
    CMP $6CAE,X
    BNE L079B10
    LDA $7ACF,X
    BNE L079B10
    LDA #1
    STA $7AE1
    BNE L079B4A
L079B10:
    BCS L079B2E
    LDA $7ACF,X
    CLC
    ADC #1
    STA $7ACF,X
    CMP #16
    BCC L079B27
    LDA #0
    STA $7ACF,X
    DEC $6CAE,X
L079B27:
    LDA #17
    STA $7ABD,X
    BNE L079B8F
L079B2E:
    LDA $7ACF,X
    CLC
    ADC #1
    STA $7ACF,X
    CMP #16
    BCC L079B43
    LDA #0
    STA $7ACF,X
    INC $6CAE,X
L079B43:
    LDA #51
    STA $7ABD,X
    BNE L079B8F
L079B4A:
    LDA $0506
    CMP $6C9C,X
    BNE L079B57
    LDA $7ACF,X
    BEQ L079B96
L079B57:
    BCS L079B75
    LDA $7ACF,X
    CLC
    ADC #1
    STA $7ACF,X
    CMP #16
    BCC L079B6E
    LDA #0
    STA $7ACF,X
    DEC $6C9C,X
L079B6E:
    LDA #68
    STA $7ABD,X
    BNE L079B8F
L079B75:
    LDA $7ACF,X
    CLC
    ADC #1
    STA $7ACF,X
    CMP #16
    BCC L079B8A
    LDA #0
    STA $7ACF,X
    INC $6C9C,X
L079B8A:
    LDA #34
    STA $7ABD,X
L079B8F:
    JSR L0793B7.w
    JSR L0FE783.w
    RTS

L079B96:
    LDA $7ABD,X
    AND #240
    STA $7ABD,X
    LDA #0
    STA $7ACF,X
    DEC $8A
    DEC $7AF6
    JMP L079A91.w

L079BAB:
    JSR L0793B7.w
    JSR L0FE783.w
    LDX $05B8
    LDA $6CC0,X
    STA $6D0B
    LDA $05BB
    STA $6CC0,X
    LDY $7477
    BNE L079BC8
    STX $05DD
L079BC8:
    LDA #48
    STA $7ABD,X
    LDA $7A86,X
    CMP #28
    BNE L079BD9
    LDA #32
    STA $7ABD,X
L079BD9:
    LDA #0
    STA $7ACF,X
    JSR L0795DB.w
    JSR L079D30.w
    INC $8A
    LDA #1
    STA $28
    JSR L0FC70D.w
    RTS

L079BEE:
    LDA #96
    JSR L0FF58A.w
    LDA $05B8
    CMP #2
    BCC L079C28
    JSR L079E5F.w
    LDX $05B8
    LDA #0
    STA $6CC0,X
    STA $6CF6,X
    STA $6C9C,X
    STA $6CAE,X
    LDA $05B8
    ASL
    TAX
    LDA $6CD2,X
    STA $00
    LDA $6CD3,X
    STA $01
    LDY #5
    LDA #0
L079C21:
    STA ($00),Y
    DEY
    BPL L079C21
    BMI L079C48
L079C28:
    LDA $05BB
    STA $7434
    LDA #0
    STA $059C
    STA $05BB
    LDA #21
    STA $8A
    RTS

L079C3B:
    JSR L0793B7.w
    JSR L079198.w
    LDA $05BB
    CMP #49
    BCS L079BEE
L079C48:
    LDX #1
L079C4A:
    LDA $6CC0,X
    BEQ L079C59
    LDY #13
L079C51:
    CMP $6CC2,Y
    BEQ L079CB8
    DEY
    BPL L079C51
L079C59:
    DEX
    BPL L079C4A
    LDA #0
    STA $7447
    STA $2D
    LDA $7477
    EOR #1
    STA $7477
    JSR L07A1DF.w
    LDA $7477
    BNE L079C76
    JSR L0FCA1D.w
L079C76:
    LDX $6D0E
    LDA $6CF6,X
    BEQ L079C83
    LDA $6D90,X
    BEQ L079C8C
L079C83:
    LDA $6D0E
    EOR #1
    STA $6D0E
    TAX
L079C8C:
    JSR L079CD0.w
    LDA $6C9C,X
    STA $0581
    LDA $6CAE,X
    STA $0580
    LDA $95
    STA $0506
    LDA $94
    STA $0507
    LDA #0
    STA $05B6
    LDA #2
    STA $2C
    LDA #8
    STA $8A
    RTS

L079CB3:
    LDA #2
    STA $8A
    RTS

L079CB8:
    LDA $6CC0,X
    STA $6D0A
    STA $7434
    LDA #1
    STA $7447
    LDA #0
    STA $059C
    LDA #19
    STA $8A
    RTS

L079CD0:
    LDA $7477
    BNE L079D2F
    LDA $6E5C
    AND #2
    BEQ L079D2F
    LDA $6D91
    CMP #2
    BNE L079D2F
    LDA #32
    STA $33
L079CE7:
    LDA $33
    BEQ L079CF4
    JSR L0FC336.w
    JSR L0FC70D.w
    JMP L079CE7.w

L079CF4:
    LDA #1
    JSR L0FC9BD.w
    LDA #4
    STA $05B5
L079CFE:
    LDA $05B5
    BEQ L079D14
    LDA #2
    STA $4A
    LDA #4
    JSR L0FCA94.w
    INC $36
    JSR L0FC70D.w
    JMP L079CFE.w

L079D14:
    LDA #1
    STA $05B8
    STA $7479
    LDA #132
    STA $738F
    LDA #14
    STA $7390
    LDA #43
    STA $747A
    LDA #16
    STA $2A
L079D2F:
    RTS

L079D30:
    LDA $7477
    BNE L079D72
    LDA $6E5C
    AND #128
    BNE L079D72
    LDX $05B8
    LDA $6CC0,X
    CMP #36
    BNE L079D72
    LDA #0
    STA $059C
    LDA #16
    STA $35
    LDA $D0
    STA $24
    LDA $D1
    STA $25
    LDA #83
    JSR L0FF58A.w
L079D5C:
    JSR L0FC288.w
    JSR L078DE1.w
    JSR L079D73.w
    BCS L079D72
    JSR L0FC336.w
    INC $36
    JSR L0FC70D.w
    JMP L079D5C.w

L079D72:
    RTS

L079D73:
    LDA $059C
    JSR L0FC34C.w

.dw L079D85
.dw L079DB3
.dw L079E42
.dw L079DF6
.dw L079E1D
.dw L079E4B

L079D85:
    LDA $35
    BEQ L079DA6
    LDA $36
    AND #7
    TAX
    LDA $25
    CLC
    ADC L079E0D.w,X
    STA $D1
    LDA $24
    ADC L079E15.w,X
    CMP #240
    BCC L079DA1
    SBC #240
L079DA1:
    STA $D0
    JMP L079DB1.w

L079DA6:
    LDA $24
    STA $D0
    LDA $25
    STA $D1
    INC $059C
L079DB1:
    CLC
    RTS

L079DB3:
    LDA #7
    JSR L0FF58A.w
    LDX #4
    LDY #7
    LDA #94
    JSR L079DCA.w
    LDA #7
    STA $35
    INC $059C
    CLC
    RTS

L079DCA:
    STX $0F
    STY $0E
    STA $10
    LDA $0F
    STA $05
    LDA $0E
    STA $04
    LDA $10
    JSR L0FD611.w
    LDA $0F
    STA $05
    LDA $0E
    STA $04
    LDA $10
    JSR L0FD67F.w
    LDA $0E
    JSR L0FCEBF.w
    LDA $10
    LDY $0F
    STA ($70),Y
    RTS

L079DF6:
    LDA #7
    JSR L0FF58A.w
    LDX #4
    LDY #8
    LDA #95
    JSR L079DCA.w
    LDA #7
    STA $35
    INC $059C
    CLC
    RTS

L079E0D:
.db $00
.db $02
.db $06
.db $01
.db $05
.db $01
.db $05
.db $01

L079E15:
.db $00
.db $03
.db $00
.db $05
.db $05
.db $02
.db $07
.db $04

L079E1D:
    LDA #7
    JSR L0FF58A.w
    LDX #6
    LDY #8
    LDA #106
    JSR L079DCA.w
    LDX #7
    LDY #8
    LDA #108
    JSR L079DCA.w
    LDX #8
    LDY #8
    LDA #109
    JSR L079DCA.w
    INC $059C
    CLC
    RTS

L079E42:
    LDA $35
    BNE L079E49
    INC $059C
L079E49:
    CLC
    RTS

L079E4B:
    LDA #1
    STA $6D99
    LDA #33
    ORA $6D8F
    STA $6D8F
    LDA #0
    STA $059C
    SEC
    RTS

L079E5F:
    LDA $7478
    BEQ L079E6F
    LDA #0
    STA $059C
    LDA #33
    STA $8A
    PLA
    PLA
L079E6F:
    RTS

L079E70:
    JSR L0793B7.w
    JSR L0FE783.w
    LDA #0
    STA $3D
    JSR L0FE674.w
    LDA $059C
    JSR L0FC34C.w

.dw L079E8D
.dw L079EC4
.dw L079FC2
.dw L079FD3
.dw L079EBC

L079E8D:
    LDA $6D0A
    SEC
    SBC #1
    ASL
    TAX
    LDA L0FEEF4.w,X
    STA $0581
    LDA (L0FEEF4.w + 1),X
    STA $0580
    LDA $95
    STA $0506
    LDA $94
    STA $0507
    LDA #0
    STA $05B6
    LDA $8A
    STA $2C
    LDA #8
    STA $8A
    INC $059C
    RTS

L079EBC:
    LDA #0
    STA $059C
    INC $8A
    RTS

L079EC4:
    LDA #3
    STA $35
    JSR L079EDD.w
    LDA $7477
    BEQ L079ED9
    LDA #55
    JSR L0FE6B8.w
    LDA #32
    STA $35
L079ED9:
    INC $059C
    RTS

L079EDD:
    LDA #0
    STA $05FC
    LDY #5
    LDA #255
L079EE6:
    STA $6D10,Y
    DEY
    BPL L079EE6
    LDA $6D0A
    STA $00
    LDY #0
    LDX #2
L079EF5:
    LDA $6CC0,X
    CMP $00
    BNE L079F04
    TXA
    SEC
    SBC #2
    STA $6D14,Y
    INY
L079F04:
    INX
    CPX #16
    BCC L079EF5
    STY $6D13
    LDY #0
    LDX #0
L079F10:
    LDA $6CC0,X
    CMP $00
    BNE L079F1C
    TXA
    STA $6D11,Y
    INY
L079F1C:
    INX
    CPX #2
    BCC L079F10
    STY $6D10
    LDA $6D10
    CMP #2
    BNE L079F39
    LDA $6D11
    BNE L079F39
    LDX $6D12
    STA $6D12
    STX $6D11
L079F39:
    LDA $6D13
    CMP #2
    BNE L079F7C
    LDA $6D14
    CLC
    ADC #2
    ASL
    TAX
    LDA $6CD2,X
    STA $00
    LDA $6CD3,X
    STA $01
    LDA $6D15
    CLC
    ADC #2
    ASL
    TAX
    LDA $6CD2,X
    STA $02
    LDA $6CD3,X
    STA $03
    LDY #2
    LDA ($00),Y
    CMP ($02),Y
    BCC L079F79
    LDA $6D14
    TAX
    LDA $6D15
    STA $6D14
    STX $6D15
L079F79:
    JSR L079F7D.w
L079F7C:
    RTS

L079F7D:
    LDA $6DB2
    AND #1
    BEQ L079FC1
    LDA $6D0A
    CMP #34
    BNE L079FC1
    LDY #1
    LDA ($00),Y
    STA $04
    LDA ($02),Y
    STA $05
    CMP #35
    BEQ L079FB3
    CMP #34
    BNE L079FC1
    LDA $04
    CMP #35
    BNE L079FC1
    LDA $6D14
    TAX
    LDA $6D15
    STA $6D14
    STX $6D15
    JMP L079FB9.w
L079FB3:
    LDA $04
    CMP #34
    BNE L079FC1
L079FB9:
    LDA #1
    STA $05FC
    STA $6D13
L079FC1:
    RTS

L079FC2:
    LDA $1B
    AND #128
    BNE L079FCC
    LDA $35
    BNE L079FD2
L079FCC:
    JSR L0FE696.w
    INC $059C
L079FD2:
    RTS

L079FD3:
    LDA #4
    STA $059C
    RTS

L079FD9:
    LDA $059C
    JSR L0FC34C.w

L079FDF:
.dw L07A058
.dw L079FE3

L079FE3:
    LDA $05B5
    BEQ L079FF1
    LDA #2
    STA $4A
    LDA #4
    JMP L0FCA94.w

L079FF1:
    LDA #16
    STA $2A
    LDA #0
    STA $7479
    STA $8A
    STA $059C
    RTS

L07A000:
    LDA $059C
    JSR L0FC34C.w

.dw L07A00E
.dw L07A031
.dw L07A058
.dw L07A066

L07A00E:
    LDA #2
    JSR L0FC9BD.w
    LDA #128
    STA $28
    LDA #29
    JSR L0FCA48.w
    JSR L0FCA50.w
    LDA #5
    STA $35
    LDA #0
    STA $05E5
    LDA #255
    STA $05E4
    INC $059C
    RTS

L07A031:
    JSR L0FC288.w
    JSR L0FD81E.w
    LDA #1
    STA $92
    LDA #0
    STA $0589
    STA $3D
    JSR L0FD499.w
    LDA $36
    AND #15
    BNE L07A050
    LDA #1
    JSR L0FF58A.w
L07A050:
    LDA $35
    BNE L07A057
    INC $059C
L07A057:
    RTS

L07A058:
    LDA #1
    JSR L0FC9BD.w
    LDA #4
    STA $05B5
    INC $059C
    RTS

L07A066:
    LDA $05B5
    BEQ L07A074
    LDA #2
    STA $4A
    LDA #4
    JMP L0FCA94.w

L07A074:
    INC $2A
    LDA #0
    STA $05F4
    STA $8A
    STA $059C
    RTS

L07A081:
    JSR L0793B7.w
    LDA $05E7
    STA $05B8
    LDA $05E8
    JSR L079212.w
    BCS L07A098
    LDA $05B8
    JSR L079A56.w
L07A098:
    LDA $05E8
    STA $74B5
    LDX $05E7
    CPX #2
    BCS L07A0AA
    LDA #1
    STA $6D28,X
L07A0AA:
    LDA #0
    STA $05BA
    JSR L07A0F3.w
    JSR L0799A5.w
    LDA #0
    STA $7AF8
    STA $7AF7
    LDA #24
    STA $8A
    RTS

L07A0C2:
    JSR L0793B7.w
    LDX $05E7
    LDA $6CC0,X
    STA $6D16,X
    STA $6D0B
    LDA $05E8
    STA $6CC0,X
    STA $05BB
    LDA #48
    STA $7ABD,X
    LDA $7A86,X
    CMP #28
    BNE L07A0EB
    LDA #32
    STA $7ABD,X
L07A0EB:
    LDA #0
    STA $05E9
    INC $8A
    RTS

L07A0F3:
    LDY $05BA
L07A0F6:
    LDA $74B5,Y
    BPL L07A103
    LDA #0
    STA $05BA
    TAY
    BEQ L07A0F6
L07A103:
    ASL
    TAX
    DEX
    DEX
    LDA L0FEEF4.w,X
    STA $03
    LDA (L0FEEF4.w + 1),X
    STA $02
    JSR L07A132.w
    BCS L07A131
    LDA $05
    STA $7B25
    LDA $04
    STA $7B26
    LDY $05BA
    STY $7ABC
    LDA $74B5,Y
    STA $05BB
    LDA #10
    STA $8A
    CLC
L07A131:
    RTS

L07A132:
    LDY #0
L07A134:
    LDA L07A14F.w,Y
    CLC
    ADC $03
    STA $05
    LDA L07A153.w,Y
    CLC
    ADC $02
    STA $04
    JSR L0794D5.w
    BCC L07A14E
    INY
    CPY #2
    BCC L07A134
L07A14E:
    RTS

L07A14F:
.db $00 $01 $00 $01

L07A153:
.db $00 $00 $01 $01

L07A157:
    JSR L0793B7.w
    JSR L0FE783.w
    LDA $059C
    JSR L0FC34C.w

.dw L07A16B
.dw L07A17B
.dw L07A198
.dw L07A1AA

L07A16B:
    LDX $05E3
    LDA #2
    STA $7A76,X
    LDA #8
    STA $35
    INC $059C
    RTS

L07A17B:
    LDA $1C
    BNE L07A183
    LDA $35
    BNE L07A197
L07A183:
    LDX $05E3
    LDA #0
    STA $7A76,X
    LDA #54
    JSR L0FE6B8.w
    LDA #16
    STA $35
    INC $059C
L07A197:
    RTS

L07A198:
    JSR L0FE674.w
    LDA $1C
    BNE L07A1A3
    LDA $35
    BNE L07A1A9
L07A1A3:
    JSR L0FE696.w
    INC $059C
L07A1A9:
    RTS

L07A1AA:
    JSR L0FE674.w
    LDA #1
    STA $05E9
    LDA $05E3
    CLC
    ADC #2
    STA $05E7
    TAX
    LDY #8
    LDA $6CC0,X
L07A1C1:
    CMP L0FF11B.w,Y
    BEQ L07A1CB
    DEY
    BPL L07A1C1
    LDY #0
L07A1CB:
    LDA L0FF124.w,Y
    STA $05E8
    LDA #4
    STA $2D
    LDA #23
    STA $8A
    LDA #0
    STA $059C
    RTS

L07A1DF:
    PHA
    TYA
    PHA
    LDY #1
    LDA #0
L07A1E6:
    STA $6D28,Y
    DEY
    BPL L07A1E6
    PLA
    TAY
    PLA
    RTS

L07A1F0:
    JSR L078DE1.w
    JSR L0FE674.w
    LDA #59
    JSR L0FE6B8.w
    LDA #2
    STA $2C
    LDA #1
    JSR L0FC9BD.w
    INC $8A
    RTS

L07A207:
    JSR L078DE1.w
    LDA #1
    STA $05EF
    LDA #2
    STA $05EE
    LDA #1
    JSR L0FC9BD.w
    INC $8A
    RTS

L07A21C:
    JSR L07A39A.w
    LDA $05EF
    BNE L07A246
    LDA #15
    STA $4A
    LDA #8
    JSR L0FCA94.w
    LDA #0
    STA $05D8
    STA $2C
    STA $059C
    LDA #2
    STA $5E
    JSR L0793B7.w
    LDA #1
    STA $5E
    LDA #3
    STA $8A
L07A246:
    RTS

L07A247:
    JSR L078DE1.w
    JSR L0FE696.w
    LDA #1
    STA $05EF
    LDA #3
    STA $05EE
    LDA #1
    JSR L0FC9BD.w
    INC $8A
    RTS

L07A25F:
    JSR L07A39A.w
    LDA $05EF
    BNE L07A287
    LDA #0
    STA $05D8
    STA $059C
    LDA #15
    STA $4A
    LDA #8
    JSR L0FCA94.w
    LDA #2
    STA $5E
    JSR L0793B7.w
    LDA #1
    STA $5E
    LDA #3
    STA $8A
L07A287:
    RTS

L07A288:
    JSR L078DE1.w
    JSR L0FE696.w
    LDA #1
    STA $05EF
    LDA #1
    STA $05EE
    LDA #1
    JSR L0FC9BD.w
    INC $8A
    RTS

L07A2A0:
    JSR L07A39A.w
    LDA $05EF
    BNE L07A2C1
    LDA #0
    STA $05D8
    STA $2C
    STA $059C
    LDA #2
    STA $5E
    JSR L0793B7.w
    LDA #1
    STA $5E
    LDA #3
    STA $8A
L07A2C1:
    RTS

L07A2C2:
    JSR L078DE1.w
    JSR L0FE674.w
    LDA $059C
    JSR L0FC34C.w

.dw L07A2EB
.dw L07A2DE
.dw L07A2D4

L07A2D4:
    LDA #2
    STA $8A
    LDA #0
    STA $059C
    RTS

L07A2DE:
    LDA $1A
    AND #192
    BEQ L07A2EA
    JSR L0FE696.w
    INC $059C
L07A2EA:
    RTS

L07A2EB:
    LDA $94
    STA $10
    LDA $95
    STA $11
    LDA $94
    JSR L0FCEBF.w
    LDY $95
    LDA ($70),Y
    STA $0E
    LDX #14
L07A300:
    LDA L07A359.w,X
    CMP $0E
    BEQ L07A30C
    DEX
    BPL L07A300
    BMI L07A30E
L07A30C:
    DEC $11
L07A30E:
    LDX #7
L07A310:
    LDA L07A368.w,X
    CMP $0E
    BEQ L07A31C
    DEX
    BPL L07A310
    BMI L07A31E
L07A31C:
    INC $10
L07A31E:
    LDX #0
    LDA #244
    STA $00
    LDA #238
    STA $01
L07A328:
    LDY #0
    LDA ($00),Y
    CMP $11
    BNE L07A337
    INY
    LDA ($00),Y
    CMP $10
    BEQ L07A346
L07A337:
    INX
    LDA #2
    JSR L0FC379.w
    CPX #80
    BCC L07A328
    LDA #2
    STA $8A
    RTS

L07A346:
    INX
    STX $05BB
    LDA #44
    JSR L0FE6B8.w
    LDA #64
    STA $77
    STA $76
    INC $059C
    RTS

L07A359:
.db $81
.db $83
.db $85
.db $87
.db $89
.db $8D
.db $8F
.db $91
.db $93
.db $95
.db $98
.db $9A
.db $9F
.db $A1
.db $7F

L07A368:
.db $8C
.db $8D
.db $90
.db $91
.db $92
.db $93
.db $94
.db $95

L07A370:
    JSR L078DE1.w
    JSR L0FE674.w
    LDA $059C
    JSR L0FC34C.w

.dw L07A382
.dw L07A2DE
.dw L07A390

L07A382:
    LDA #128
    STA $06D1
    LDA #69
    JSR L0FE6B8.w
    INC $059C
    RTS

L07A390:
    LDA #0
    STA $059C
    LDA #3
    STA $8A
    RTS

L07A39A:
    LDA $8A
    STA $05ED
    LDA $05EE
    STA $8A
    LDA #4
    STA $4A
    LDA #13
    JSR L0FCA94.w
    LDA $8A
    STA $05EE
    LDA $05ED
    STA $8A
    RTS

L07A3B8:
    JSR L0FE674.w
    INC $8A
    RTS

L_PALETTES_07_UNK:
.dw L07A3C8
.dw L07A3EC
.dw L07A400
.dw L07A424
.dw L07A438

L07A3C8:
.db $3F $00 $20 $0F $20 $10 $1A $0F
.db $2B $0A $1A $0F $28 $17 $1A $0F
.db $31 $1A $22 $0F $20 $36 $0F $0F
.db $11 $36 $0F $0F $15 $36 $0F $0F
.db $25 $36 $0F $00

L07A3EC:
.db $3F $10 $10 $0F $20 $21 $12 $0F
.db $37 $27 $17 $0F $35 $25 $15 $0F
.db $18 $36 $0F $00

L07A400:
.db $3F $00 $20 $0F $20 $10 $00 $0F
.db $20 $10 $00 $0F $20 $10 $00 $0F
.db $20 $10 $00 $0F $20 $10 $00 $0F
.db $20 $10 $00 $0F $20 $10 $00 $0F
.db $20 $10 $00 $00

L07A424:
.db $3F $10 $10 $0F $20 $21 $11 $0F
.db $0A $0B $0C $0F $11 $36 $0F $0F
.db $16 $36 $00 $00

L07A438:
.db $3F $00 $10 $0F $20 $10 $1A $0F
.db $2B $0A $1A $0F $28 $17 $1A $0F
.db $31 $1A $22 $00

.dw L07A454
.dw L07A45D
.dw L07A466
.dw L07A46F

L07A454:
.db $02 $04 $64 $40 $08 $04 $65 $40
.db $00

L07A45D:
.db $02 $04 $64 $00 $00 $04 $65 $00
.db $08

L07A466:
.db $02 $00 $67 $80 $04 $08 $66 $80
.db $04

L07A46F:
.db $02 $00 $66 $00 $04 $08 $67 $00
.db $04

L07A478:
.db $16
.db $17

L07A47A:
.db $1D
.db $1C

L07A47C:
    LDA #0
    STA $7AFB
    JSR L07A5C8.w
    LDA $6D92
    AND #192
    BNE L07A48E
    JMP L07A4EE.w

L07A48E:
    CMP #192
    BEQ L07A4EE
    JSR L0FC39A.w
    LSR
    LSR
    TAX
    DEX
    STX $10
    LDA #0
    STA $7B10
L07A4A0:
    LDX $7B10
    LDA $6CF8,X
    BEQ L07A4E4
    LDA $7B10
    CLC
    ADC #2
    ASL
    TAX
    LDA $6CD2,X
    STA $0E
    LDA $6CD3,X
    STA $0F
    LDY #1
    LDA ($0E),Y
    LDX $10
    CMP L07A478.w,X
    BNE L07A4E4
    LDX $10
    LDA L07A47A.w,X
    STA $0570
    JSR L0FFACC.w
    LDA $6D92
    ORA #192
    STA $6D92
    LDA #61
    STA $7AFB
    LDA $7B10
    STA $7AFA
    RTS

L07A4E4:
    INC $7B10
    LDA $7B10
    CMP #13
    BCC L07A4A0
L07A4EE:
    LDA #0
    STA $7B10
L07A4F3:
    LDX $7B10
    LDA $6CF8,X
    BEQ L07A540
    LDA $7B11,X
    BEQ L07A540
    LDA $6CC2,X
    SEC
    SBC #1
    ASL
    TAX
    LDA L0FEF94.w,X
    STA $00
    LDA (L0FEF94.w + 1),X
    STA $01
    LDY #0
L07A514:
    LDA ($00),Y
    BMI L07A540
    STA $02
    LDX #1
L07A51C:
    LDA $6CF6,X
    BEQ L07A528
    LDA $6CC0,X
    CMP $02
    BEQ L07A52F
L07A528:
    DEX
    BPL L07A51C
    INY
    JMP L07A514.w

L07A52F:
    LDA $7B10
    STA $7AFA
    LDA ($00),Y
    STA $7AFB
    RTS

L07A53B:
    LDA #0
    STA $7AFB
L07A540:
    INC $7B10
    LDA $7B10
    CMP #13
    BCC L07A4F3
    LDA $36
    STA $00
    LDA #13
    STA $01
    JSR L0FC6C9.w
    LDA $01
    STA $0F
    LDA #7
    STA $7B0F
L07A55E:
    LDA $7B0F
    ASL
    TAX
    LDA L0FE360.w,X
    STA $00
    LDA (L0FE360.w + 1),X
    STA $01
    LDY #0
L07A56F:
    LDA ($00),Y
    BMI L07A5A2
    STA $02
    LDX $0F
    LDA #13
    STA $0E
L07A57B:
    LDA $6CF8,X
    BEQ L07A594
    LDA $7B11,X
    BEQ L07A594
    LDA $6CC2,X
    CMP $02
    BNE L07A594
    JSR L07A5B9.w
    CMP $7B11,X
    BCC L07A5A5
L07A594:
    INX
    CPX #13
    BCC L07A59B
    LDX #0
L07A59B:
    DEC $0E
    BNE L07A57B
    INY
    BPL L07A56F
L07A5A2:
    JMP L07A5B1.w

L07A5A5:
    INY
    LDA ($00),Y
    BMI L07A5A2
    STA $7AFB
    STX $7AFA
    RTS

L07A5B1:
    DEC $7B0F
    BPL L07A55E
    JMP L07A5C7.w

L07A5B9:
    LDA $36
    AND #3
    STA $10
L07A5BF:
    JSR L0FC04E.w
    DEC $10
    BPL L07A5BF
    RTS

L07A5C7:
    RTS

L07A5C8:
    LDX #0
L07A5CA:
    TXA
    CLC
    ADC #2
    ASL
    TAY
    LDA $6CD2,Y
    STA $00
    LDA $6CD3,Y
    STA $01
    LDA $6CF8,X
    BEQ L07A5E3
    LDY #2
    LDA ($00),Y
L07A5E3:
    STA $7B11,X
    INX
    CPX #13
    BCC L07A5CA
    RTS

L07A5EC:
    LDA $05FB
    JSR L0FC34C.w

.dw L07A5FE
.dw L07A6C2
.dw L07A767
.dw L07A83F
.dw L07A8CD
.dw L07A956

L07A5FE:
    LDA $747C
    BNE L07A604
    RTS

L07A604:
    LDA $7440
    SEC
    SBC $743D
    BCC L07A638
    CMP #12
    BCC L07A638
    SBC #2
    STA $6B
    LDA #83
    JSR L0FF58A.w
    LDA $7441
    STA $6C
    LDA #0
    STA $11
    LDA #67
    STA $10
    JSR L07A64B.w
    INC $6B
    LDA $7441
    STA $6C
    LDA #1
    STA $11
    JSR L07A64B.w
L07A638:
    RTS

L07A639:
    LDA #6
    JSR L0FC068.w
    TAX
    LDA L07A645.w,X
    STA $10
    RTS

L07A645:
.db $40 $41 $42 $4B $4B $4B

L07A64B:
    LDA $11
    BEQ L07A652
    JSR L07A639.w
L07A652:
    JSR L07A65A.w
    DEC $6C
    BPL L07A64B
    RTS

L07A65A:
    JSR L07A684.w
    BCC L07A660
    RTS

L07A660:
    LDY $6C
    LDA $10
    STA ($70),Y
    LDA $6C
    STA $05
    LDA $6B
    STA $04
    LDA $10
    STA $0B
    JSR L07A6B9.w
    LDA $6C
    STA $05
    LDA $6B
    STA $04
    LDA $10
    STA $0B
    JMP L07A6B5.w

L07A684:
    LDA $6B
    JSR L0FCEBF.w
    LDY $6C
    LDA ($70),Y
    CMP #46
    BCC L07A699
    CMP #114
    BCC L07A6B3
    CMP #158
    BCS L07A6B3
L07A699:
    LDA $6B
    STA $02
    LDA $6C
    STA $03
    JSR L0FF280.w
    BCC L07A6AB
    JSR L0FF28B.w
    BCS L07A6B3
L07A6AB:
    LDY #15
    LDA $10
    STA ($00),Y
    SEC
    RTS
L07A6B3:
    CLC
    RTS

L07A6B5:
    LDA #7
    BNE L07A6BB
L07A6B9:
    LDA #13
L07A6BB:
    STA $4A
    LDA #6
    JMP L0FCA94.w

L07A6C2:
    JSR L0FF2CB.w
    LDA #218
    STA $0A
    JSR L07A75D.w
    BCS L07A6DA
    JSR L0FF2D4.w
    LDA #113
    STA $0A
    JSR L07A75D.w
    BCC L07A747
L07A6DA:
    LDA $7440
    LSR
    STA $6B
    JSR L0FCEBF.w
    LDY #0
    LDA ($70),Y
    CMP #67
    BEQ L07A747
    LDA #83
    JSR L0FF58A.w
    LDA #0
    STA $10
    LDA #19
    STA $4A
    LDA #6
    JSR L0FCA94.w
    LDA $7440
    LSR
    STA $6B
    LDA $7441
    STA $6C
    LDA #0
    STA $11
    LDA #67
    STA $10
    JSR L07A64B.w
    LDA #1
    STA $11
    INC $6B
    LDA $7441
    STA $6C
    JSR L07A64B.w
    LDA $7441
    STA $6C
    INC $6B
    JSR L07A64B.w
    LDA $7441
    STA $6C
    INC $6B
    JSR L07A64B.w
    LDA #0
    STA $11
    LDA #68
    STA $10
    LDA $7441
    STA $6C
    INC $6B
    JSR L07A64B.w
L07A747:
    RTS

L07A748:
    LDY #18
    LDA ($00),Y
    CMP #255
    BEQ L07A758
    LDY #15
    LDA ($00),Y
    CMP $0A
    BEQ L07A765
L07A758:
    LDA #21
    JSR L0FC379.w
L07A75D:
    LDY #0
    LDA ($00),Y
    BNE L07A748
    CLC
    RTS

L07A765:
    SEC
    RTS

L07A767:
    LDA $747C
    BEQ L07A786
    LDA $7440
    STA $10
L07A771:
    LDA $10
    JSR L0FCEBF.w
    LDY $7441
L07A779:
    LDA ($70),Y
    CMP #218
    BEQ L07A787
    DEY
    BNE L07A779
    DEC $10
    BNE L07A771
L07A786:
    RTS

L07A787:
    STY $11
    LDA #5
    STA $08
L07A78D:
    LDA $7441
    JSR L0FC068.w
    CLC
    ADC #1
    STA $0F
    LDA $7440
    JSR L0FC068.w
    CLC
    ADC #1
    STA $0E
    JSR L0FCEBF.w
    LDY $0F
    LDA ($70),Y
    CMP #48
    BEQ L07A7BC
    CMP #208
    BEQ L07A7BC
    CMP #75
    BEQ L07A7BC
    DEC $08
    BNE L07A78D
    BEQ L07A786
L07A7BC:
    LDA $10
    STA $0511
    LDA $11
    STA $0510
    LDA #2
    STA $05E5
    LDA #11
    STA $4A
    LDA #6
    JSR L0FCA94.w
    LDA $10
    STA $04
    LDA $11
    STA $05
    LDA #242
    STA $0B
    JSR L07A6B9.w
    LDA $10
    STA $04
    LDA $11
    STA $05
    LDA #242
    STA $0B
    JSR L07A6B5.w
    LDA $10
    JSR L0FCEBF.w
    LDY $11
    LDA #242
    STA ($70),Y
    LDA $0E
    STA $0511
    LDA $0F
    STA $0510
    LDA #1
    STA $05E5
    LDA #11
    STA $4A
    LDA #6
    JSR L0FCA94.w
    LDA $0E
    STA $04
    LDA $0F
    STA $05
    LDA #218
    STA $0B
    JSR L07A6B9.w
    LDA $0E
    STA $04
    LDA $0F
    STA $05
    LDA #218
    STA $0B
    JSR L07A6B5.w
    LDA $0E
    JSR L0FCEBF.w
    LDY $0F
    LDA #218
    STA ($70),Y
L07A83E:
    RTS

L07A83F:
    LDA $747C
    BNE L07A83E
    LDA #174
    STA $7A
    LDA #103
    STA $7B
    LDA $36
    STA $37
    LDA #20
    JSR L0FC068.w
    LDY #8
    CMP ($7A),Y
    BCC L07A8CC
    LDA #113
    STA $7DA9
    LDA #20
    STA $7446
    LDA #17
    STA $4A
    LDA #6
    JSR L0FCA94.w
    LDA #15
    STA $4A
    LDA #6
    JSR L0FCA94.w
    LDA #23
    STA $4A
    LDA #6
    JSR L0FCA94.w
    LDA #128
    STA $28
    JSR L0FC70D.w
    LDY #18
    LDA #1
    STA ($7A),Y
    LDY #16
    LDA ($7A),Y
    STA $0511
    LDY #17
    LDA ($7A),Y
    STA $0510
    LDA #1
    STA $05E5
    LDA #11
    STA $4A
    LDA #6
    JSR L0FCA94.w
    LDY #17
    LDA ($7A),Y
    STA $0500
    LDY #16
    LDA ($7A),Y
    STA $0501
    LDY #15
    LDA ($7A),Y
    STA $6B
    LDA #21
    STA $4A
    LDA #6
    JSR L0FCA94.w
    LDY #15
    LDA $6B
    STA ($7A),Y
L07A8CC:
    RTS

L07A8CD:
    JSR L0FF2CB.w
    LDA #113
    STA $0A
    JSR L07A75D.w
    BCS L07A8E5
    JSR L0FF2D4.w
    LDA #113
    STA $0A
    JSR L07A75D.w
    BCC L07A94D
L07A8E5:
    LDA $36
    AND #3
    ASL
    STA $05FF
    LDX $05FF
    LDA L07A94E.w,X
    JSR L0FCEBF.w
    LDX $05FF
    LDY (L07A94E.w + 1),X
    LDA ($70),Y
    CMP #46
    BCC L07A94D
    CMP #114
    BCC L07A90A
    CMP #158
    BCC L07A94D
L07A90A:
    LDA #2
    STA $05E5
    LDA #10
    STA $4A
    LDA #6
    JSR L0FCA94.w
    LDX $05FF
    LDA L07A94E.w,X
    STA $0511
    LDA (L07A94E.w + 1),X
    STA $0510
    LDA #1
    STA $05E5
    LDA #11
    STA $4A
    LDA #6
    JSR L0FCA94.w
    LDX $05FF
    LDA L07A94E.w,X
    STA $0501
    LDA (L07A94E.w + 1),X
    STA $0500
    LDA #21
    STA $4A
    LDA #6
    JSR L0FCA94.w
L07A94D:
    RTS

L07A94E:
.db $12 $12
.db $0A $04
.db $12 $12
.db $0A $05

L07A956:
    LDA $747C
    BEQ L07A96C
    LDX #0
L07A95D:
    LDA L07A985.w,X
    CMP #255
    BEQ L07A96C
    CMP $7434
    BEQ L07A96D
    INX
    BPL L07A95D
L07A96C:
    RTS

L07A96D:
    LDA $743D
    CMP L07A989.w,X
    BNE L07A96C
    TXA
    ASL
    TAX
    LDA L07A98C.w,X
    STA $7C
    LDA (L07A98C.w + 1),X
    STA $7D
    JMP L07A9B2.w

L07A985:
.db $48
.db $4C
.db $3B
.db $FF

L07A989:
.db $04
.db $05
.db $02

L07A98C:
.dw L07A992
.dw L07A9AA
.dw L07A9A2

L07A992:
.db $07
.db $06
.db $04
.db $03
.db $D0
.db $D0
.db $D0
.db $D0
.db $D0
.db $D0
.db $D0
.db $D0
.db $D0
.db $DA
.db $D0
.db $D0

L07A9A2:
.db $07
.db $03
.db $02
.db $02
.db $D0
.db $D0
.db $D5
.db $D0

L07A9AA:
.db $04
.db $08
.db $02
.db $02
.db $D0
.db $D0
.db $D5
.db $D0

L07A9B2:
    LDY #0
    LDA ($7C),Y
    STA $11
    INY
    LDA ($7C),Y
    STA $6B
    INY
    LDA ($7C),Y
    STA $0F
    INY
    LDA ($7C),Y
    STA $0E
    INY
    STY $0C
L07A9CA:
    LDA #6
    JSR L0FF58A.w
    LDA $0F
    STA $0D
    LDA $11
    STA $6C
L07A9D7:
    LDY $0C
    LDA ($7C),Y
    STA $10
    INC $0C
    JSR L07A65A.w
    INC $6C
    DEC $0D
    BNE L07A9D7
    INC $6B
    DEC $0E
    BNE L07A9CA
    RTS

L07A9EF:
.dw L07AA8F
.dw L07AA91
.dw L07AA94
.dw L07AA96
.dw L07AA99
.dw L07AA9B
.dw L07AA9E
.dw L07AAA1
.dw L07AAA3
.dw L07AAA5
.dw L07AAA7
.dw L07AAAA
.dw L07AAAD
.dw L07AAAF
.dw L07AAB1
.dw L07AAB3
.dw L07AAB5
.dw L07AAB7
.dw L07AAB8
.dw L07AABB
.dw L07AABF
.dw L07AAC3
.dw L07AAC5
.dw L07AAC7
.dw L07AACA
.dw L07AACD
.dw L07AACF
.dw L07AAD1
.dw L07AAD4
.dw L07AAD7
.dw L07AADA
.dw L07AADC
.dw L07AADF
.dw L07AAE2
.dw L07AAE4
.dw L07AAE6
.dw L07AAE8
.dw L07AAEB
.dw L07AAED
.dw L07AAF0
.dw L07AAF2
.dw L07AAF4
.dw L07AAF6
.dw L07AAF8
.dw L07AAFA
.dw L07AAFC
.dw L07AAFE
.dw L07AB00
.dw L07AB02
.dw L07AB03
.dw L07AB04
.dw L07AB05
.dw L07AB07
.dw L07AB08
.dw L07AB0A
.dw L07AB0B
.dw L07AB0C
.dw L07AB0F
.dw L07AB10
.dw L07AB11
.dw L07AB12
.dw L07AB13
.dw L07AB14
.dw L07AB15
.dw L07AB16
.dw L07AB17
.dw L07AB18
.dw L07AB19
.dw L07AB1A
.dw L07AB1C
.dw L07AB1D
.dw L07AB1E
.dw L07AB1F
.dw L07AB20
.dw L07AB21
.dw L07AB22
.dw L07AB23
.dw L07AB24
.dw L07AB25
.dw L07AB25

L07AA8F:
.db $02 $01

L07AA91:
.db $08 $02 $01

L07AA94:
.db $04 $08

L07AA96:
.db $01 $08 $04

L07AA99:
.db $01 $08

L07AA9B:
.db $02 $01 $04

L07AA9E:
.db $08 $01 $04

L07AAA1:
.db $02 $04

L07AAA3:
.db $04 $01

L07AAA5:
.db $04 $08

L07AAA7:
.db $01 $02 $04

L07AAAA:
.db $01 $02 $08

L07AAAD:
.db $08 $04

L07AAAF:
.db $04 $02

L07AAB1:
.db $02 $01

L07AAB3:
.db $04 $08

L07AAB5:
.db $02 $04

L07AAB7:
.db $01

L07AAB8:
.db $04 $08 $02

L07AABB:
.db $02 $08 $04 $01

L07AABF:
.db $01 $08 $04 $02

L07AAC3:
.db $01 $02

L07AAC5:
.db $01 $02

L07AAC7:
.db $01 $04 $02

L07AACA:
.db $02 $04 $01

L07AACD:
.db $08 $02

L07AACF:
.db $01 $02

L07AAD1:
.db $08 $01 $04

L07AAD4:
.db $02 $01 $08

L07AAD7:
.db $02 $08 $04

L07AADA:
.db $02 $01

L07AADC:
.db $02 $04 $08

L07AADF:
.db $08 $02 $04

L07AAE2:
.db $08 $01

L07AAE4:
.db $04 $08

L07AAE6:
.db $04 $01

L07AAE8:
.db $08 $02 $01

L07AAEB:
.db $02 $01

L07AAED:
.db $01 $02 $08

L07AAF0:
.db $01 $04

L07AAF2:
.db $08 $04

L07AAF4:
.db $08 $04

L07AAF6:
.db $08 $04

L07AAF8:
.db $04 $02

L07AAFA:
.db $02 $01

L07AAFC:
.db $01 $08

L07AAFE:
.db $04 $02

L07AB00:
.db $02 $01

L07AB02:
.db $01

L07AB03:
.db $02

L07AB04:
.db $01

L07AB05:
.db $08 $04

L07AB07:
.db $08

L07AB08:
.db $08 $01

L07AB0A:
.db $02

L07AB0B:
.db $08

L07AB0C:
.db $08 $02 $01

L07AB0F:
.db $01

L07AB10:
.db $01

L07AB11:
.db $02

L07AB12:
.db $02

L07AB13:
.db $02

L07AB14:
.db $04

L07AB15:
.db $04

L07AB16:
.db $01

L07AB17:
.db $01

L07AB18:
.db $01

L07AB19:
.db $02

L07AB1A:
.db $08 $04

L07AB1C:
.db $02

L07AB1D:
.db $02

L07AB1E:
.db $02

L07AB1F:
.db $02

L07AB20:
.db $01

L07AB21:
.db $02

L07AB22:
.db $02

L07AB23:
.db $04

L07AB24:
.db $04

L07AB25:
.db $04

L07AB26: ; dunno how long is the array
.db $02 $03 $00 $01
.db $03 $04 $01 $03
.db $04
.db $05
.db $02
.db $03
.db $05
.db $06
.db $03
.db $02
.db $06
.db $07
.db $04
.db $02
.db $09
.db $0A
.db $05
.db $02
.db $0A
.db $0B
.db $06
.db $01
.db $0C
.db $0D
.db $07
.db $01
.db $0C
.db $0E
.db $08
.db $02
.db $10
.db $11
.db $09
.db $02
.db $11
.db $12
.db $0A
.db $02
.db $11
.db $1B
.db $0B
.db $02
.db $13
.db $14
.db $0C
.db $04
.db $14
.db $19
.db $0D
.db $04
.db $19
.db $1A
.db $0E
.db $03
.db $15
.db $16
.db $0F
.db $03
.db $15
.db $17
.db $10
.db $03
.db $17
.db $18
.db $11
.db $03
.db $16
.db $18
.db $12
.db $02
.db $1C
.db $1D
.db $13
.db $02
.db $1D
.db $1E
.db $14
.db $02
.db $1E
.db $1F
.db $15
.db $03
.db $1F
.db $20
.db $16
.db $03
.db $20
.db $21
.db $29
.db $04
.db $21
.db $22
.db $17
.db $04
.db $21
.db $26
.db $18
.db $03
.db $26
.db $27
.db $19
.db $03
.db $27
.db $28
.db $1A
.db $02
.db $23
.db $24
.db $1C
.db $02
.db $24
.db $25
.db $1D
.db $02
.db $25
.db $29
.db $1E
.db $04
.db $29
.db $2A
.db $1F
.db $04
.db $2B
.db $2C
.db $20
.db $04
.db $2C
.db $2D
.db $21
.db $04
.db $2E
.db $2F
.db $23
.db $02
.db $07
.db $39
.db $24
.db $02
.db $3F
.db $2B
.db $25
.db $05
.db $1A
.db $3E
.db $26
.db $04
.db $45
.db $23
.db $27
.db $02
.db $30
.db $4D
.db $28
.db $03
.db $16
.db $3D
.db $12
.db $02
.db $17
.db $3D
.db $11
.db $03
.db $00
.db $00
.db $00
.db $00
.db $FF

L07ABD3:
.dw L07AC2B
.dw L07AC2D
.dw L07AC33
.dw L07AC39
.dw L07AC3D
.dw L07AC41
.dw L07AC45
.dw L07AC49
.dw L07AC4B
.dw L07AC4F
.dw L07AC53
.dw L07AC57
.dw L07AC5B
.dw L07AC63
.dw L07AC6B
.dw L07AC71
.dw L07AC77
.dw L07AC7D
.dw L07AC83
.dw L07AC87
.dw L07AC8B
.dw L07AC8F
.dw L07AC95
.dw L07AC9B
.dw L07ACA3
.dw L07ACA9
.dw L07ACAF
.dw L07ACB3
.dw L07ACB7
.dw L07ACBB
.dw L07ACBF
.dw L07ACC7
.dw L07ACCF
.dw L07ACD7
.dw L07ACDF
.dw L07ACDF
.dw L07ACE3
.dw L07ACE7
.dw L07ACF1
.dw L07ACF9
.dw L07ACFD
.dw L07AD03
.dw L07AD0B
.dw L07AD0B

L07AC2B:
.db $0A $29

L07AC2D:
.db $0A $27 $0A $25 $0B $25

L07AC33:
.db $0B $24 $0B $22 $09 $22

L07AC39:
.db $09 $22 $09 $1F

L07AC3D:
.db $0B $1F $0B $1D

L07AC41:
.db $1C $23 $1C $21

L07AC45:
.db $1C $21 $1C $1F

L07AC49:
.db $16 $1F

L07AC4B:
.db $19 $1F $19 $1C

L07AC4F:
.db $0B $1B $0B $18

L07AC53:
.db $0E $18 $0E $1A

L07AC57:
.db $0A $18 $0A $17

L07AC5B:
.db $11 $1A $11 $18 $10 $18 $10 $16

L07AC63:
.db $10 $16 $10 $14 $0F $14 $0F $13

L07AC6B:
.db $11 $13 $11 $12 $15 $12

L07AC71:
.db $16 $16 $16 $13 $19 $13

L07AC77:
.db $16 $16 $16 $18 $19 $18

L07AC7D:
.db $1A $18 $1C $18 $1C $12

L07AC83:
.db $1B $13 $1B $12

L07AC87:
.db $05 $17 $05 $18

L07AC8B:
.db $03 $18 $03 $15

L07AC8F:
.db $03 $15 $03 $12 $05 $12

L07AC95:
.db $05 $12 $09 $12 $09 $10

L07AC9B:
.db $08 $0D $06 $0D $06 $0C $04 $0C

L07ACA3:
.db $08 $0D $08 $0B $09 $0B

L07ACA9:
.db $0B $0B $0B $0D $0E $0D

L07ACAF:
.db $0E $0D $0E $0A

L07ACB3:
.db $04 $0C $04 $09

L07ACB7:
.db $04 $09 $04 $06

L07ACBB:
.db $06 $06 $06 $08

L07ACBF:
.db $0A $08 $0A $06 $08 $06 $08 $05

L07ACC7:
.db $08 $05 $08 $04 $07 $04 $07 $03

L07ACCF:
.db $1A $0C $1A $0B $1B $0B $1B $09

L07ACD7:
.db $1B $09 $1A $09 $1A $0A $19 $0A

L07ACDF:
.db $1A $06 $1A $03

L07ACE3:
.db $0D $1D $11 $1D

L07ACE7:
.db $16 $10 $16 $0E $18 $0E $18 $0D
.db $1A $0D

L07ACF1:
.db $15 $12 $17 $12 $17 $10 $1B $10

L07ACF9:
.db $04 $0B $04 $09

L07ACFD:
.db $15 $03 $13 $03 $13 $02

L07AD03:
.db $09 $10 $09 $0E $08 $0E $08 $0D

L07AD0B:
.db $85 ; unknown where it stops
.db $04
.db $A9
.db $00
.db $85
.db $05
.db $A5
.db $78
.db $85
.db $00
.db $A5
.db $79
.db $85
.db $01
.db $A9
.db $84
.db $85
.db $02
.db $A9
.db $74
.db $85
.db $03
.db $4C
.db $09
.db $C2
.db $85
.db $04
.db $A9
.db $00
.db $85
.db $05
.db $A9
.db $84
.db $85
.db $00
.db $A9
.db $74
.db $85
.db $01
.db $A5
.db $7E
.db $38
.db $E9
.db $15
.db $85
.db $02
.db $A5
.db $7F
.db $E9
.db $00
.db $85
.db $03
.db $4C
.db $09
.db $C2

L07AD42:
    LDX $0501
    LDY $0500
    STX $00
    JSR L07AE59.w
    LDA #61
    STA ($72),Y
    LDA #0
    STA $C4
    STX $C7
    STY $C6
    JSR L07AD95.w
L07AD5C:
    INC $C4
    LDX #0
L07AD60:
    LDY #0
    TXA
    PHA
    ASL
    TAX
    LDA L0FEE22.w,X
    STA $72
    LDA (L0FEE22.w + 1),X
    STA $73
    PLA
    TAX
L07AD72:
    LDA ($72),Y
    AND #63
    CMP $C4
    BNE L07AD81
    STX $C7
    STY $C6
    JSR L07AD95.w
L07AD81:
    INY
    CPY #32
    BNE L07AD72
    INX
    CPX $7440
    BCC L07AD60
    BEQ L07AD60
    LDA $C4
    CMP $C5
    BNE L07AD5C
    RTS

L07AD95:
    TXA
    PHA
    TYA
    PHA
    LDX #0
L07AD9B:
    TXA
    ASL
    TAY
    LDA L07AE51.w,Y
    ADC $C6
    STA $03
    LDA (L07AE51.w + 1),Y
    CLC
    ADC $C7
    STA $02
    ASL
    TAY
    LDA L0FEE5E.w,Y
    STA $04
    LDA (L0FEE5E.w + 1),Y
    STA $05
    LDY $03
    LDA ($04),Y
    TAY
    LDA $7484
    ROL
    BCS L07ADC9
    LDA L0FE8DE.w,Y
    BPL L07ADCC
L07ADC9:
    LDA L0FE9DE.w,Y
L07ADCC:
    PHA
    CMP #31
    BCC L07ADE9
    PLA
    LDA $7484
    ROL
    BCS L07ADDD
    JSR L0FF280.w
    BCC L07ADE0
L07ADDD:
    JSR L0FF28B.w
L07ADE0:
    LDY #15
    LDA ($00),Y
    TAY
    LDA L0FE8DE.w,Y
    PHA
L07ADE9:
    LDY $0505
    DEY
    TYA
    ASL
    TAY
    LDA L0FEADE.w,Y
    STA $06
    LDA L0FEADF.w,Y
    STA $07
    PLA
    TAY
    LDA ($06),Y
    CLC
    ADC $C4
    BCC L07AE07
L07AE03:
    LDA #62
    BNE L07AE0B
L07AE07:
    CMP #61
    BCS L07AE03
L07AE0B:
    STA $09
    TXA
    CLC
    ROR
    ROR
    ROR
    ORA $09
    STA $0A
    LDA $02
    ASL
    TAY
    LDA L0FEE22.w,Y
    STA $72
    LDA (L0FEE22.w + 1),Y
    STA $73
    LDY $03
    LDA ($72),Y
    AND #63
    BEQ L07AE40
    CMP #60
    BCS L07AE44
    CMP $09
    BNE L07AE3E
    JSR L0FC04E.w
    CMP #128
    BCC L07AE40
    JMP L07AE44.w

L07AE3E:
    BCC L07AE44
L07AE40:
    LDA $0A
    STA ($72),Y
L07AE44:
    INX
    CPX #4
    BEQ L07AE4C
    JMP L07AD9B.w

L07AE4C:
    PLA
    TAY
    PLA
    TAX
    RTS

L07AE51:
.db $00 $FF
.db $01 $00
.db $00 $01
.db $FF $00

L07AE59:
    TYA
    PHA
    TXA
    PHA
    LDA $00
    ASL
    TAX
    LDA L0FEE22.w,X
    STA $72
    LDA (L0FEE22.w + 1),X
    STA $73
    PLA
    TAX
    PLA
    TAY
    RTS

.dw L07AF18
.dw L07AE9A
.dw L07AF76
.dw L07AFC8
.dw L07B709
.dw L07B037
.dw L07AF76
.dw L07B070
.dw L07B0F0
.dw L07B254
.dw L07B162
.dw L07B1E7
.dw L07B20E
.dw L07B2EB
.dw L07B3BC
.dw L07B5B7
.dw L07B77D
.dw L07B867
.dw L07B8F0
.dw L07B951
.dw L07B99A


L07AE9A:
.db $30 $80 $14 $04 $E8 $50 $30 $81
.db $E9 $04 $DF $76 $F1 $EA $15 $16
.db $9D $9D $FF $ED $3C $5B $31 $40
.db $0F $3F $05 $0F $FF $25 $28 $2B
.db $10 $14 $9D $9C $E1 $0A $ED $EA
.db $07 $0E $FF $1A $2F $28 $2F $07
.db $0F $2F $19 $25 $12 $28 $23 $ED
.db $04 $1E $0F $03 $13 $04 $2B $27
.db $E1 $0A $ED $EA $2D $0B $1A $FF
.db $10 $01 $06 $84 $07 $0C $2A $ED
.db $1D $01 $10 $01 $14 $0F $24 $9D
.db $FF $ED $00 $14 $1A $20 $05 $0D
.db $10 $0E $0F $9D $9D $E1 $0A $ED
.db $ED $ED $FF $FF $44 $0F $3D $0F
.db $3F $1A $FF $16 $08 $0F $10 $0F
.db $0B $10 $ED $E1 $08 $EF

L07AF18:
.db $30 $80 $14 $04 $E8 $50 $30 $81
.db $E9 $04 $DF $B4 $F1 $EA $1A $2F
.db $28 $2F $07 $0F $2F $19 $ED $22
.db $0B $08 $28 $14 $0F $24 $23 $EE
.db $EA $04 $20 $03 $10 $11 $16 $FF
.db $09 $19 $2D $0B $05 $0F $ED $10
.db $04 $0D $2A $14 $FF $04 $24 $02
.db $19 $05 $EE $EA $3C $5B $31 $40
.db $0F $3F $27 $ED $06 $1D $01 $10
.db $01 $2E $1B $06 $01 $13 $ED $25
.db $12 $28 $2E $FF $08 $11 $28 $0C
.db $19 $10 $0F $9D $9D $EF

L07AF76:
.db $30 $80 $14 $04 $E8 $50 $30 $12
.db $E9 $04 $DF $B4 $F1 $EA $35 $52
.db $31 $8E $5B $34 $ED $17 $05 $2A
.db $15 $27 $9D $9D $EE $EA $40 $0F
.db $89 $4A $0A $03 $FF $10 $04 $0D
.db $1A $0F $ED $09 $1C $0F $2F $10
.db $11 $1A $FF $16 $08 $0F $10 $0F
.db $0C $1A $0C $0F $10 $0F $EE $EA
.db $0E $2B $9D $ED $40 $0F $89 $4A
.db $2E $FF $25 $85 $11 $20 $03 $9D
.db $9D $EF

L07AFC8:
.db $30 $80 $14 $04 $E8 $50 $30 $81
.db $E9 $04 $DF $B4 $F1 $EA $15 $16
.db $FF $1A $2F $28 $2F $07 $0F $2F
.db $19 $25 $12 $28 $05 $0F $ED $09
.db $19 $14 $29 $13 $0F $20 $13 $0F
.db $FF $ED $0D $23 $13 $06 $10 $19
.db $05 $EE $EA $07 $0E $9D $9D $FF
.db $15 $28 $1A $0F $FF $21 $0D $0B
.db $23 $16 $ED $1E $29 $87 $2E $FF
.db $0B $87 $08 $01 $0B $13 $25 $2A
.db $EE $EA $26 $21 $1C $0F $10 $01
.db $9D $ED $2C $02 $25 $19 $FF $09
.db $22 $0C $23 $2E $ED $0B $87 $08
.db $01 $0D $27 $9D $9D $9D $EF

L07B037:
.db $30 $80 $14 $04 $E8 $50 $30 $20
.db $E9 $04 $DF $B4 $F1 $EA $00 $1C
.db $0F $15 $01 $FF $35 $41 $8A $30
.db $9D $ED $05 $2B $28 $1A $FF $14
.db $02 $0E $0F $07 $27 $EE $2D $10
.db $0B $19 $FF $0E $1A $0F $2E $ED
.db $1A $15 $2B $15 $01 $13 $0F $9D
.db $EF

L07B070:
.db $30 $80 $14 $04 $E8 $50 $30 $82
.db $E9 $04 $DF $B4 $F1 $EA $1C $1C
.db $1C $9B $9B $9B $ED $1A $0F $05
.db $15 $FF $25 $12 $28 $23 $ED $EA
.db $2D $0A $0F $2D $0A $0F $FF $0B
.db $17 $10 $23 $16 $ED $09 $09 $20
.db $13 $0F $06 $10 $05 $EE $EA $09
.db $19 $FF $36 $0F $3F $3C $0A $20
.db $19 $11 $05 $28 $05 $0F $ED $14
.db $0F $2F $15 $24 $19 $05 $ED $04
.db $24 $01 $0B $28 $0D $13 $25 $2C
.db $02 $0E $0F $EE $EA $26 $08 $FF
.db $24 $19 $14 $0F $24 $9D $ED $25
.db $12 $28 $2E $FF $1B $14 $29 $10
.db $29 $14 $24 $ED $01 $05 $0B $13
.db $05 $03 $0C $15 $9D $9D $9D $EF

L07B0F0:
.db $30 $80 $14 $04 $E8 $50 $30 $8F
.db $E9 $04 $DF $B4 $F1 $EA $1C $9A
.db $1C $9A $1C $9A $FF $04 $20 $03
.db $10 $11 $16 $FF $ED $09 $19 $40
.db $40 $58 $0A $20 $05 $0F $ED $10
.db $04 $0D $2A $14 $04 $24 $02 $19
.db $05 $EE $EA $43 $0F $8A $3F $43
.db $27 $ED $00 $19 $FF $04 $2C $05
.db $24 $19 $10 $11 $2E $ED $04 $20
.db $03 $19 $34 $3F $58 $13 $0F $FF
.db $0B $87 $02 $23 $12 $0A $0D $27
.db $EE $EA $25 $12 $28 $16 $FF $13
.db $2F $1A $0F $12 $2E $ED $00 $10
.db $03 $2A $19 $10 $0F $9D $9D $9D
.db $EF $EF

L07B162:
.db $30 $80 $14 $04 $E8 $50 $30 $93
.db $E9 $06 $F1 $EA $1C $1C $1C $9B
.db $9B $9B $FF $1A $0F $05 $15 $25
.db $12 $28 $23 $ED $01 $20 $04 $20
.db $03 $10 $11 $05 $0F $FF $10 $04
.db $0B $10 $19 $1A $ED $44 $0F $3D
.db $0F $3F $0A $20 $19 $FF $05 $03
.db $10 $0F $20 $10 $0F $ED $EA $44
.db $0F $3D $0F $3F $0A $20 $1A $FF
.db $0C $13 $0F $16 $ED $0B $0F $1C
.db $0F $2F $19 $29 $87 $02 $11 $16
.db $FF $05 $03 $28 $2B $10 $ED $EA
.db $01 $0C $0F $2B $FF $09 $19 $2B
.db $01 $1A $FF $10 $85 $1C $1F $29
.db $14 $ED $0A $0D $13 $24 $28 $04
.db $02 $FF $0A $28 $1A $0F $10 $0F
.db $9D $9D $E1 $10 $EF

L07B1E7:
.db $30 $40 $14 $03 $E9 $01 $F1 $EA
.db $40 $0F $89 $4A $04 $25 $1C $0F
.db $2F $05 $0F $FF $25 $28 $2B $10
.db $9D $ED $21 $2F $15 $FF $16 $08
.db $0F $2C $3F $3F $E1 $08 $EF

L07B20E:
.db $30 $80 $14 $04 $E8 $50 $30 $1D
.db $E9 $04 $F1 $EA $1A $85 $9D $ED
.db $09 $09 $1A $FF $01 $85 $10 $01
.db $9B $9B $9B $9B $ED $EA $2D $10
.db $0B $1A $FF $15 $0D $0F $ED $09
.db $2F $15 $14 $09 $2C $16 $01 $2A
.db $19 $9C $ED $EA $10 $0C $08 $13
.db $9D $ED $59 $8A $3F $44 $16 $01
.db $0A $3F $2F $E1 $10 $EF

L07B254:
.db $30 $80 $14 $04 $E8 $50 $30 $02
.db $E9 $04 $DF $B4 $F1 $EA $00 $85
.db $FF $21 $2F $15 $FF $21 $03 $2A
.db $13 $0F $0B $87 $ED $00 $2B $05
.db $0F $FF $51 $58 $19 $0B $2F $13
.db $0F $2F $27 $9D $EE $EA $13 $0F
.db $24 $21 $2F $15 $FF $26 $10 $0F
.db $2F $0B $15 $01 $13 $0F $EE $EA
.db $09 $09 $2E $FF $20 $24 $85 $13
.db $01 $2A $19 $1A $ED $44 $0F $3F
.db $50 $19 $06 $14 $02 $0B $51 $35
.db $33 $58 $EE $EA $05 $2B $1A $FF
.db $35 $0F $3F $39 $0F $31 $5A $2E
.db $ED $27 $1B $0F $10 $0F $0C $14
.db $FF $01 $2D $2B $13 $01 $2A $19
.db $EE $EA $21 $2F $15 $FF $0E $1A
.db $0F $16 $27 $85 $13 $ED $27 $2D
.db $01 $15 $05 $20 $2E $FF $20 $24
.db $85 $13 $00 $08 $0F $13 $EF

L07B2EB:
.db $30 $80 $14 $04 $E8 $50 $30 $86
.db $E9 $04 $DF $A5 $F1 $EA $1C $1C
.db $1C $FF $12 $01 $16 $FF $25 $85
.db $13 $06 $10 $15 $EE $EA $09 $09
.db $1A $FF $44 $0F $3F $50 $19 $0A
.db $01 $10 $0F $2F $EE $EA $09 $09
.db $16 $06 $10 $05 $28 $16 $1A $ED
.db $24 $02 $FF $01 $06 $13 $1A $05
.db $03 $2B $17 $EE $EA $2D $2B $28
.db $FF $44 $0F $3F $50 $06 $87 $02
.db $1A $ED $1B $14 $19 $07 $2A $0B
.db $21 $2E $ED $24 $85 $14 $24 $FF
.db $14 $02 $14 $1C $0F $EE $EA $10
.db $0F $05 $28 $FF $0C $07 $0F $16
.db $1A $FF $09 $2C $0A $17 $EE $EA
.db $26 $85 $07 $29 $14 $FF $0C $09
.db $0B $0C $0F $12 $ED $07 $2A $0B
.db $21 $15 $05 $0F $28 $FF $0B $2F
.db $13 $0F $26 $07 $19 $0B $0F $84
.db $EE $EA $04 $20 $03 $10 $11 $19
.db $FF $07 $2A $0B $22 $0C $05 $0F
.db $10 $09 $0E $ED $44 $0F $3F $50
.db $0A $20 $16 $14 $85 $13 $1A $FF
.db $0A $01 $0B $0F $87 $02 $19 $ED
.db $09 $0F $11 $0E $02 $15 $19 $10
.db $0F $05 $28 $15 $9B $9B $9B $9B
.db $EF

L07B3BC:
.db $30 $80 $14 $05 $E8 $40 $30 $01
.db $E9 $04 $F1 $F0 $01 $EA $10 $0F
.db $01 $0B $0F $87 $02 $1C $0F $05
.db $FF $3D $59 $35 $9D $E6 $E8 $60
.db $30 $02 $F0 $02 $EA $30 $5A $52
.db $9B $9B $9B $9B $E6 $F0 $01 $EA
.db $00 $00 $FF $24 $02 $10 $0F $01
.db $0B $0F $87 $02 $1C $0F $0A $ED
.db $09 $2F $15 $25 $12 $28 $FF $1E
.db $0F $07 $05 $0F $ED $1B $18 $29
.db $12 $1C $0F $0B $13 $25 $2A $E6
.db $F0 $02 $EA $10 $0F $23 $27 $8F
.db $3B $8A $40 $0F $1A $FF $1C $0B
.db $06 $0F $15 $11 $05 $28 $2E $ED
.db $24 $85 $13 $01 $13 $FF $14 $0F
.db $2F $15 $09 $02 $08 $0F $06 $2E
.db $24 $ED $0A $03 $06 $0F $85 $13
.db $0B $20 $02 $EE $EA $0E $2B $16
.db $FF $22 $0C $02 $19 $4B $0F $37
.db $0F $5A $05 $0F $ED $05 $28 $21
.db $12 $01 $13 $06 $13 $FF $24 $02
.db $ED $21 $02 $09 $0F $06 $0A $03
.db $FF $13 $0F $06 $15 $01 $EE $EA
.db $2D $10 $0B $10 $11 $FF $ED $24
.db $02 $10 $0F $23 $05 $24 $0B $2B
.db $15 $01 $2D $9B $9B $9B $EE $EA
.db $09 $0F $23 $2F $18 $30 $5A $52
.db $EE $EA $25 $85 $1A $1F $29 $FF
.db $2D $10 $0B $1A $FF $00 $15 $10
.db $16 $ED $15 $16 $24 $0B $13 $00
.db $08 $0F $28 $2B $15 $05 $85 $10
.db $EE $EA $1C $0B $06 $0F $15 $FF
.db $27 $05 $2F $05 $0F $00 $85 $13
.db $9B $9B $9B $ED $EA $30 $5A $52
.db $16 $FF $14 $13 $24 $FF $1B $14
.db $0F $01 $09 $14 $05 $0F $ED $04
.db $09 $2A $27 $02 $15 $06 $05 $0F
.db $0B $13 $9B $9B $9B $EE $EA $10
.db $0F $05 $28 $FF $2D $10 $0B $1A
.db $ED $51 $58 $19 $10 $0C $08 $2E
.db $FF $24 $14 $23 $27 $02 $14 $ED
.db $09 $09 $20 $13 $0F $06 $10 $9B
.db $9B $9B $EE $EA $10 $0F $05 $28
.db $FF $0E $2B $20 $13 $0F $1A $FF
.db $30 $5A $52 $16 $FF $ED $10 $10
.db $05 $85 $13 $1E $0B $07 $15 $05
.db $85 $10 $EE $EA $0E $2B $13 $0F
.db $9B $9B $00 $2F $15 $16 $FF $12
.db $23 $10 $07 $0B $13 $ED $09 $0F
.db $23 $2F $18 $9B $9B $FF $1E $2F
.db $14 $1A $FF $0C $0F $85 $14 $9B
.db $9B $E6 $F0 $01 $EA $24 $02 $01
.db $01 $FF $2D $05 $85 $13 $01 $2A
.db $EE $EA $14 $16 $05 $07 $3D $59
.db $35 $9D $FF $ED $01 $20 $1A $FF
.db $16 $08 $0F $2A $2F $10 $0F $9D
.db $9D $9D $EE $EA $1E $0F $07 $05
.db $0F $06 $85 $14 $FF $10 $0C $08
.db $2A $9D $EE $EA $06 $85 $14 $FF
.db $10 $0C $08 $2A $05 $28 $FF $1E
.db $0F $07 $2E $0B $2F $0B $0F $13
.db $EE $EA $05 $0F $2F $1A $0F $2A
.db $2F $10 $0F $27 $FF $3D $59 $35
.db $9D $9D $EF

L07B5B7:
.db $30 $80 $14 $04 $E8 $50 $30 $85
.db $E9 $04 $DF $B4 $F1 $EA $0E $02
.db $05 $FF $12 $01 $16 $06 $10 $05
.db $9B $9B $9B $EE $EA $09 $19 $02
.db $03 $1A $FF $0D $0F $1B $24 $15
.db $01 $ED $03 $01 $09 $02 $00 $2A
.db $FF $59 $38 $0F $5A $06 $0B $10
.db $0F $2F $14 $0B $13 $ED $0A $01
.db $09 $0F $19 $10 $10 $05 $01 $2E
.db $FF $21 $0D $13 $25 $2C $02 $EE
.db $EA $59 $38 $0F $5A $19 $FF $26
.db $02 $05 $2F $15 $2A $1D $01 $0B
.db $10 $11 $27 $ED $27 $07 $0E $0F
.db $FF $09 $09 $20 $13 $0F $FF $2D
.db $0B $14 $14 $24 $16 $ED $10 $10
.db $05 $85 $13 $06 $13 $07 $2B $10
.db $EE $EA $10 $0F $05 $0F $9B $9B
.db $9B $FF $14 $06 $0C $13 $0F $16
.db $04 $0E $07 $ED $59 $38 $0F $5A
.db $13 $01 $09 $07 $19 $FF $23 $01
.db $02 $2F $1A $12 $06 $10 $EE $EA
.db $06 $08 $FF $21 $15 $19 $24 $19
.db $9D $9D $9D $ED $2D $0B $05 $28
.db $19 $FF $0A $01 $09 $0F $19 $10
.db $19 $21 $10 $0F $EE $EA $24 $0B
.db $FF $2D $0B $05 $0F $FF $10 $04
.db $2B $2B $1A $0F $ED $0E $19 $14
.db $06 $1A $FF $05 $20 $02 $09 $14
.db $1A $15 $01 $EE $EA $19 $09 $85
.db $10 $24 $19 $1A $FF $ED $01 $0A
.db $06 $0F $27 $07 $FF $09 $02 $1C
.db $07 $0D $27 $EE $EA $3E $4C $A7
.db $30 $19 $FF $2D $05 $01 $0B $87
.db $02 $07 $0F $2F $1A $ED $15 $0A
.db $08 $00 $2A $24 $19 $14 $FF $06
.db $01 $13 $01 $2A $EE $EA $08 $85
.db $0B $13 $FF $2D $2A $01 $27 $02
.db $16 $1A $ED $0B $15 $01 $10 $0F
.db $2C $02 $EE $EA $27 $01 $15 $FF
.db $22 $10 $0F $0B $0F $16 $1A $0C
.db $2A $15 $ED $01 $19 $11 $2E $FF
.db $0E $20 $12 $16 $0C $2A $15 $27
.db $9D $EF

L07B709:
.db $30 $80 $14 $04 $E8 $50 $30 $01
.db $E9 $04 $DF $B4 $F1 $EA $21 $2F
.db $15 $FF $26 $10 $0F $2F $0C $2A
.db $15 $ED $59 $38 $0F $5A $19 $FF
.db $10 $0F $01 $1C $0F $10 $01 $05
.db $0F $07 $2A $EE $EA $06 $0B $10
.db $0F $2F $1A $FF $20 $03 $1D $ED
.db $20 $1E $02 $1C $0F $10 $01 $1A
.db $FF $02 $0B $2C $1D $0A $05 $0F
.db $85 $13 $ED $20 $24 $29 $2E $FF
.db $05 $10 $23 $2C $EE $EA $13 $06
.db $2E $FF $1C $0F $2F $0A $2F $0B
.db $13 $ED $1B $14 $29 $0C $0F $12
.db $FF $10 $04 $0B $13 $26 $07 $2F
.db $10 $0F $9D $EF

L07B77D:
.db $30 $80 $14 $04 $E9 $04 $DF $B4
.db $F1 $EA $1C $05 $06 $FF $0B $85
.db $09 $07 $19 $25 $21 $19 $15 $05
.db $16 $ED $05 $2B $28 $2E $21 $04
.db $2C $0C $ED $1C $0F $06 $21 $15
.db $FF $05 $04 $05 $0F $00 $2A $EE
.db $EA $04 $0E $2B $0A $0F $2F $19
.db $FF $17 $0B $14 $27 $1A $0F $2B
.db $ED $10 $0F $2B $24 $05 $0F $FF
.db $04 $0E $2B $04 $19 $19 $07 $ED
.db $13 $0F $2F $0D $12 $19 $27 $02
.db $0B $0F $86 $12 $0B $ED $47 $31
.db $4A $0F $4A $0F $9B $9B $9B $EE
.db $EA $10 $20 $0B $01 $14 $FF $1B
.db $06 $05 $03 $16 $03 $10 $ED $0E
.db $19 $00 $2F $09 $07 $0B $0F $86
.db $24 $2F $05 $0F $FF $1B $14 $10
.db $1B $0F $FF $ED $05 $2B $19 $07
.db $11 $05 $28 $1A $85 $0C $2B $1A
.db $0F $EE $EA $01 $08 $14 $0B $01
.db $06 $2A $24 $19 $FF $0C $1D $0F
.db $13 $16 $ED $05 $07 $0B $0F $12
.db $15 $FF $0B $05 $0F $04 $14 $0C
.db $0F $2B $2A $EE $EA $30 $5A $52
.db $27 $FF $15 $0D $0F $01 $07 $9C
.db $ED $09 $19 $04 $0E $2C $0B $01
.db $FF $25 $20 $19 $15 $05 $16 $ED
.db $01 $85 $10 $01 $15 $16 $05 $0F
.db $FF $00 $2A $14 $01 $02 $19 $10
.db $0F $EF

L07B867:
.db $30 $80 $14 $04 $E8 $50 $30 $83
.db $E9 $04 $DF $B4 $F1 $EA $9B $9B
.db $9B $07 $0F $1C $1C $1C $9B $9B
.db $ED $2D $2B $05 $0F $FF $0B $1A
.db $01 $0C $2A $FF $09 $19 $ED $0B
.db $1B $0F $14 $19 $17 $20 $2E $FF
.db $04 $05 $0C $24 $19 $10 $11 $27
.db $EE $EA $3B $0F $8A $40 $0F $0A
.db $20 $19 $FF $23 $01 $16 $0B $10
.db $05 $0F $01 $ED $01 $05 $0B $13
.db $1A $FF $05 $03 $0A $17 $EE $EA
.db $09 $19 $FF $10 $0F $01 $06 $14
.db $02 $0B $44 $0F $5A $37 $0A $20
.db $05 $0F $ED $23 $01 $05 $01 $27
.db $29 $FF $27 $1B $0F $27 $0D $0B
.db $ED $0B $29 $86 $02 $19 $FF $03
.db $0B $0F $06 $14 $15 $2B $9D $9D
.db $EF

L07B8F0:
.db $30 $80 $14 $04 $E8 $50 $30 $86
.db $E9 $04 $DF $A5 $F1 $EA $1C $1C
.db $1C $FF $05 $2D $01 $01 $24 $19
.db $27 $15 $9B $9B $ED $10 $0F $05
.db $0F $FF $20 $10 $0F $09 $2C $0B
.db $1A $0D $17 $ED $EA $30 $5A $52
.db $14 $05 $01 $02 $FF $09 $0E $0F
.db $02 $2E $ED $02 $0B $15 $01 $10
.db $07 $15 $07 $1A $0F $ED $22 $0C
.db $23 $27 $9B $9B $9B $ED $44 $0F
.db $3F $50 $19 $14 $02 $1D $FF $19
.db $1E $0F $85 $13 $09 $01 $E1 $10
.db $EF

L07B951:
.db $30 $80 $14 $04 $E8 $50 $30 $22
.db $E9 $04 $DF $B4 $F1 $EA $15 $16
.db $9C $FF $43 $A7 $3F $40 $05 $0F
.db $ED $10 $0C $08 $10 $0F $0A $2B
.db $10 $19 $05 $EE $EA $27 $0B $9D
.db $FF $0D $0F $2F $07 $0F $2F $ED
.db $3B $0F $A9 $5C $3F $52 $19 $1C
.db $0F $10 $01 $16 $ED $14 $12 $08
.db $0F $06 $0D $27 $9D $9D $EF $9A
.db $B9

L07B99A:
.db $30 $80 $14 $03 $E8 $50 $30 $86
.db $E9 $02 $DF $A5 $F1 $EA $09 $0A
.db $0F $05 $0B $01 $09 $2D $85 $1A
.db $1F $23 $9D $ED $2D $05 $0F $19
.db $2C $01 $2E $FF $02 $08 $2A $05
.db $0F $27 $01 $9D $EF $3D $C7 $DB
.db $B9 $F5 $B9 $59 $BA $8E $BA $C8
.db $BA $08 $BB $39 $BB $7E $BB $AC
.db $BB $30 $80 $14 $03 $E9 $04 $DF
.db $76 $F1 $EA $0B $18 $9D $1A $2F
.db $28 $2F $1D $01 $14 $0F $24 $ED
.db $E1 $10 $EF $30 $80 $14 $04 $E9
.db $04 $DF $76 $F1 $EA $09 $19 $05
.db $01 $0E $0F $07 $FF $40 $0F $89
.db $4A $0A $20 $16 $ED $08 $2F $05
.db $2E $02 $2A $10 $96 $FF $01 $01
.db $14 $0F $06 $87 $02 $10 $0F $ED
.db $09 $19 $04 $19 $13 $0F $FF $10
.db $10 $06 $06 $85 $13 $25 $2A $E1
.db $10 $EF $30 $80 $14 $03 $E8 $50
.db $30 $8E $E9 $04 $DF $76 $F1 $EA
.db $44 $3F $50 $27 $9B $9B $9B $ED
.db $2D $2B $16 $FF $11 $05 $28 $2E
.db $00 $10 $03 $27 $E1 $10 $EF $30
.db $80 $14 $04 $E8 $50 $30 $84 $E9
.db $04 $DF $76 $F1 $EA $9B $9B $9B
.db $01 $13 $0F $27 $FF $53 $43 $0F
.db $8A $3F $3A $ED $01 $20 $09 $0E
.db $FF $2D $2B $14 $19 $08 $01 $25
.db $07 $2E $ED $1A $10 $0C $1D $0F
.db $0B $E1 $10 $EF $30 $80 $14 $04
.db $E8 $50 $30 $8B $E9 $04 $DF $76
.db $F1 $EA $2D $10 $0B $14 $13 $FF
.db $10 $10 $05 $01 $10 $07 $1A $ED
.db $15 $01 $19 $10 $0F $FF $0B $05
.db $0B $9B $9B $ED $10 $10 $05 $2D
.db $18 $1A $0F $9B $9B $9B $9B $FF
.db $0C $20 $17 $E1 $10 $EF $30 $80
.db $14 $04 $E8 $50 $30 $88 $E9 $04
.db $DF $76 $F1 $EA $06 $0A $20 $10
.db $11 $16 $FF $02 $28 $21 $1A $15
.db $01 $05 $0F $ED $26 $03 $00 $85
.db $13 $FF $13 $06 $16 $20 $2D $2A
.db $ED $2D $05 $0F $08 $2F $FF $14
.db $07 $14 $00 $0B $0F $2D $02 $05
.db $0F $01 $01 $E1 $10 $EF $30 $80
.db $14 $03 $E8 $50 $30 $87 $E9 $04
.db $DF $76 $F1 $EA $1C $1C $1C $FF
.db $04 $0B $0F $87 $02 $11 $84 $2F
.db $10 $11 $ED $2D $2A $01 $08 $14
.db $0F $FF $0B $2F $13 $0F $24 $28
.db $02 $2D $27 $9D $E1 $10 $EF $30
.db $80 $14 $04 $E8 $50 $30 $82 $E9
.db $04 $DF $76 $F1 $EA $07 $85 $FF
.db $2D $05 $0F $04 $02 $09 $07 $24
.db $ED $24 $1A $25 $09 $2B $20 $13
.db $0F $05 $ED $15 $28 $1A $0F $FF
.db $04 $20 $03 $10 $11 $24 $ED $0B
.db $0F $09 $0F $07 $19 $FF $21 $11
.db $12 $0F $2B $16 $0B $13 $25 $2C
.db $02 $E1 $10 $EF $30 $80 $14 $04
.db $E8 $50 $30 $91 $E9 $04 $DF $76
.db $F1 $EA $40 $40 $58 $3A $50 $46
.db $FF $3A $35 $58 $32 $34 $50 $33
.db $40 $41 $ED $9B $9B $9B $9B $9B
.db $9B $9B $9B $FF $39 $5C $3C $E1
.db $10 $EF $30 $80 $14 $04 $E8 $50
.db $30 $81 $E9 $04 $DF $76 $F1 $EA
.db $04 $20 $03 $10 $11 $05 $0F $FF
.db $20 $0A $05 $FF $ED $09 $2B $1E
.db $14 $0F $FF $13 $0F $06 $2A $14
.db $1A $15 $9B $9B $9B $ED $10 $0F
.db $05 $0F $FF $09 $19 $44 $0F $3D
.db $0F $3F $1A $ED $0E $02 $05 $2F
.db $10 $2F $16 $1A $FF $10 $04 $0D
.db $17 $0E $0F $9D $E1 $10 $EF $00
.db $40 $41 $00 $00 $00 $00 $10 $0C
.db $00 $28 $11 $00 $71 $80 $EC $20
.db $38 $52 $24 $25 $A1 $06 $10 $11
.db $01 $88 $09 $01 $10 $00 $00 $44
.db $08 $01 $04 $41 $41 $25 $40 $00
.db $04 $84 $00 $19 $08 $82 $71 $99
.db $10 $10 $40 $6F $CB $80 $C1 $21
.db $00 $40 $20 $D4 $06 $10 $C4 $01
.db $40 $10 $00 $3E $00 $19 $41 $00
.db $50 $50 $00 $08 $00 $01 $69 $02
.db $E7 $71 $2C $6C $8E $02 $10 $40
.db $02 $00 $08 $00 $80 $00 $80 $92
.db $16 $80 $01 $2F $00 $54 $20 $30
.db $00 $00 $02 $00 $00 $20 $44 $11
.db $24 $06 $01 $42 $48 $92 $20 $00
.db $00 $40 $80 $0C $80 $1C $5C $02
.db $60 $44 $01 $4A $1C $05 $02 $80
.db $02 $10 $00 $00 $00 $00 $C4 $94
.db $41 $41 $11 $5F $B4 $10 $40 $01
.db $40 $80 $00 $00 $04 $48 $10 $09
.db $05 $50 $2E $03 $24 $04 $00 $00
.db $80 $00 $0A $28 $00 $00 $00 $A0
.db $21 $0A $00 $86 $89 $45 $02 $50
.db $04 $00 $C0 $C4 $11 $00 $C0 $81
.db $91 $00 $E2 $C0 $14 $00 $50 $00
.db $02 $00 $00 $03 $32 $00 $42 $24
.db $80 $01 $09 $04 $84 $2A $21 $20
.db $00 $00 $00 $00 $21 $00 $0C $F0
.db $E9 $48 $94 $14 $48 $1C $00 $00
.db $00 $09 $04 $04 $28 $04 $4C $81
.db $03 $03 $A2 $10 $69 $22 $00 $00
.db $10 $08 $00 $83 $A0 $80 $00 $72
.db $12 $00 $00 $51 $06 $50 $00 $00
.db $00 $24 $01 $00 $06 $04 $02 $86
.db $22 $64 $8C $41 $24 $82 $00 $00
.db $40 $21 $01 $00 $00 $01 $48 $09
.db $02 $04 $04 $1C $18 $00 $00 $0C
.db $00 $00 $04 $00 $81 $40 $54 $74
.db $88 $44 $8A $00 $22 $B0 $00 $59
.db $10 $01 $00 $00 $00 $00 $0C $46
.db $01 $62 $00 $00 $04 $59 $A0 $80
.db $00 $01 $10 $00 $00 $40 $89 $59
.db $64 $4A $A0 $9A $0E $60 $00 $A8
.db $06 $08 $00 $10 $90 $00 $20 $10
.db $00 $91 $52 $58 $99 $11 $35 $90
.db $20 $05 $00 $0C $0A $29 $34 $A6
.db $12 $9A $44 $47 $80 $01 $20 $00
.db $01 $00 $00 $E1 $00 $00 $98 $76
.db $07 $41 $10 $20 $03 $45 $04 $00
.db $00 $50 $09 $80 $10 $02 $42 $40
.db $12 $97 $80 $C8 $44 $E9 $02 $80
.db $00 $14 $08 $02 $01 $10 $60 $CB
.db $66 $42 $50 $00 $D0 $00 $03 $00
.db $21 $40 $00 $20 $40 $06 $06 $29
.db $12 $02 $40 $D1 $14 $88 $00 $C1
.db $00 $00 $04 $00 $10 $24 $40 $31
.db $00 $04 $A1 $22 $42 $24 $00 $10
.db $40 $10 $42 $20 $81 $20 $87 $52
.db $A1 $42 $75 $10 $02 $50 $10 $00
.db $00 $38 $00 $00 $00 $01 $00 $01
.db $10 $04 $51 $48 $CD $11 $01 $51
.db $00 $08 $21 $50 $00 $40 $BB $08
.db $67 $82 $19 $40 $40 $35 $02 $00
.db $00 $A4 $10 $43 $00 $00 $00 $85
.db $50 $11 $C5 $40 $80 $00 $00 $70
.db $00 $08 $00 $08 $00 $00 $0A $18
.db $A0 $34 $12 $10 $11 $7C $84 $00
.db $90 $01 $00 $00 $00 $00 $82 $70
.db $50 $70 $09 $11 $14 $77 $04 $00
.db $00 $08 $40 $00 $05 $40 $59 $A2
.db $02 $00 $AC $40 $88 $54 $00 $0D
.db $00 $00 $00 $02 $09 $32 $C9 $10
.db $82 $00 $10 $D8 $01 $10 $02 $40
.db $02 $80 $10 $A0 $40 $01 $80 $70
.db $40 $00 $55 $D0 $E1 $A5 $22 $30
.db $00 $02 $08 $08 $08 $00 $43 $60
.db $83 $83 $10 $00 $45 $48 $08 $00
.db $00 $04 $08 $10 $50 $20 $14 $20
.db $08 $82 $13 $C4 $49 $52 $44 $06
.db $00 $10 $00 $00 $40 $00 $11 $11
.db $83 $21 $01 $0D $31 $0C $12 $12
.db $10 $00 $00 $84 $20 $42 $44 $CA
.db $2E $00 $4C $80 $1B $22 $88 $00
.db $40 $02 $01 $80 $40 $40 $02 $08
.db $83 $C0 $D0 $60 $8C $20 $00 $09
.db $00 $88 $02 $00 $40 $00 $9A $70
.db $08 $98 $02 $82 $25 $04 $01 $00
.db $00 $9C $82 $A1 $20 $41 $11 $E8
.db $10 $40 $04 $41 $40 $54 $00 $82
.db $00 $00 $A0 $60 $00 $00 $4D $0D
.db $10 $00 $40 $41 $01 $92 $44 $10
.db $00 $A0 $02 $06 $83 $69 $A1 $07
.db $11 $07 $04 $04 $00 $14 $02 $00
.db $0B $11 $41 $0C $00 $A2 $44 $88
.db $13 $84 $08 $A1 $10 $00 $10 $00
.db $18 $02 $02 $C1 $00 $48 $0A $00
.db $44 $24 $40 $04 $02 $00 $00 $00
.db $21 $00 $00 $00 $00 $00 $41 $03
.db $02 $FC $9E $E6 $10 $E5 $21 $40
.db $00 $A6 $40 $22 $00 $08 $E0 $25
.db $10 $5C $17 $03 $A1 $24 $88 $00
.db $02 $20 $01 $4D $01 $00 $5E $00
.db $33 $08 $40 $83 $08 $A0 $09 $20
.db $10 $41 $04 $00 $00 $05 $10 $10
.db $50 $40 $90 $40 $00 $58 $33 $00
.db $00 $00 $24 $02 $00 $04 $01 $10
.db $67 $B6 $60 $02 $83 $42 $10 $00
.db $10 $00 $00 $01 $00 $02 $B2 $85
.db $40 $18 $00 $51 $04 $54 $00 $00
.db $0A $80 $08 $00 $04 $01 $CA $08
.db $20 $00 $18 $25 $D4 $85 $20 $20
.db $50 $3A $00 $20 $14 $00 $00 $02
.db $80 $44 $84 $00 $18 $01 $92 $00
.db $4A $00 $14 $40 $25 $C0 $14 $12
.db $00 $80 $E1 $09 $24 $18 $00 $00
.db $80 $00 $10 $10 $00 $20 $20 $04
.db $10 $E8 $05 $65 $11 $04

L07BFA0:
.dw L078500
.dw L078A02
.dw L078A03
.dw L078A84
.dw L079A34
.dw L0797C9
.dw L0797D7
.dw L078B81
.dw L078E80
.dw L079136
.dw L07960B
.dw L07A5EC
.dw L07AD42

.db $08 $03 $01 $03 $A0 $01 $BE $A3
.db $04 $05 $00 $30 $80 $60 $53 $23
.db $7A $51 $01 $96 $38 $D8 $4C $A4
.db $00 $78 $00 $40 $20 $42 $00 $51
.db $24 $00 $08 $14 $40 $41 $98 $B9
.db $70 $AE $C7 $B9 $00 $00 $08 $40
.db $10 $28 $68 $A8 $21 $48 $00 $01
.db $00 $02 $00 $40 $01 $FF $41 $90
.db $00 $14 $40 $00 $01 $10

.ENDS
